- XBMC Remote/DetailViewController.m
- XBMC Remote/RemoteController.m
- XBMC Remote/RightMenuViewController.m
- XBMC Remote/cs.lproj/Localizable.strings
- XBMC Remote/de.lproj/Localizable.strings
- XBMC Remote/en.lproj/Localizable.strings
- XBMC Remote/fr.lproj/Localizable.strings
- XBMC Remote/it.lproj/Localizable.strings
- XBMC Remote/pl.lproj/Localizable.strings
- XBMC Remote/zh-Hans.lproj/Localizable.strings
Correction of typos in keys and in localizable.strings existent files.
> Correction of typos

- XBMC Remote/HostViewController.m
- XBMC Remote/cs.lproj/Localizable.strings
- XBMC Remote/de.lproj/Localizable.strings
- XBMC Remote/en.lproj/Localizable.strings
- XBMC Remote/fr.lproj/Localizable.strings
- XBMC Remote/it.lproj/Localizable.strings
- XBMC Remote/pl.lproj/Localizable.strings
- XBMC Remote/zh-Hans.lproj/Localizable.strings
Corrected key in code and every language strings file.
> Another typo found "How-to actvate..."

- XBMC Remote/nl.lproj/Localizable.strings
made the tone friendlier and less stilted, corrected grammatical errors and typos, made translations more consistent.
> fixed dutch translations

- XBMC Remote/NowPlaying.m
- XBMC Remote/RemoteController.m
- XBMC Remote/ShowInfoViewController.m
- XBMC Remote/Utilities.h
- XBMC Remote/Utilities.m
Fixes Kodi issue https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/95
Details:
- With Kodi 15 an new syntax for Player.Seek was added
- With Kodi 19 the old syntax was removed
- This change checks for the Kodi server version and builds the support command parameter for seek
> Fix for broken seek with Kodi 19+

- XBMC Remote/AppInfoViewController.m
- XBMC Remote/HostManagementViewController.m
- fix iOS 14 crash:
> Thread 1: "Application tried to present UIModalTransitionStylePartialCurl to or from non-fullscreen view controller <CustomNavigationController: 0x104012600>."
- show full version number
> About screen improvements

- XBMC Remote/DetailViewController.m
> fix live TV crash

- XBMC Remote/DetailViewController.m
- XBMC Remote/NowPlaying.m
- XBMC Remote/ShowInfoViewController.m
- XBMC Remote/WebViewController.m
A set of fixes to the UI:
- When starting with CollectionView as lastmode the searchbar was still shown. Also hide it in thise case.
- CollectionView now jumps to the correct position after pushing "/" in the index bar.
- Load Details from list via Longpress-Menu (was only working for English or a subset of all possible actions)
- Fix longpress action from filtered list (during active search)
- Use full display height for WebViewController
And a small refactoring:
- Refactoring identical sequences into new method `deselectAtIndexPath`
> More fixes to UI (Longpress Actions, CollectionView, WebView)

- XBMC Remote/AppDelegate.m
- XBMC Remote/DetailViewController.m
- XBMC Remote/HostManagementViewController.m
- XBMC Remote/HostViewController.h
- XBMC Remote/HostViewController.m
- XBMC Remote/HostViewController.xib
- XBMC Remote/NowPlaying.m
- XBMC Remote/ShowInfoViewController.m
Details:
- Fix last item in playlist not fully shown ([forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3004226#pid3004226))
- Move up the tip in HostViewController to be fully readable (found during working on something else)
- Avoid empty space above CollectionView (aka grid view) ([forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3004226#pid3004226))
- Hide "tip" text in HostViewVC when on iPad in Landscape mode. Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/138
- Show toolbar for all lists in DetailVC ([forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3008407#pid3008407))
- Resume does not work ([forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3008588#pid3008588))
- Bring back posters for NowPlaying screen …
> Few fixes for issues reported from TestFlight builds

- XBMC Remote/DetailViewController.m
- XBMC Remote/MoreItemsViewController.m
- XBMC Remote/SettingsValuesViewController.m
- XBMC Remote/de.lproj/Localizable.strings
- XBMC Remote/en.lproj/Localizable.strings
- XBMC Remote/iPad/MenuViewController.m
Several fixes for issues reported from tester or found by myself:
- Fix Dark Mode for few items (TV pie chart, SettingsValuesVC item and MoreItemsVC item)
- Hide button5 (...) when unsupported. Avoids crash on iPad and unwanted highlighting when pressing empty area.
- Instead of searchbar provide an info label on top of the collectionView ([forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3009849#pid3009849))
> Few more fixes for issues found during tests

- XBMC Remote/DetailViewController.h
- XBMC Remote/DetailViewController.m
- XBMC Remote/de.lproj/Localizable.strings
Fixes an issue report in the forum ([post](https://forum.kodi.tv/showthread.php?tid=360354&pid=3012184#pid3012184)) and some other issues.
Summary:
- Do not show JSON-RPC error if no PVR Add-on is installed
- Avoid jumping sort/grid button when selecting a gerne in from the music library
- Fix https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/162
> Some more fixes

- XBMC Remote/AppDelegate.m
- XBMC Remote/DetailViewController.m
Next fixes from user´s feedback.
Details:
- Fix https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/165 (used wrong sort method for `AudioLibrary.GetArtists`)
- Fix insets for DetailViews again (regression of latest ToolBar changes)
> More fixes for 1.6 issue reports

- XBMC Remote/DetailViewController.m
Details:
- Fixes filtering-related crashes from https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/161 (crash after longpress on search result for empty search string)
> Some more fixes of 1.6 issues

- XBMC Remote/DetailViewController.h
- XBMC Remote/DetailViewController.m
- XBMC Remote/HostManagementViewController.m
- XBMC Remote/HostViewController.m
- XBMC Remote/MasterViewController.h
- XBMC Remote/NowPlaying.h
- XBMC Remote/NowPlaying.m
- XBMC Remote/RemoteController.h
- XBMC Remote/RemoteController.m
- XBMC Remote/RightMenuViewController.h
- XBMC Remote/RightMenuViewController.m
- XBMC Remote/SettingsValuesViewController.h
- XBMC Remote/SettingsValuesViewController.m
- XBMC Remote/ShowInfoViewController.h
- XBMC Remote/ShowInfoViewController.m
- XBMC Remote/Utilities.h
- XBMC Remote/Utilities.m
- XBMC Remote/ViewControllerIPad.h
- XBMC Remote/ViewControllerIPad.m
- XBMC Remote/WebViewController.h
- XBMC Remote/WebViewController.m
Replace deprecated `UIAlertView` with `UIAlertController`
FIxes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/198.
> Replace deprecated UIAlertView with UIAlertController

- XBMC Remote/DetailViewController.h
- XBMC Remote/DetailViewController.m
- XBMC Remote/HostManagementViewController.m
- XBMC Remote/NowPlaying.m
- XBMC Remote/RightMenuViewController.m
Close many issues reported in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/193.
- Avoid out-of-bounds access at several places reported from crash logs
- Enhance thread safety for EPG which was suspect to cause several crashes in this area
- Avoid crashes in some other places
> Stability fixes

- XBMC Remote/DetailViewController.m
- XBMC Remote/ECSlidingViewController/ECSlidingViewController.m
- XBMC Remote/ShowInfoViewController.m
- XBMC Remote/ViewControllerIPad.m
- XBMC Remote/iPad/MenuViewController.m
- XBMC Remote/iPad/StackScrollViewController.m
- Replaces deprecated didRotateFromInterfaceOrientation and willAnimateRotationToInterfaceOrientation
> Migrate to viewWillTransitionToSize

- pull_request_template.md
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
> add PR template

- fastlane/metadata/en-US/release_notes.txt
Draft for 1.6.2 release notes
[no app]
> Draft for 1.6.2 release notes

- XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
With XCode 12.5 new compile warning show up. This PR fixes them.
Maintenance: Fix compiler warnings introduced with XCode 12.5
> Fix new XCode 12.5 cast warnings

- XBMC Remote/DetailViewController.m
- XBMC Remote/de.lproj/Localizable.strings
- XBMC Remote/en.lproj/Localizable.strings
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/297.
Fix: Add few missing localized strings and added German translation
> Add few missing localized strings

- fastlane/metadata/en-US/release_notes.txt
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/300.
[not app] Release Notes 1.7.1
> Releases Notes for 1.7.1

- XBMC Remote/AppDelegate.m
For movie collection until now no "art" was requested. This PR enables showing posters.
Screenshot:
https://abload.de/img/simulatorscreenshot-if0kuw.png
Feature: Add posters for move collections
> Feature: Add posters for movie collections

- XBMC Remote/Utilities.m
Fix  a regression when refactoring doubled code in https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/286.
Bugfix: Use correct nil check
> Fix check for nil when formatting strings

- XBMC Remote/HostManagementViewController.m
- XBMC Remote/NowPlaying.m
- XBMC Remote/Utilities.m
- XBMC Remote/ViewControllerIPad.m
Fixes crashes reported in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/323.
Bugfix: Avoid potential crashes
> Avoid potential crashes

- XBMC Remote/DetailViewController.h
- XBMC Remote/DetailViewController.m
- XBMC Remote/HostViewController.m
- XBMC Remote/MoreItemsViewController.m
- XBMC Remote/NowPlaying.m
- XBMC Remote/ShowInfoViewController.m
- XBMC Remote/Utilities.h
- XBMC Remote/Utilities.m
- XBMC Remote/VolumeSliderView.m
Make all Utilities functions global
Maintenance: Make all Utilities functions global
> Make all Utilities functions global

- XBMC Remote/DetailViewController.m
- XBMC Remote/NowPlaying.m
- XBMC Remote/SDWebImage/UIImageView+WebCache.h
- XBMC Remote/SDWebImage/UIImageView+WebCache.m
- XBMC Remote/Settings.bundle/Root.plist
- XBMC Remote/Settings.bundle/de.lproj/Root.strings
- XBMC Remote/Settings.bundle/en.lproj/Root.strings
- XBMC Remote/ShowInfoViewController.m
- XBMC Remote/Utilities.h
- XBMC Remote/Utilities.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/182.
This PR implements a new feature which allows the user to enable/disable rounded corners for thumbnails. The method to round the edges is using `bezierPathWithRoundedRect` which results in a smooth rounded edge, similar to iOS' "squircle". When enabled this gives the UI a fresher and modern look -- in my opinion. Per default the rounded corners are enabled.
Screenshots:
https://abload.de/img/simulatorscreenshot-i6rkkb.png
https://abload.de/img/simulatorscreenshot-i59jgm.png
https://abload.de/img/simulatorscreenshot-i60jba.png
https://abload.de/img/simulatorscreenshot-iukjk8.png
https://abload.de/img/simulatorscreenshot-i54j4n.png
https://abload.de/img/simulatorscreenshot-inkjuh.png …
> Feature: rounded corners for thumbnails/images

- XBMC Remote/Utilities.m
This PR reduces the radius of the recently introduced rounded corners based on user feedback.
Former corner radius (10%)
https://abload.de/img/simulatorscreenshot-irjjb8.png (Music cover)
https://abload.de/img/simulatorscreenshot-i1jje0.png (4:3 TV)
New corner radius (3%)
https://abload.de/img/simulatorscreenshot-ilxjdy.png (Music cover)
https://abload.de/img/simulatorscreenshot-iebkfo.png (4:3 TV)
Optimization: Reducing corner radius for better look
> Reducing corner radius for better look

- XBMC Remote/AppDelegate.m
- XBMC Remote/DetailViewController.m
- XBMC Remote/Utilities.m
1. Improve displaying music videos:
a) Show artist information
b) Add support to sort by artist and genre
c) Sort by "Title" instead of "Name"
Screenshot: https://abload.de/img/bildschirmfoto2021-09r2k6q.png
2. While working on this I also improved displaying runtime. With this PR runtime string are kept empty (`""`), if the `runtime == 0`.
Screenshot: https://abload.de/img/bildschirmfoto2021-091kk4u.png
3. Another improvement done while working on the music videos sort-by enhancement is more robustness in the sort-algorithm which now processes `NSArray` as well.
Feature: Improve displaying music videos
Improvement: Improve sorting robustness
Improvement: Improve displaying runtime
> Feature: Improve music videos

- README.md
- fastlane/metadata/en-US/description.txt
- fastlane/metadata/en-US/release_notes.txt
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/357.
[not app]
> Release Notes for 1.8

- fastlane/metadata/en-US/release_notes.txt
Updating Release Notes for Remote App version 1.8.1
[not app]
> Release Notes 1.8.1

- XBMC Remote/ShowInfoViewController.h
- XBMC Remote/ShowInfoViewController.m
- XBMC Remote/ShowInfoViewController.xib
- XBMC Remote/Utilities.h
- XBMC Remote/Utilities.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/435.
This does a massive rework of `ShowInfoViewController`.
Screenshots:
https://abload.de/img/bildschirmfoto2021-1024jal.png
https://abload.de/img/bildschirmfoto2021-10eakcy.png
https://abload.de/img/bildschirmfoto2021-10kcjq1.png
https://abload.de/img/bildschirmfoto2021-10jkkxj.png
https://abload.de/img/bildschirmfoto2021-1088knn.png
https://abload.de/img/bildschirmfoto2021-10j5kmi.png
Improvement: Unified layout for detail views
Feature. Show description and summary for recording and broadcast details
Feature: Dedicated layout for music videos
Bugfix: Do not use jewel case for TV/Radio broadcast details
Bugfix. Show complete summary/plot/description for all item types
> Maintenance: Rework showinfo

- XBMC Remote/DetailViewController.m
Fixes and issue reported in a [forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3069432#pid3069432).
<a href="https://abload.de/image.php?img=bildschirmfoto2021-11nxjbu.png"><img src="https://abload.de/img/bildschirmfoto2021-11nxjbu.png" /></a>
Bugfix: Do not draw unwanted borders around default thumbs
> Bugfix: Do not draw unwanted borders around default thumbs

- XBMC Remote/en.lproj/Localizable.strings
Small fix reported in the forum.
Bugfix: Correct minor issue in English string
> Bugfix: Correct minor issue in English string

- XBMC Remote/DetailViewController.h
- XBMC Remote/DetailViewController.m
- XBMC Remote/cs.lproj/Localizable.strings
- XBMC Remote/de.lproj/Localizable.strings
- XBMC Remote/en.lproj/Localizable.strings
- XBMC Remote/es.lproj/Localizable.strings
- XBMC Remote/fr.lproj/Localizable.strings
- XBMC Remote/it.lproj/Localizable.strings
- XBMC Remote/nl.lproj/Localizable.strings
- XBMC Remote/pl.lproj/Localizable.strings
- XBMC Remote/pt-PT.lproj/Localizable.strings
- XBMC Remote/sv.lproj/Localizable.strings
- XBMC Remote/tr.lproj/Localizable.strings
- XBMC Remote/zh-Hans.lproj/Localizable.strings
This PR removes some unneeded variables and localized strings around `DetailViewController`.
Maintenance: Remove unneeded variables and localized strings
> Maintenance: Remove unneeded variables and localized strings

- Kodi Remote.xcodeproj/project.pbxproj
- XBMC Remote/DetailViewController.m
- XBMC Remote/Utilities.h
- XBMC Remote/Utilities.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/370.
This PR implements automated rating request for the AppStore. 
1st attempt: It will show the rating popup each 10th start/wakeup.
Feature: Implement automated rating request
> Feature: Implement automated rating request

- fastlane/metadata/en-US/release_notes.txt
Updating Release Notes for App version 1.9
[not app] Updating Release Notes for App version 1.9
> Release Notes 1.9

- XBMC Remote/NowPlaying.h
- XBMC Remote/NowPlaying.m
Choose correct default thumb for the Music and Video playlist.
Bugfix: Show correct default thumb in movie/music playlists
> Improvements around playlist

- XBMC Remote/DetailViewController.m
- XBMC Remote/Utilities.h
- XBMC Remote/Utilities.m
For the Kodi settings table there is a unique animation on iPhone. The animation slides in the table from bottom to top. For this we need to have a helper method which animates x and y origins.
Bugfix: Fix invisible Kodi server settings
> Bugfix: Fix invisible Kodi server settings

- Kodi Remote.xcodeproj/project.pbxproj
This PR adds support for two languages: Finnish (fi-fi) and Korean (ko-kr) languages.
Feature: Add support for Finnish (fi-fi) and Korean (ko-kr) languages
> Feature: Add support for Finnish (fi-fi) and Korean (ko-kr) languages

- fastlane/metadata/en-US/release_notes.txt
Updating Release Notes for App version 1.10
[not app] Updating Release Notes for App version 1.10
> Release Notes 1.10

- fastlane/metadata/en-US/release_notes.txt
Updating Release Notes for App version 1.10.1
[not app] Updating Release Notes for App version 1.10.1
> Release Notes 1.10.1

- XBMC Remote/HostManagementViewController.m
- XBMC Remote/NowPlaying.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/646.
Improvement: Gray out "Edit" if there are no items
> Improvement: Gray out "Edit" if there are no items

- XBMC Remote/DetailViewController.m
- XBMC Remote/NowPlaying.m
- XBMC Remote/ShowInfoViewController.m
- XBMC Remote/Utilities.h
- XBMC Remote/Utilities.m
This PR moves two already existing helper functions to `Utilities` and uses them in some more places to reduce code duplication.
Maintenance: Avoid duplicate code
> Maintenance: Avoid duplicate code

- XBMC Remote/HostViewController.xib
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/721.
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-10x1csx.png"><img src="https://abload.de/img/bildschirmfoto2022-10x1csx.png" /></a>
Improvement: Better readability of help and error message in HostVC
> Improvement: Better readability of help and error message in HostVC

- fastlane/metadata/en-US/release_notes.txt
Release Notes 1.11
Release Notes 1.11
> Release Notes 1.11

- XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m
- XBMC Remote/DetailViewController.m
This PR keeps the index background transparent also when touched.
Improvement: Transparent index background
> Improvement: Transparent index background

- XBMC Remote/ShowInfoViewController.m
Closes a topic raised in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3121054#pid3121054).
Use white scrollbar in TVShow details for improved readability.
Screenshot: https://abload.de/img/simulatorscreenshot-ivui64.png
rovement: Use white scrollbar in TVShow details
> Improvement: Use white scrollbar in TVShow details

- fastlane/metadata/en-US/release_notes.txt
> Release Notes 1.12

- fastlane/metadata/en-US/release_notes.txt
> Release Notes 1.12.1

- XBMC Remote/iPad/StackScrollViewController.h
- XBMC Remote/iPad/StackScrollViewController.m
In iPad's `StackScrollViewController` there are a lot of frame calculations which have code duplicates. This PR is stepwise refactoring the code for better maintainability, introducing helper methods and variables got reduce the duplications.
Maintenance: Refactor iPad StackScrollVieewController
> Maintenance: Refactor iPad StackScrollViewController

- XBMC Remote/ShowInfoViewController.m
Fixes an issue reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3151563#pid3151563).
The problem is with different padding behaviour over iOS version using `UIToolbar`. On stackoverflow a possible solution was presented which basically can remove some default padding which is applied for some iOS versions: [UIToolbar left and right spacing when rotating device in IOS11](https://stackoverflow.com/questions/48543542/uitoolbar-left-and-right-spacing-when-rotating-device-in-ios11).
This PR implements a 2-step approach:
1. Remove the left/right padding via negative fixed spaces.
2. Add padding via `UIView` of desired width
This implementation was verified to work on iOS 14.5 and iOS 16.2 simulators.
Bugfix: Correct padding in ShowInfoVCs navigation bar on iPad
> Bugfix: Correct padding in ShowInfoVCs navigation bar on iPad

- XBMC Remote/Settings.bundle/en.lproj/Root.strings
Add localization for recently introduced setting `"Episode identifier"`.
Improvement: Add localization for setting "Episode identifier"
> Improvement: Add localization for setting "Episode identifier"

- XBMC Remote/AppDelegate.m
- XBMC Remote/DetailViewController.m
- XBMC Remote/NowPlaying.m
- XBMC Remote/RemoteController.m
- XBMC Remote/RightMenuViewController.m
- XBMC Remote/SettingsValuesViewController.m
- XBMC Remote/ShowInfoViewController.m
- XBMC Remote/Utilities.h
- XBMC Remote/Utilities.m
- XBMC Remote/VolumeSliderView.m
- XBMC Remote/XBMCVirtualKeyboard.m
- XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
- XBMC Remote/tcpJSONRPC.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/877.
Check for `NSDictionary` type before processing further to increase robustness against mal-formatted JSON API responses as recently seen in Kodi 21.0-ALPHA nightly builds.
Improvement: Increase robustness against mal-formatted JSON API responses
> Improvement: Increase robustness against mal-formatted JSON API responses

- fastlane/metadata/en-US/release_notes.txt
Release Notes 13.0
[not app]Release Notes 13.0
> Release Notes 13.0

- XBMC Remote/SDWebImage/SDWebImageDownloader.m
Fixes and issue reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3171200#pid3171200).
Use `cacheKeyForURL` instead of the URL to identify different image download operations. Now `key` holds both the image URL and the target resolution. Parallel image downloads of different keys will be handled separately, for the same key this is done only once (as intended by SDWebImage). This fixes an issue where the same images were downloaded in parallel, but should have a post processing to scale to different resolutions. This could end up in loading/caching low resolution images instead of the desired high resolution.
Bugfix: Fix potentially low resolution NowPlaying images
> Bugfix: Fix potentially low resolution NowPlaying images

- fastlane/metadata/en-US/release_notes.txt
Release Notes 1.13.1
[not app] Release Notes 1.13.1
> Release Notes 1.13.1

- XBMC Remote/AppDelegate.m
- XBMC Remote/DetailViewController.h
- XBMC Remote/DetailViewController.m
- XBMC Remote/HostViewController.m
- XBMC Remote/MoreItemsViewController.m
- XBMC Remote/NowPlaying.m
- XBMC Remote/RemoteController.m
- XBMC Remote/RightMenuViewController.m
- XBMC Remote/SettingsValuesViewController.m
- XBMC Remote/ShowInfoViewController.m
- XBMC Remote/Utilities.h
- XBMC Remote/Utilities.m
- XBMC Remote/jsonDataCell.xib
- XBMC Remote/tcpJSONRPC.m
This PR collects multiple rework and refactoring, mainly focused to:
- Avoid code duplication
- Reduce magic numbers
- Remove obsolete definitions
- Remove not needed attempt to load from URL (in case any way falling back to pre-defined default thumbs)
- Correction of progress pie layout calculation (not visible as magic number resolved this before)
- Fix layout of list view cells
Maintenance: Refactoring in multiple areas
Bugfix: Correct size for labels in list view (avoids overlapping)
> Maintenance: Refactoring in multiple areas

- Kodi Remote.xcodeproj/project.pbxproj
Now it's no longer necessary to add system frameworks to the project unless linking weakly
> link frameworks automatically

- XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m
- XBMC Remote/DetailViewController.m
This PR takes care of an issue with the index discussed in the forum, see [this post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3181429#pid3181429).
Improvement: Reduce index width and center the index text properly
> Improvement: Reduce index width and center the index text properly

- XBMC Remote/DetailViewController.h
- XBMC Remote/DetailViewController.m
- XBMC Remote/DetailViewController.xib
- XBMC Remote/HostManagementViewController.h
- XBMC Remote/HostManagementViewController.m
- XBMC Remote/HostManagementViewController.xib
This PR does a set of maintenance changes:
- Use ivar `selectedIndexPath` instead of misnamed global variable `selected`
- Remove unused method `handleLongPressSortButton`
- Reformat multi-condition check
- Refactor gathering of action sheet's source location inside `handleLongPress`
Maintenance: Refactor parts of DetailViewController
> Maintenance: Refactor parts of DetailViewController

- fastlane/metadata/en-US/release_notes.txt
Providing the Release Notes for 1.14
[not app] Release Notes 1.14
> Release Notes 1.14

- XBMC Remote/ShowInfoViewController.m
Fixes a regression report in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3191003#pid3191003).
This fixes a regression caused by refactoring when adding the tagline feature (https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/997).
Bugfix: Increase the font size of ShowInfoVC labels
> Bugfix: Increase the font size of ShowInfoVC labels

- fastlane/metadata/en-US/release_notes.txt
Release Notes 1.15
[not app]Release Notes 1.15
> Release Notes 1.15

- XBMC Remote/DetailViewController.h
- XBMC Remote/DetailViewController.m
- XBMC Remote/HostViewController.m
- XBMC Remote/MasterViewController.m
- XBMC Remote/MessagesView.m
- XBMC Remote/RightMenuViewController.m
- XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.m
- XBMC Remote/Utilities.m
- XBMC Remote/ViewControllerIPad.m
This PR does some minor coding styles ans minor refactoring I came across when walking through the code:
- Unify pointer declaration
- Avoid double "_" in xib tag definition
- Fix typos in comments and variable name
- Remove unneeded variable and ivar
- Use `NSUInteger` when dealing with `count`
Maintenance: Small coding style changes and internal rework
> Maintenance: Small coding style changes and internal rework

- Kodi Remote.xcodeproj/project.pbxproj
The translation for Brazilian Portuguese reached >70% and is enabled now.
Feature: Support language pt-br
> Feature: Support language pt-br

- XBMC Remote/NowPlaying.m
- XBMC Remote/ShowInfoViewController.m
- XBMC Remote/ViewControllerIPad.m
- XBMC Remote/iPad/MenuViewController.m
- XBMC Remote/iPad/StackScrollViewController.h
- XBMC Remote/iPad/StackScrollViewController.m
iPad's StackScrollViewController was a hard to maintain class, majorly because of excessive condition structures in `handlePanFrom` which controls moving and positioning the views in the stack. This PR rewrites this method, adds detailed comments on the implementation, along with it rewrites the bounce implementation and removes obsolete code and variables.
Reduce the conditions and layout updates massively. Three major sections are left:
1. Dragging views _out of_ or _into_ the visible area
2. Dragging views _within_ the visible area
3. _Placing_ views at the target positions (snap into place)
In section 2 and3 there are additional conditions to handle dragging left/right or to handle one or two moved views.
The views have lesser amount of stable positions they "snap" into.
- The view …
> Rework iPad stack controller

- XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.h
- XBMC Remote/DetailViewController.m
- XBMC Remote/ECSlidingViewController/ECSlidingViewController.h
- XBMC Remote/NowPlaying.m
- XBMC Remote/RemoteController.h
- XBMC Remote/RemoteController.m
- XBMC Remote/SettingsValuesViewController.h
- XBMC Remote/SettingsValuesViewController.m
- XBMC Remote/ShowInfoViewController.m
- XBMC Remote/Utilities.h
- XBMC Remote/Utilities.m
- XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.h
- XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPCError.h
- XBMC Remote/mainMenu.h
This PR unifies declaration of enums, following:
- Use `typedef NS_ENUM`
- Start with capital letters
- Choose name reflecting the function
Maintenance: Coding style for enums
> Maintenance: Coding style for enums

- fastlane/metadata/en-US/release_notes.txt
Release Notes 1.16
[not app]Release Notes 1.16
> Release Notes 1.16

- XBMC Remote/Utilities.m
This PR simplifies the implementation of `colorizeImage:withColor:`.
Maintenance: Simplify colorizeImage:withColor:
> Maintenance: Simplify colorizeImage:withColor:

- XBMC Remote/AppDelegate.m
- XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m
- XBMC Remote/DetailViewController.h
- XBMC Remote/DetailViewController.m
- XBMC Remote/HostViewController.m
- XBMC Remote/KenBurns/JBKenBurnsView.m
- XBMC Remote/MasterViewController.m
- XBMC Remote/MoreItemsViewController.m
- XBMC Remote/NowPlaying.h
- XBMC Remote/NowPlaying.m
- XBMC Remote/RemoteController.m
- XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.m
- XBMC Remote/ShowInfoViewController.m
- XBMC Remote/Utilities.m
- XBMC Remote/ViewControllerIPad.m
- XBMC Remote/VolumeSliderView.m
- XBMC Remote/iPad/StackScrollViewController.m
- XBMC Remote/tcpJSONRPC.m
This PR applies some coding style changes and minor refactoring.
- Use `nil` instead of empty callback
- Remove double semicolon
- Use member instead of method
- Remove empty methods and related observers
- Remove inactive code
- Space instead of tab
- Remove `currentScreenBoundsDependOnOrientation`
Maintenance: Coding styles and minor refactoring
> Maintenance: Coding styles and minor refactoring

- fastlane/metadata/en-US/release_notes.txt
Release Notes 1.17
[not app]Release Notes 1.17
> Release Notes 1.17

- Kodi Remote.xcodeproj/project.pbxproj
With https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/1263 the translation for Indonesian surpassed the threshold to enable the language support in the App.
Feature: Add support for Indonesian (id-id)
> Feature: Add support for Indonesian (id-id)

- XBMC Remote/HostManagementViewController.h
- XBMC Remote/HostManagementViewController.m
- XBMC Remote/Utilities.h
- XBMC Remote/Utilities.m
This PR adds information on the Remote App's memory usage and image cache size.
Screenshots: https://ibb.co/GfmCGNRD
Improvement: Show Remote App memory usage and image cache size
> Improvement: Show Remote App memory usage and image cache size

- XBMC Remote/AppInfoViewController.m
- XBMC Remote/FloatingHeaderFlowLayout.m
- XBMC Remote/HostManagementViewController.m
- XBMC Remote/HostViewController.m
- XBMC Remote/RemoteController.m
Refactor `FloatingHeaderFlowLayout`, add comments and use enums for `edgesForExtendedLayout`.
Maintenance: Refactor FloatingHeaderFlowLayout and use enums for edgesForExtendedLayout
> Maintenance: Refactor FloatingHeaderFlowLayout and use enums for edgesForExtendedLayout

- fastlane/metadata/en-US/release_notes.txt
Release Notes 1.18
[not app]Release Notes 1.18
> Release Notes 1.18

- XBMC Remote/DetailViewController.m
- XBMC Remote/HostManagementViewController.m
- XBMC Remote/NowPlaying.m
- XBMC Remote/RightMenuViewController.m
Use `performBatchUpdates` instead of `beginUpdates`/`endUpdates` (which will be deprecated in future releases).
Maintenance: Migrate to performBatchUpdates
> Maintenance: Migrate to performBatchUpdates
