xbmc/Official-Kodi-Remote-iOS

XBMC Remote/AppDelegate.m, XBMC Remote/cs.lproj/Localizable.strings, XBMC Remote/de.lproj/Localizable.strings, XBMC Remote/en.lproj/Localizable.strings, XBMC Remote/fr.lproj/Localizable.strings, XBMC Remote/it.lproj/Localizable.strings, XBMC Remote/pl.lproj/Localizable.strings, XBMC Remote/zh-Hans.lproj/Localizable.strings
There were existing Addon and Add-on terms across keys and translated strings.
Uniformized to comply to Kodi glossary, every instance is now "Add-on".
=> Uniformization of term "Addon" -> "Add-on"

XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/ViewControllerIPad.m, XBMC Remote/iPad/StackScrollViewController.h, XBMC Remote/iPad/StackScrollViewController.m
The newer iPads without Home button need some special treatment for the DetailViewController´s button toolbar and the StackViewController views. With this change both types of iPads (with and without Home button) will show the bar and views properly, including rotation.
=> Fix bottom padding for iPads without Home button

XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
I've been running into timeout issues when trying to refresh the song view with a library of > 20k songs on a RasPi 2 and Intel-Atom-based computers. Nothing is wrong with the connection, just takes some time to transfer the data. This just ups the timeout.
=> Increase the timeout for API requests

XBMC Remote/XBMCVirtualKeyboard.m
Fixes issue https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/113.
Define blackColor for keyboard text field (which has a white background defined). This way the text field stays readable when entering Dark Mode.
=> Hotfix for Dark Mode

Kodi Remote.xcodeproj/project.pbxproj, README.md, fastlane/Fastfile
- Testflight script improvements
- bring back support for 32-bit devices (that run pre-iOS 11): noticed that previous builds had been built only for arm64
=> AppStore distribution fix

XBMC Remote/AppDelegate.h, XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.m, XBMC Remote/MasterViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/SettingsValuesViewController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/VolumeSliderView.m
This fixes issue https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/111.
Details already given in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/99#issuecomment-757415645:
> Still not checked for all screens and view modes. It is hard to see what exactly was calculated to get those hard coded numbers. In general the code on master tries to use different scaling factors for several items (e.g. thumbviews, the remote or the volume slider). There are three families of scaling factors which reflect the three different x-axis resolutions at the time when the last changes were done, the fourth one (e.g. iPhone 12) was not taken into account. As the factors are not 100% identical for each family (like 1.29, 1.294 and 1.31) I think there was some manual tweaking done in some places, …
=> Fix scaling for iPhones

XBMC Remote/DetailViewController.m
- In albumView ignore the playcount check for each track, only the playcount of the album is relevant
- Resolves albums not being shown when selecting them from the list of already played / non-played albums
=> Fix albumView not showing when entering via view of played/non-played albums

XBMC Remote/AppDelegate.h, XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/MasterViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
Fixes issue https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/122.
- Latest scaling changes for iPhone assume that full available screen width is used. This is only true for iPhones.
- For iPads the reduced and fixed width STACKSCROLL_WIDTH is used. In this case do not scale the thumb/banner.
- Implemented methods instead of #defines.
Interesting other aspect: The newer iPads are much wider than the older ones. Therefore it is possible to use broader frames for the views in the StackScrollViewController via
#define PAD_MENU_TABLE_WIDTH 300
#define STACKSCOLL_WIDTH (CGRectGetWidth(UIScreen.mainScreen.fixedCoordinateSpace.bounds)-PAD_MENU_TABLE_WIDTH)
This way the stackview is taking exactly the space on the rights side of the menu when in Portrait orientation. But this needs some …
=> Fix thumb/banner scaling for iPad

Kodi Remote.xcodeproj/project.pbxproj, XBMC Remote/AppInfoViewController.m, XBMC Remote/CustomNavigationController.m, XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.m, XBMC Remote/HostViewController.m, XBMC Remote/InitialSlidingViewController.m, XBMC Remote/MasterViewController.m, XBMC Remote/MoreItemsViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/PlayFileViewController.m, XBMC Remote/RemoteController.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/ViewControllerIPad.m, XBMC Remote/VolumeSliderView.m, XBMC Remote/WebViewController.m, XBMC Remote/XBMCVirtualKeyboard.m, XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.h, XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m, XBMC Remote/iPad/MenuViewController.m, XBMC Remote/iPad/StackScrollViewController.m, XBMC Remote/tcpJSONRPC.m
Based on an ask from @kambala-decapitator I looked into the changes from his local branch [xcode11](https://github.com/kambala-decapitator/Official-Kodi-Remote-iOS/tree/xcode11) and brought those changes into a series of commits which were not yet merged to master as part of the latest updates.
Changes:
- Enable warning for overwriting deprecated functions
- Replace `didReceiveAuthenticationChallenge` with `willSendRequestForAuthenticationChallenge`
- Remove deprecated `viewDidUnload` and ensure all cleanups are moved to `dealloc`
- Remove deprecated `shouldAutorotateToInterfaceOrientation`
- Rework declarations of `supportedInterfaceOrientations`
- Remove pre-iOS 8 screen size retrieval
=> More code cleanup

XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.m, XBMC Remote/MessagesView.h, XBMC Remote/MessagesView.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/SettingsValuesViewController.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/125.
Since 7a67e37 (set modal presentation style to fullscreen ...) messages are displayed at the wrong vertical position in the `SettingsValuesViewController`, e.g. when adding buttons manually. This PR uses `safeAreaInsets` to gather the correct offset for iPhones, and keeps using the former hardcoded value otherwise.
=> Fix message position for iPhones in settings menu

XBMC Remote/DetailViewController.m
Fixes issue https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/96 and https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/88
Details:
- Since Kodi19 there is no fallback to use poster or banner in case there is no thumbnail.
- Use poster if available
=> Fix posters not shown with Kodi 19+

XBMC Remote/DetailViewController.m
Fix https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/132.
Details:
Correct the order of image assignments to have the preferred assignment of banners done last, if configured by user.
Important:
Because of the way how the "Prefer banners for TV Show" feature is implemented, user needs to synchronize with Kodi again after the fix is rolled out.
=> Prefer TV Show banner when configured

XBMC Remote/DetailViewController.m, XBMC Remote/MasterViewController.m, XBMC Remote/ViewControllerIPad.m
Fixes an issue discussed in this [forum thread](https://forum.kodi.tv/showthread.php?tid=312272). Alternative solution to https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/92.
Details:
- Move thumbSize adaption from `handleXBMCServerHasChanged` to `DetailViewController`´s `viewDidLoad`
- Will ensure the thumbSize for TV Shows is correctly set when entering the TV Show menu, independent of when the connection status changes
- Tested with Kodi19 server
=> Fix thumb size for TV Shows when posters are preferred

XBMC Remote/HostManagementViewController.m
Fix https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/136
- Checking for the height of navigationController in HostManagementVC sometimes gives 0 even though the bar is shown. To work around this we go back to former solution of hard coding this offset.
- Hard coding is not really preferred, but in this case I want to avoid the hassles to implement this properly (was already dropped for another message positioning case in another PR which was merged).
=> Fix sometimes wrong position of message in HostManagementVC

XBMC Remote/AppDelegate.h, XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m, XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.m, XBMC Remote/HostViewController.m, XBMC Remote/MoreItemsViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/PosterCell.m, XBMC Remote/ProgressPieView.m, XBMC Remote/RecentlyAddedCell.m, XBMC Remote/RemoteController.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/SettingsValuesViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/VolumeSliderView.m, XBMC Remote/XBMCVirtualKeyboard.m
This PR basically implements Dark Mode support and will fix some observations from test reports. Nevertheless this PR needs some testing (TestFlight?) to find menus and textfields not taken into account yet.
- Add new methods to allow setting system colors which support Dark Mode
- Use standard colors in case of iOS w/o Dark Mode support
- Use new system colors for main list/cell background d text colors
In addition this PR changes the used colors towards system red/green/blue/teal instead of homebrewn color definitions:
- Use system colors for red/green/blue/teal
- Use systemRed instead of Red
Some screenshots:
https://abload.de/img/simulatorscreenshot-iptk5v.png
https://abload.de/img/simulatorscreenshot-ijejte.png
https://abload.de/img/simulatorscreenshot-il7k9e.png …
=> Implement Dark Mode support

XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m, XBMC Remote/DetailViewController.m
In the current Remote App the look for the index bar in grid view differs from list view. The list view´s index bar is the default iOS one. The grid view´s index bar can be changed. This PR does two main changes:
1.  Align the vertical size of the index bars for list and grid view.
2. Change index text color to systemBlueColor (refers to https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/145) and remove shadow from grid view´s index text.
This was tested on several iPhone and iPad simulators with different amount of index items.
Current look:
https://abload.de/img/simulatorscreenshot-i3kkpz.png (list view)
https://abload.de/img/simulatorscreenshot-ikrjqa.png (grid view)
Reworked:
https://abload.de/img/simulatorscreenshot-ig1k1l.png (list view) …
=> Different look for index bar in grid and list view

XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.m
Fix https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/143.
This PR changes the way how colors for text and UI elements are derived from the average cover color (e.g. from music albums). It now uses hue/saturation/brightness instead of adding offsets to the RGB components. This way hue stays intact, and only desaturation is applied to wash out the colors and the brightness is kept in a certain range to have a more stable representation over different covers.
=> Rework color grading

XBMC Remote/ActorCell.m, XBMC Remote/AppDelegate.h, XBMC Remote/AppDelegate.m, XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m, XBMC Remote/ClearCacheView.m, XBMC Remote/DetailViewController.m, XBMC Remote/InitialSlidingViewController.m, XBMC Remote/MasterViewController.m, XBMC Remote/MessagesView.m, XBMC Remote/NowPlaying.m, XBMC Remote/PosterCell.m, XBMC Remote/PosterHeaderView.m, XBMC Remote/RecentlyAddedCell.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/SettingsValuesViewController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/ViewControllerIPad.m, XBMC Remote/VolumeSliderView.m, XBMC Remote/iPad/MenuViewController.m
This PR reworks the color definitions for all gray UI parts. Instead of calls like  `[UIColor colorWithRed:0.141176f green:0.141176f blue:0.141176f alpha:1.0f]` this is now reduced to a method call `[Utilities getGrayColor:36 alpha:1.0]`.
=> Rework gray color definitions

XBMC Remote/DetailViewController.m
Minor fix to iPad "corner info" (text field and fullscreen toggle button at the right side of the toolbar).
- Allow 5 pixel space right of the iPad corner info
- Fixes corner info text being cut at the end
=> Make iPad corner info fully readable

XBMC Remote/WebViewController.m
Minor fix to `WebViewController`.
- Use correct toolbar height for iPhones without Home Button
- Gives better consistency when switching from other menus to `WebViewController`
=> Fix WebView toolbar for iPhones w/o Home Button

XBMC Remote/DetailViewController.m
Few more fixes for issues reported from TestFlight.
- Last album in list was partly hidden behind toolbar ([forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3010785#pid3010785))
- Invisble toolbar buttons were actionable, hide them properly (found while fixing above, could lead to unwanted behaviour)
=> More fixes for issues reported from TestFlight

XBMC Remote/ShowInfoViewController.m
Minor fix for issue reported in [forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3011629#pid3011629).
- Keep using SystemFont for channel and recording name in ShowInfoVC for recordings
=> Use SystemFont for recording details

XBMC Remote/AppDelegate.h, XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.h, XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/ViewControllerIPad.m
In `NowPlaying` screen a variety of hardcoded magic numbers was used during layout of the views. Most of them are now either removed (as not needed at all), replaced with calculations based on other view´s dimensions or -- where needed -- replaced by defines. While on it I also found some unused code and removed it, as well as refactored some code where appropriate.
As an optimization/feature the new code uses bigger fonts for newer iPads with higher resolution. Also, the NowPlaying´s view height is now derived from the maximum possible height in Landscape mode. This avoids some space/visibility issues in Portrait mode on newer iPads which were before worked around via hardcoded offsets.
Summary:
- Removing magic numbers
- Refactored code
- Removed unneeded variables, code and defines
- …
=> Rework of NowPlaying screen

XBMC Remote/HostManagementViewController.m
Partial fix of https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/161 (crash when calling pushViewController)
=> Next fixes for 1.6 issues

XBMC Remote/NowPlaying.m
Details:
- Fixes one of crashes from https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/161: out-of-bounds crash in `cellForRowAtIndexPath`
=> More fixes for 1.6 issues (crashes)

XBMC Remote/NowPlaying.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/171.
- Fixes a regression of App version 1.6 and latest NowPlaying rework
- Fixes thumbview dimension not correct when image not in cache
- Calculates the thumbview frame size instead of hardcoding it
- Same method used for NowPlaying and ShowInfoVC
- Same method used for iPhone and iPad
=> Rework NowPlaying and ShowInfoVC with enabled jewel case

XBMC Remote/DetailViewController.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/170
Details:
- iPad behaves different than iPhone
- For iPad the action sheet after longpress on a filtered list must be shown from `[self.view superview]`
Need some guidance if the right way to fix this...
=> Fix longpress on filtered list for iPad

XBMC Remote/NowPlaying.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/171 (newly reported overlay problem).
The view for detailed infos was not set as subview of the NowPlaying screen and was in consequence displaced on iPads. I corrected this and decided to use the same frame dimension as for the "jewel" frame. This results in a frame which always uses the full width of the NowPlaying screen and might be larger than the underlying thumb. I feel this way we make best use of the available space, especially when there is a lot of details available to display. Screenshots:
https://abload.de/img/simulatorscreenshot-i5hkvk.png
https://abload.de/img/simulatorscreenshot-ik4k6h.png
https://abload.de/img/simulatorscreenshot-icojls.png
https://abload.de/img/simulatorscreenshot-il2kea.png …
=> Fix overlay position for DetailView in NowPlaying screen

XBMC Remote/DetailViewController.m
- TV Shows do not have a button5 defined. So we did always hide the toolbar when leaving TV Shows first tab.
- Instead, check each button on the toolbar before hiding the toolbar itself.
@gfoldv, thanks for reporting.
=> Fix hidden toolbar in TV Shows menu

XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m, XBMC Remote/DetailViewController.m
- In grid view (CollectionView) the width was too small to display the possible index text.
- The required width is same for iPad and iPhone.
- Take care the index is fully visible in the frame.
=> Fix index width & position for grid view

XBMC Remote/AppDelegate.h, XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/de.lproj/Localizable.strings, XBMC Remote/en.lproj/Localizable.strings, XBMC Remote/tcpJSONRPC.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/134.
After a quite some journey through the code and many hints from the community, here is the "sort for PVR recording/timer" feature. In fact, I was initially of the opinion that the Remote App does not sort itself and only displays the items in the order coming from the JSON response. But this is not true. The App requests the items only once with a default sort method/order and in addition collects metadata which can be used for sorting. But: the selectable sorting methods are mingled together with the sort methods in the App -- the logic was a bit obscured.
For the PVR sorting the App now sends a default sort request (sort by label, ascending). This is not sent in case the API does not support this yet. Independent (!) of …
=> Feature: Enable sorting for PVR recordings/timers

XBMC Remote/HostManagementViewController.m
Have consistent UI icons for both iPad and iPhone. With this change on iPhones (as already for iPads) you reach the "Power Action Menu" via the same icon (upper right side on the screen shot).
<a href="https://abload.de/image.php?img=simulatorscreenshot-ixbkay.png"><img src="https://abload.de/img/simulatorscreenshot-ixbkay.png" /></a>
=> Use same icon for power menu on iPad and iPhone

XBMC Remote/ShowInfoViewController.m
Minor UI fix. The position of the season´s coverView (depends on the jewelView) was a bit too far left when "Show jewel case" is disabled.
<a href="https://abload.de/image.php?img=bildschirmfoto2021-02i0jia.png"><img src="https://abload.de/img/bildschirmfoto2021-02i0jia.png" /></a>
=> Fix position of jewelview when jewel case is disabled

XBMC Remote/DetailViewController.m
- Show first 3 characters of day of the week, instead of first character only.
- Allows to differentiate between Saturday (Sa.) and Sunday (Su.)
Before (red) and after (green) this change:
<a href="https://abload.de/image.php?img=bildschirmfoto2021-021ek7r.png"><img src="https://abload.de/img/bildschirmfoto2021-021ek7r.png" /></a>
=> Optimized index for channelGuideView

XBMC Remote/DetailViewController.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/184.
- Use localizedStandardCompare selector to sort
- Results in correct order 1, 2, 9, 12, 21 in instead of 1, 12, 2, 21, 9
Before:
https://abload.de/img/simulatorscreenshot-ihakbs.png
After:
https://abload.de/img/simulatorscreenshot-i7mj3x.png
https://abload.de/img/simulatorscreenshot-i4gjgr.png
=> Fix wrong index sorting for playcount

XBMC Remote/NowPlaying.m
Fixes issue reported in [forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3017071#pid3017071).
Details:
- Instead of adding the overlay view to NowPlaying view as subview we only convert the desired center position
=> Fix shuffle/repeat in overlays not working for iPads

XBMC Remote/DetailViewController.m
Possibly fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/161.
Changes:
1. When requesting the channel list for an empty channel group (`channelgroupid` == -1) Kodi server reacts with an error. The updated implementation now does not request the channel list in this case and simply shows "No results found".
2. The last non-fixed crash reported in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/161 is reproducible when entering the situation described above (`channelgroupid` == -1). I added a potential fix for this in the 2nd commit.
=> More robust handling of empty channel groups in Live TV

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/de.lproj/Localizable.strings, XBMC Remote/en.lproj/Localizable.strings
Feature request was reported as bug in [forum thread](https://forum.kodi.tv/showthread.php?tid=360386).
Most of the code was prepared but still commented. With this PR a new UI entry "Movie Playlists" is added to the "More ..." screen of the Video main menu. The functionality via action sheets is the same as for Music Playlists (for now). Also "art" is used to show the expected thumbs with Kodi 19 and later.
=> Feature: Enable Video Playlists support

XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m, XBMC Remote/Utilities.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/153 and closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/176. This change implements following features:
1. Derive color of the top bar in season view from the season cover. The text color will be selected for best contrast. The functionality is similar to the solution for album view.
2. Change the background color for TV station logos for better contrast and readability
3. Show icon art for recordings when available.
While on it I refactored several statements inside the code.
=> Features: derive color from seasons cover and better readability for TV station logos

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/192.
Details:
A) Fixes sorting by playcount for albums in several use cases:
1. Sorting (by playcount) itself now works ins this case, and it is possible to change the sort order.
2. The sections now display the correct tet ("listened" instead of "watched").
B) Allow changing sort order (for sorting by playcount) for Top100 Albums and Top100 Songs. 
Question: Was this intended behaviour? When sorting for playcount the Top100 lists do not show sections or the playcount. Therefor it is not easy to recognize how the display list is sorted, even though the sort-indicator indicates this. Do we want to change the behaviour for consistency (like done with this PR), or shall this keep unchanged?
=> Fix sort-by-playcount for few music album cases

XBMC Remote/AppDelegate.m
With this PR the fullscreen option for music albums and artists is enabled. 
Screenshots:
https://abload.de/img/simulatorscreenshot-i60jn1.png
https://abload.de/img/simulatorscreenshot-ii3jxg.png
https://abload.de/img/simulatorscreenshot-iqajlt.png
https://abload.de/img/simulatorscreenshot-i8wjms.png
=> Enable fullscreen for music albums and artists

XBMC Remote/DetailViewController.m, XBMC Remote/Utilities.m
Implement a better way of calculating the average color and brightness for images with alpha channels. This should fix reports that some dark TV station logos are still drawn on top of dark background ([forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3022986#pid3022986)).
Details:
- Use different methods for images with and without alpha channel
- For images with alpha channel apply higher weighting for non-transparent colors
Now tested with two logo sets provided by a Kodi user.
Set A (monochrome, mainly dark logos):
https://abload.de/img/simulatorscreenshot-i1xjr2.png (before)
https://abload.de/img/simulatorscreenshot-iznjd6.png (with)
Set B (monochrome and color, mainly bright logos):
https://abload.de/img/simulatorscreenshot-idmko8.png (before) …
=> Optimize background color for TV station logos

XBMC Remote/DetailViewController.m
Fixes a regression caused by https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/194.
Issue:
- When entering the album details view the titles are sorted by label/name and not by track id.
Details:
- Do not fall back to sort-by-label when sort order is nil
- Fixes sort order for songs in album details (was by fault falling back to sort-by-label instead of sort-by-trackid)
=> Do not fall back to sort-by-label when sort order is nil

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/SettingsValuesViewController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.m, XBMC Remote/ViewControllerIPad.m
Bugfix: Update on UI style for Cancel buttons
User experience: Adding a Cancel option for iPhone´s "Power" menu.
Details:
- Use UIAlertActionStyleCancel when showing Cancel button: 
-- Get back to standard look for Cancel buttons in actions sheets. 
-- When replacing UIActionSheets with UIAlertController the style for Cancel buttons was net set correctly.
- Add Cancel option for Power menu on iPhones
-- On iPhone cancelling the Power menu was not user friendly as a Cancel option was missing.
-- Introduce a Cancel option and remove the LED-Torch option (can still be reached via RemoteControl) to show Cancel as last item for smaller iPhones and iPod.
Screenshots:
https://abload.de/img/simulatorscreenshot-il1jl9.png (iPod Power Menu before) …
=> Update on Cancel buttons

XBMC Remote/DetailViewController.m, XBMC Remote/SettingsValuesViewController.m, XBMC Remote/ShowInfoViewController.h, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
Implements missing function report in [forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3027541#pid3027541).
Details:
- Choose different background colors for TV logos
- Processing only done when showing PVR recording details
- Refactoring into Utilities.m to re-use same implementation in different controllers
=> Automatic background color for TV logos in recording details

XBMC Remote/DetailViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
As brought up in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3027133#pid3027133) the current implementation for the Season View background can become a bit aggressive (not to say "froggy" :) ). This PR limits the saturation of the chosen background color for a smoother coloring. In addition, it lets the searchbar have the color of the topmost season background color.
Screenshots:
https://abload.de/img/simulatorscreenshot-isqjef.png (Dexter, before)
https://abload.de/img/simulatorscreenshot-ijkjwl.png (Dexter, after)
https://abload.de/img/simulatorscreenshot-i5xj9x.png (Sherlock, before)
https://abload.de/img/simulatorscreenshot-ismj51.png (Sherlock, after)
https://abload.de/img/simulatorscreenshot-incjzm.png (Muppets, before) …
=> Desaturate season background and choose top most background color for searchbar

XBMC Remote/DetailViewController.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/213.
When rotating on iPad the implementation of `viewWillTransitionToSize` was missing for `DetailViewController`. This caused the view to scroll to top when the rotating from landscape to portrait as this increases the height. This PR adds `viewWillTransitionToSize` and always keeps the intended default ContentOffset which results in not showing the searchbar after rotation.
Bugfix: Avoid searchbar showing after rotation on iPad
=> Avoid searchbar showing after rotation

XBMC Remote/DetailViewController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
This PR resolves an issue report from a [forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3027965#pid3027965).
1. Monochrome images were not properly analyzed for their average color / brightness causing an inadequate choice of background color. This PR reworks the calculation method.
2. The TV station logs for channel list, recording list and recording details now use same aspect ratios for improved UI consistency.
Screenshots:
https://abload.de/img/simulatorscreenshot-ia2k9f.png (monochrome before, recording + channel list)
https://abload.de/img/simulatorscreenshot-i53jr8.png (monochrome before, recording list + details)
https://abload.de/img/simulatorscreenshot-i96j2c.png (monochrome after, recording + channel list)
https://abload.de/img/simulatorscreenshot-ih3kp4.png …
=> Features and fixes around TV station logos

XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/220.
Added boundary checks before accessing an array in `actionSheetHandler`. In case `item` cannot be read the return from method. I tested the error case (leaving the method) and this had no negative side effects, just the action was not executed.
Bugfix: Avoid reported crash in DetailViewController:actionSheetHandler
=> Avoid crash DetailViewController:actionSheetHandler

XBMC Remote/DetailViewController.m
This fixes a major regression I was not observing because I was mainly testing around the possible reset case.
Details:
- Only return on empty item in case an item should be selected
- Before we returned without any further action also when sorting shall be changed
Sorry for any inconvenience. 
Bugfix: Fix regression caused by fix for crash in DetailViewController:actionSheetHandler
=> Fix regression which caused sorting to not work at all

XBMC Remote/AppDelegate.m, XBMC Remote/NowPlaying.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/223.
Make `NowPlaying` controller the first responder and move the `motionBegin` method there. Tested on iPhone Xs and iPad 5G simulator.
Bugfix: Make shake gesture work again (allows to clear playlist)
=> Enable shake recognition in NowPlaying controller

XBMC Remote/DetailViewController.m
In case the default thumb needs to be shown in grid view there are two issues. First, the cell background color is using DarkMode/LightMode but needs to be set to a dark background always. Second, adding the extension "_wall" to the image name which already ends with ".png" results in an unresolvable filename. In effect the grid view was showing an empty white field in LightMode and an empty dark field in DarkMode.
Details:
- Choose the dark default color of grid view as background
- Remove .png suffix before adding _wall suffix
Screenshots (taken from Live TV channel groups):
https://abload.de/img/simulatorscreenshot-i6rjwh.png (before)
https://abload.de/img/simulatorscreenshot-i3lk32.png (after)
Remark: I will remove the ".png" treatment with a future PR that moves the images to …
=> Fix displaying "nocover" images in grid view

XBMC Remote/DetailViewController.m
After showing the Live TV recording list the thumb frame origin and size was not properly set anymore as it still used the recording list settings. This is fixed with setting the default dimension and origin properly.
Screenshot:
<a href="https://abload.de/image.php?img=bildschirmfoto2021-04bjkpk.png"><img src="https://abload.de/img/bildschirmfoto2021-04bjkpk.png" /></a>
Bugfix: Fix wrong thumb dimension after showing recording list
=> Fix wrong cell dimension after showing recordings

XBMC Remote/DetailViewController.m
App sets the background color of cells according to Darkmode/Lightmode. It is better to set a transparent background as a default. This resolves a minor glitch when selecting a row, and still supports setting dedicated background colors for transparent TV station logos.
Details:
- Instead of Darkmode/Lightmode background color use clearColor
- Fixes grey selection not shown under transparent image
Screenshot:
<a href="https://abload.de/image.php?img=bildschirmfoto2021-04wsk30.png"><img src="https://abload.de/img/bildschirmfoto2021-04wsk30.png" /></a>
Bugfix: Fixes minor glitch not showing selection under transparent thumb image in data cell
=> Minor correction in cell background color

XBMC Remote/DetailViewController.m
The App is assuming the season shown on top of the list (season with smallest number) would come as `seasonIdx==0`. This assumption is wrong as the season items can be unsorted. There this PR implements a method to identify the smallest season number and use this to set the color of the searchbar.
Details:
- Introduce method to identify the season which is listed on top the list.
- Choose searchbar color based on this season.
Screenshot:
<a href="https://abload.de/image.php?img=bildschirmfoto2021-04tnk5h.png"><img src="https://abload.de/img/bildschirmfoto2021-04tnk5h.png" /></a>
Bugfix: Fix possibly wrong season view searchbar color
=> Searchbar color for seasons always uses color of topmost season

XBMC Remote/Utilities.m
The App analyzes images for their colors and brightness to decide on background colors. Especially for lately implemented background detection for transparent TV station logos it is important to know the exact format before running the analysis. To ensure the calculations are done accurately this PR forces images into two certain formats: one for images with alpha channel (32 bpp ARGB) and one for images without (32 bpp RGBx). These match the typical formats, conversions were seen rarely during my tests. As an advantage the analysis implementation is reduced as well.
This should finally resolve problems with unreadable TV station logos.
Details:
- Forcing images into certain format before analyzing
- 32 bits per pixel
- If with alpha: kCGImageAlphaPremultipliedFirst (ARGB)
- If without …
=> Enforce specific image formats before analyzing them

XBMC Remote/ShowInfoViewController.m
Three changes:
1. The App is not applying the tint properly when entering the info view (e.g. album info or artists info) for the first time. Only when entering the same content a second time the tint is taken over. This PR sets the tint as soon as the images are loaded and the tint was calculated.
2. The album info view was not showing the album title even though provided. This PR now reads the album title from the correct key.
3. Empty items (e.g. "BORN" or "FOUNDED") should not be visible when empty. This PR hides empty items in album and artist info view.
Bugfix: Set info view's tint at first view
Bugfix: Show album name in album info view
=> Fix ShowInfoVC

XBMC Remote/DetailViewController.m
The App uses slightly different ways of selecting the text and text shadow colors for season and album view. This PR is aligns both views. In addition, this PR fixes an issue with text colors for release and trackcount label not correctly set when the view is shown the first time.
Screenshots:
https://abload.de/img/bildschirmfoto2021-04pwkbz.png
Optimization: Unify look of season and album view
Bugfix: Text colors in album details not properly set at first view
=> Unify text colors for season and album view

XBMC Remote/Utilities.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/245
This PR introduces exception handling via a `@try` / `@catch` block when creating an instance of `SFSafariViewController`. This avoids potential crashes of the App (e.g. when trying to load URL without leading `http://` or `https://`). Instead, the App will present an error message with the non-loadable URL.
Bugfix: Avoid crash of Safari browser
=> Handle Safari exception

XBMC Remote/ShowInfoViewController.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/253
Since 1.6.1 the size of TV show covers was reduced. This PR brings back the original size as in 1.6.0.
Bugfix: Bring back size of TV show cover (same as for movies)
=> Bring back full size for TV Show cover in ShowInfoVC

XBMC Remote/DetailViewController.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/248
The App uses the wrong path for the selected item when long-pressing on a filtered list. In consequence the wrong title was displayed for the action sheet. This PR lets the App choose the correct item and allows to further reduce complexity. This issue is caused by not-yet fixed wrong code from the intial overhaul of the search behavior which was required to make the App run under iOS 14.
Bugfix: Show correct title (taken from item) in action sheet for filtered lists
=> Show correct title in action sheet popup for filtered lists

XBMC Remote/DetailViewController.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/250
Details:
- On iPad we need to present from searchController not only when a non-empty filtered list is available, but also when we have an active but empty searchbar textfield.
Bugfix: Fix longpress on filtered list not showing in case of active but empty searchbar textfield
=> Fix longpress when search textfield active but empty

XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/241.
1. Restore keyboard visibility
When coming back to a filtered list (e.g. filtering for music albums, then select one to go into the detail view, then go back) the App is never showing the keyboard and the search text field is not firstResponder anymore. This PR aligns the behavior with other iOS Apps: The keyboard visibility / editing mode is saved and restored when re-entering the menu.
2. Avoid misbehavior
When a filtered list is shown (e.g. filtering for music albums) and the user hits "Search" the keyboard becomes invisible and allows to touch the toolbar items. Hitting any of these buttons now leads to uncontrolled behavior which can only be fixed via re-entering the whole music menu. This PR avoids this situation by …
=> Fixes around UI behavior while searching

XBMC Remote/AppDelegate.h, XBMC Remote/DetailViewController.m, XBMC Remote/tcpJSONRPC.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/97
This PR implements support for sort tokens for the Remote App. When connecting to the Kodi server the App requests the server´s sort tokens and the server´s setting for "ignore articles when sorting" via the JSON API. As older versions of Kodi do not provide the sort tokens a default set (`"The"`, `"The_"` and `"The."`) is defined -- following the same default Kodi uses.
Remark: The web interface also applies `"A"` and `"An"` as sort tokens. As the Kodi UI does not use this, which most users here compare the App behavior with, and several native speakers voted to only use `"The"` I am sticking to the reduced sort token set.
Feature: Ignore articles based on Kodi sort tokens (e.g. "The")
=> Implement support for sort tokens

XBMC Remote/AppDelegate.h, XBMC Remote/AppDelegate.m, XBMC Remote/MasterViewController.m
Use e.g. 192.168.1.255 instead of 255.255.255.255 as destination address to fix WoL not working on iOS 14.5.
Bugfix: Wake-on-LAN on iOS 14.5 works again
=> Use LAN's broadcast address for Wake-on-LAN

XBMC Remote/NowPlaying.m
The App shows an empty overlay view when clicking on the NowPlaying screen if nothing is playing. This PR simply checks for the already available `nothingIsPlaying` variable.
Bugfix: Do not show song details if nothing is playing
=> Do not show song details if nothing is playing

XBMC Remote/DetailViewController.m
- This avoids presenting an unneeded opaque bar over the bottom part of thumbs/covers
Takes care of a valid comment made in a [forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3028203#pid3028203).
The App does still show empty labels and the corresponding "shadow bar" in fullscreen mode, even though they are not required. This PR removes both label and shadow in fullscreen mode, similar to setting "Hide label in wall view".
Screenshots:
https://abload.de/img/simulatorscreenshot-iwajmq.png (movies, before)
https://abload.de/img/simulatorscreenshot-i9kjxp.png (movies, after)
https://abload.de/img/simulatorscreenshot-iswj98.png (music, before)
https://abload.de/img/simulatorscreenshot-in9jvb.png (music, after)
Bugfix: Remove unneeded shadow bar from covers in fullscreen mode
=> Do not show posterLabel and labelImageView in fullscreen mode

XBMC Remote/ShowInfoViewController.m
The App is not showing the movie covers at the correct position when presenting them in modal view (happens when selecting a movie from fullscreen mode on iPads). This PR corrects the position:
Screenshots (with jewel case):
https://abload.de/img/simulatorscreenshot-ifyjvw.png (iPad 5G, before)
https://abload.de/img/simulatorscreenshot-i2hkqe.png (iPad 5G, after)
Screenshots (without jewel case):
https://abload.de/img/simulatorscreenshot-i65j62.png (iPad 5G, before)
https://abload.de/img/simulatorscreenshot-ia1kj7.png (iPad 5G, after)
https://abload.de/img/simulatorscreenshot-iesjrq.png (iPad Pro 4G, before)
https://abload.de/img/simulatorscreenshot-iezjeb.png (iPad Pro 4G, after)
Bugfix: Correct the position of movie covers in modal view
=> Correct the position of movie cover in modal view

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/ShowInfoViewController.m
The App since 1.6.2 support fullscreen for music albums and artists. But when selecting a music album or an artists the fullscreen mode is stopped and the App falls back into the normal list/grid view. This is not happening when selecting a movie from the fullscreen mode. In this case a detail view (ShowInfoViewController) is presented in modal view.
This PR changes the music behavior to the same as for movies. When an album is selected a modal view of the album details is presented, skipping the track list for the album. When an artists is selected a modal view of the artist details is presented, skipping all albums of this artist. This is not fully consistent to the behavior in list/grid view, but keeps the fullscreen look&feel. You can still reach the skipped view via the upper right …
=> Feature: Music fullscreen also loads ShowInfo view

XBMC Remote/AppDelegate.m, XBMC Remote/PosterCell.m, XBMC Remote/RecentlyAddedCell.m
The App uses a green frame to highlight a selected item in grid view and fullscreen mode. This is done via drawing a green background which is 2x border width bigger as the image shown. There are two issues with this: First, the dimension for the movie covers was not selected properly in fullscreen mode. In consequence the green frame was not having equal border width (screenshot 1). Second, this looked somehow strange when a cover which does match the expected aspect ratio is drawn (see screenshots 3 and 5).
This PR changes the height of the movie cover cells for fullscreen mode to match the expected aspect ratio. Also it changes the highlighting from using a green background to drawing a green frame.
Screenshots:
https://abload.de/img/simulatorscreenshot-i8jj2t.png (fullscreen, before) …
=> Fix posterselect

XBMC Remote/ViewControllerIPad.m
During startup on iPad a sporadic race condition can result in a crash. This is caused by attempting to present the "serverpicker" popup twice. This PR adds a check to avoid presenting the popup again when it is already presented.
Bugfix: Avoid sporadic crash on iPad at startup
=> Avoid crash when attempting to present popup twice

XBMC Remote/DetailViewController.m, XBMC Remote/RemoteController.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/SDWebImage/UIImageView+WebCache.m
The App is throwing several runtime warning when started and while usage. This PR addresses 4 of them.
1. Instead of trying to load an UIImage from `filename = @""` we rather load the invisible `"blank.png"` (happens each start)
Warning:
_Kodi Remote[13395:684990] [framework] CUICatalog: Invalid asset name supplied: ''_
2. Do not try to load images from an empty URL path (e.g. happens when entering music genre menu)
Warning:
_Kodi Remote[13222:678986] nil host used in call to allowsSpecificHTTPSCertificateForHost
2021-04-30 15:50:02.893256+0200 
Kodi Remote[13222:678986] nil host used in call to allowsAnyHTTPSCertificateForHost:
2021-04-30 15:50:02.893425+0200 
Kodi Remote[13222:678986] CFURLRequestSetHTTPCookieStorageAcceptPolicy_block_invoke: no longer implemented and should not be …
=> Fix runtime warnings

XBMC Remote/NowPlaying.m
For the musepack audio codec a mapping method was introduced to map the codec name provided by Kodi server to the provided icons. The App only uses this for audio playback. This PR introduces the same for video playback. The App will now also show the correct audio codec icon in case a video is using a musepack encoded audio stream.
Bugfix: Show musepack icon in codec details of videos
=> Show musepack icon also for video playback

XBMC Remote/NowPlaying.m
https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/265 only works for iPhone. For iPad the song details are triggered via a different call. This PR now adds the check inside of `toggleSongDetails` which loads and presents the view we do not want show. Now works on both iPhone and iPad devices.
Bugfix: Do not show song details if nothing is playing on iPad and iPhone
=> Do not show song details if nothing is playing on iPad and iPhone

XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.h, XBMC Remote/HostManagementViewController.m, XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m, XBMC Remote/ShowInfoViewController.h, XBMC Remote/ShowInfoViewController.m
There are crashes of `pushViewController` reported from users via AppStore. The call stack can be reproduced in case the same controller is pushed again. Looking in the App's code there are three cases where a singleton constructor is used to create a child view controller instance only once before calling `pushViewController` to show it. In all other places there are simply new view controller instances created. This PR removes the singleton constructor and lets the App create a new instance each time before calling `pushViewController`.
Bugfix: Fix pushViewController crashes reported via AppStore
=> Avoid crash when attempting to push same controller again

XBMC Remote/NowPlaying.m
The NowPlaying screen was not handling the "Pictures" mode well. While showing pictures there is no need to display the progressbar and runtimes. Also the details screen should be hidden. The only function which is available in this screen while showing picture is to enable shuffle. As you cannot disable shuffle anymore once it was enabled, this PR is simply removing the details screen in picture mode. Picture mode is identified as `playerID==2`.
Bugfix: Adapt UI for pictures mode (no progressbar, no details screen)
=> Adapt NowPlaying to Pictures mode

XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.h, XBMC Remote/HostManagementViewController.m, XBMC Remote/MasterViewController.h, XBMC Remote/MasterViewController.m, XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.h, XBMC Remote/RemoteController.m, XBMC Remote/RightMenuViewController.h, XBMC Remote/RightMenuViewController.m, XBMC Remote/SettingsValuesViewController.m, XBMC Remote/ShowInfoViewController.h, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/ViewControllerIPad.h, XBMC Remote/ViewControllerIPad.m, XBMC Remote/VolumeSliderView.h, XBMC Remote/VolumeSliderView.m, XBMC Remote/XBMCVirtualKeyboard.h, XBMC Remote/XBMCVirtualKeyboard.m, XBMC Remote/tcpJSONRPC.h, XBMC Remote/tcpJSONRPC.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/277.
Details:
- Avoid using property which is regularly overwritten
- Move identical and repeated code into new method `getJsonRPC`
Maintenance: Replace jsonRPC variables and properties with common method
=> Introduce method getJsonRPC

XBMC Remote/ShowInfoViewController.h, XBMC Remote/ShowInfoViewController.m
Fixes an issue reported in a [forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3036044#pid3036044). On iPad and in fullscreen mode the "Done" button could be inserted multiple times when the modal view was pulled down and flipping back. This PR adds a check if the button was already created and added to the toolbar. Priority for this fix not too high as the issue is in since several years.
Bugfix: Avoid multiple "Done" buttons on ShowInfo screen when in fullscreen mode on iPad
=> Avoid multiple "Done" buttons when in modal view

XBMC Remote/DetailViewController.m
This PR fixes an issues in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3036302#pid3036302). Now the longpress actionsheets are also showing up in the newly added fullscreen mode for Music items.
Details:
- In fullscreen mode the longpress actionsheet was not displayed as the wrong displaying controller was defined.
- In relation to this also corrected the presenting controller for popups being shown as result of selecting an action from the sheet.
Bugfix: Longpress menus were not showing in fullscreen modal view
=> Fix longpress actionsheets in fullscreen modal view

XBMC Remote/VolumeSliderView.m, XBMC Remote/VolumeSliderView.xib
Takes care of feedback from [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3036679#pid3036679). This PR brings back the volume up/down button functionality for iPhone.
Details:
- Re-enable volume plus/minus button for iPhone
- Ensure correct position and aspect ratios of title (iPad) and image (iPhone)
Improvement: Bring back volume up/down button functionality on iPhone
=> Bring back volume up/down button functionality on iPhone

XBMC Remote/DetailViewController.m
Expect to close https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/291. Since the rework of sorting to support "ignore articles" the option to sort by method `"none"` fell back to `"label"` (= sort-by-name). This PR will now change the code to skip sorting if the sort method is `"none"`.
Screenshots:
https://abload.de/img/bildschirmfoto2021-059bkr5.png
Bugfix: No sort-by-name when sort method is "none" (e.g. in AddOns, Recently Added)
=> Handle sort-by-none

XBMC Remote/NowPlaying.m
The App keeps the SongDetails view open when playback ends. In this situation it cannot be closed by the user anymore. This PR allows to close the SongDetails view and automatically closes it when the playback ends.
Bugfix: Close SongDetails when playback ends
=> Close SongDetails when playback ends

XBMC Remote/NowPlaying.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/304.
The App is not updating the playlist if this changed from server side (e.g. adding an album to the playlist). This PR adds listeners to the `"Playlist.On"`-notifications and calls the already implemented method to update the playlist in the App. Verified with Kodi 20 Alpha.
Bugfix: Update App playlist when the playlist changed on server
=> Fix: Update App playlist when it changed on server

fastlane/metadata/en-US/marketing_url.txt
Adding [https://kodi.tv](https://kodi.tv) as marketing URL for AppStore.
[no app] Add kodi.tv as marketing URL for AppStore
=> Add kodi.tv as marketing URL for AppStore

XBMC Remote/AppDelegate.h, XBMC Remote/AppDelegate.m
Long planned change to rework `AppDelegate.m` which holds the main configuration for JSON requests to Kodi server and the main menus. The rework will move to easier-to-read literals instead of initializers and will use common methods for repeated code sequences.
This should be observed in TF builds for a while. Making this a draft PR until we see the 1.7 Release showed no issues over a reasonable amount of time.
Maintenance: Rework AppDelegate.m/.h
=> Rework AppDelegate.m/.h

XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/296.
The App's TV Show view for the user looks like a grid / fullscreen view when banners are shown. In the background the cells are still following the iOS color mode (DarkMode / LightMode). The background becomes visible when the index is becoming visible, e.g. when sorting by year, resulting in a white background which does not match user's expectation. This PR will always use a dark cell background for only this view and only when showing banners.
Optimization: Dark cell background for TV Show banner view
=> Always choose dark cell color for banner TV Show view

XBMC Remote/DetailViewController.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/318.
Details:
- Fixes visible highlighting when touching un-used / non-loaded buttons (see screenshot in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/318)
- Reworked to modern objective c
Bugfix: Hide non-loaded toolbar buttons
=> Hide non-used buttons in toolbar

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/321.
When longpressing on a recording item the actionsheet title shows the recording name twice. This PR changes the actionsheet tilte to either show `"plotoutline"` after the recording name, or only show the recording name without adding a new line.
Bugfix: Fix actionsheet title for recordings
=> Fix recording details

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/294.
Details:
- Remove available sort methods from JSON command parameters
- Kodi server does not need above information as sorting is done locally in the App. Kodi server might in future even reject these malformed JSON requests.
- Remove unneeded functions and code related to this change.
- Rename key to "available_sort_methods" as it moved from sort section to general parameters.
Maintenance: Clean up malformed sort request via JSON API
=> Remove available sort methods from JSON command parameters

XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.m
The App always shows "-" instead of a TV Shows's amount of episodes. This is caused by using the wrong key `"showtitle"` which is not present. This PR fixes this.
Details:
- Use correct key `"episode"`
- Let `getStringFromDictionary` support `NSNumber`
Screenshot:
https://abload.de/img/bildschirmfoto2021-065ojxk.png
Bugfix: Show correct amount of episodes in Info view
=> Bugfix: Show correct amount of episodes in Info view

XBMC Remote/AppDelegate.h, XBMC Remote/DetailViewController.m, XBMC Remote/tcpJSONRPC.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/308.
The App always shows **all** movie sets, independent of the Kodi server user setting to only show movie sets with >1 movie. This PR will enable the App to respect the Kodi server user setting. It will read `videolibrary.groupsingleitemsets` at connect, so in case you change the setting you need to re-connect once. If the user wants to ignore 1-movie sets, a post-processing is applied to remove the irrelevant movie sets from the list provided via the API.
Feature: Respect setting to show/ignore 1-movie sets
=> Read setting to show 1-movie-sets and ignore such sets when disabled

XBMC Remote/AppDelegate.m, XBMC Remote/Settings.bundle/Root.plist, XBMC Remote/Settings.bundle/cs.lproj/Root.strings, XBMC Remote/Settings.bundle/de.lproj/Root.strings
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/306.
Details:
- Each main menu entry can be switched on/off in Kodi App settings (default is ON for each)
- Added localized strings for English and German
- Minor refactoring when building the menu (iPad per default now also has NowPlaying)
Feature: Make main menu configurable
=> Feature: Make main menu configurable

XBMC Remote/HostManagementViewController.xib, XBMC Remote/NowPlaying.xib
As side effect of the massive icon/remote/layout rework there are some runtime warnings seen which point to xib´s still having defined few images which are not available anymore. This PR resolves this and either give the appropriate image or removes it from xib.
Bugfix: Resolve XCode runtime warnings about missing images
=> Avoid runtime warnings in XCode

XBMC Remote/AppDelegate.m, XBMC Remote/MasterViewController.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/iPad/MenuViewController.m, XBMC Remote/mainMenu.h
Use enum instead of magic number for "family" property.
Maintenance: Use enum instead of magic number for "family" property
=> Replace magic numbers with enum for property "family"

XBMC Remote/DetailViewController.m
This PR fixes a regression of the `AppDelegate` rework which was merged with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/283 (since first 1.7.2 build).
Details:
- `sheetActions` are expected as mutable array to be able to tailor them.
- Use `mutableCopy` as the sheetAction arrays are non-mutable since the `AppDelegate` rework.
Bugfix: Fix missing actionSheet options for playlists, movies, tv shows and videos
=> Bugfix: Fix missing actionSheet options

Kodi Remote.xcodeproj/project.pbxproj, XBMC Remote/AppDelegate.h, XBMC Remote/AppDelegate.m, XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m, XBMC Remote/ConvenienceMacros.h, XBMC Remote/DetailViewController.m, XBMC Remote/ECSlidingViewController/ECSlidingViewController.m, XBMC Remote/HostManagementViewController.m, XBMC Remote/HostViewController.m, XBMC Remote/KenBurns/JBKenBurnsView.m, XBMC Remote/Kodi Remote-Prefix.pch, XBMC Remote/MessagesView.m, XBMC Remote/NowPlaying.m, XBMC Remote/PosterCell.m, XBMC Remote/RecentlyAddedCell.m, XBMC Remote/RemoteController.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/SettingsValuesViewController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.m, XBMC Remote/VolumeSliderView.m, XBMC Remote/XBMCVirtualKeyboard.m, XBMC Remote/iPad/StackScrollViewController.m
Use `#define` to improve code readability. 
- for `UIUserInterfaceIdiom` checks
- for `UIInterfaceOrientation` checks
Maintenance: Use #defines for device type and device orientation checks
=> Maintenance: Use #defines to improve code readability

XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/ShowInfoViewController.m
This PR applies follwing changes. 
- First change fixes an issue described in a [forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3049725#pid3049725), which results in double `1x01` (or whatever season/episode is played) shown in the App's playlist when the playback was started via the Kodi UI. 
Screenshot: https://abload.de/img/a5137fe2-9c4b-4309-ap0k3p.jpeg
- Second change fixes missing or wrong thumbnails when calling the info screen via longpress on the playlist item.
Screenshots:
https://abload.de/img/simulatorscreenshot-i6iku0.png (TVShow before)
https://abload.de/img/simulatorscreenshot-i5lkam.png (TVShow after)
https://abload.de/img/simulatorscreenshot-it5ksx.png (Movie before)
https://abload.de/img/simulatorscreenshot-iqjkie.png (Movie after)
- Last changes are …
=> Bugfix: Resolve issues around playlist

XBMC Remote/VolumeSliderView.m
This PR corrects the vertical position of the volume control elements for iPads.
<a href="https://abload.de/image.php?img=bildschirmfoto2021-07gljs0.png"><img src="https://abload.de/img/bildschirmfoto2021-07gljs0.png" /></a>
Bugfix: Correct vertical position of volume control on iPad
=> Bugfix: Correct vertical position of volume control on iPad

XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.m, XBMC Remote/HostViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/ViewControllerIPad.m, XBMC Remote/iPad/StackScrollViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/355.
Reading the bottom padding is implemented the same way multiple times in the code. This PR moves the related code to `Utilities` and provides the common method `getBottomPadding`.
Maintenance: Avoid duplicated code around reading bottom padding
=> Avoid duplicate code when reading bottom padding

XBMC Remote/RemoteController.m, XBMC Remote/cellView.xib, XBMC Remote/cellViewIPad.xib
This PR applies two changes:
1. Use `IS_IPHONE` macro for idiom check (was overseen in latest remote screen rework)
2. Use same color for main menu text when highlighted or not (see screenshot)
Screenshot: https://abload.de/img/bildschirmfoto2021-083lkq7.png
Bugfix: Consistent main menu text colors when highlighting
=> Bugfix: Main menu text color and idiom check macro

XBMC Remote/NowPlaying.m
With v1.6.2 a regression came in which resulted in the jewel case being drawn on top of the NowPlaying details view. This PR fixes this and moves the `songDetailsView` back on top.
Screenshots: https://abload.de/img/bildschirmfoto2021-08qhk5a.png
Bugfix: Properly display NowPlaying details with enabled jewel case
=> Bugfix: Properly display NowPlaying details with enabled jewel case

XBMC Remote/RemoteController.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/ViewControllerIPad.m, XBMC Remote/VolumeSliderView.h, XBMC Remote/VolumeSliderView.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/358.
Add volume slider to remote screen:
- When screen size allows (`height >= 568`) add the volume bar on top.
- Use `leftAnchor` to differentiate between embedded and full screen.
- Align both iPad/iPhone volume elements in vertical center of screen.
Feature: Show volume slider on remote screen (not working for iPhone 4S)
=> Feature: Add volume slider to remote screen

XBMC Remote/Utilities.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/366.
Force images to desired format before analyzing the average color:
- Desired format: `kCGImageAlphaNoneSkipLast` or `kCGImageAlphaPremultipliedFirst`, 32bpp, `kCGBitmapByteOrderDefault`
- ByteOrder was not taken into account when checking for the need to re-format an image.
- Check unmasked CGBitmapInfo against desired format.
- Fixes issues with automatic background color selection for TV station logos when rounded corners are enabled.
Bugfix: Fix issues with automatic TV station background while rounded corners are enabled
=> Bugfix: Fix issues with automatic TV station background while rounded corners are enabled

XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/PosterCell.m, XBMC Remote/ShowInfoViewController.m
This PR fixes feedback from a [forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3055353#pid3055353). The following topics are fixed:
1. Show rounded corners for recording details
<a href="https://abload.de/image.php?img=bildschirmfoto2021-08kfkmw.png"><img src="https://abload.de/img/bildschirmfoto2021-08kfkmw.png" /></a>
2. Show rounded corner for playlist thumbs (same as for thumbs in list view)
<a href="https://abload.de/image.php?img=bildschirmfoto2021-087bkmx.png"><img src="https://abload.de/img/bildschirmfoto2021-087bkmx.png" /></a>
3. Do not show border for TV logos in recording list
<a href="https://abload.de/image.php?img=bildschirmfoto2021-08xck5l.png"><img src="https://abload.de/img/bildschirmfoto2021-08xck5l.png" /></a>
4. Use correct thumbsizes and frames for …
=> Bugfix: Fix rounded corners for some use cases

XBMC Remote/zh-Hans.lproj/Localizable.strings
This PR removes a control character from Chinese language file.
Weblate can not process this file with the control character present.
Please merge https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/377 first.
[not app] Remove control character from Chinese translation
=> Remove control character from Chinese translation

XBMC Remote/DetailViewController.m, XBMC Remote/Utilities.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3055992#pid3055992)
Details:
- Do not alter the views dimensions as the rounded corner function can be called multiple times per cell (e.g. when editing a playlist).
- Keep using `CGRectInset` to have minimum free space around the thumbs (`1.0 / UIScreen.mainScreen.scale`). This looks more convenient even though it eats some space from the image content.
Screenshot: https://abload.de/img/bildschirmfoto2021-08hnj5h.png
Bugfix: Do not change thumbsize when editing a playlist
=> Bugfix: Do not change thumbsize when editing a playlist

fastlane/Fastfile
After changing app version without release beta tags continue to use old version which doesn't look right.
=> [fastlane] sync app version with tag

XBMC Remote/DetailViewController.m, XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.m
While reviewing https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/380 I recognized a regression which was caused when removing compile warnings during the initial iOS 14 migration end of 2020. This caused two texts -- displaying the amount of search results and the amount of "more" items -- not being translated correctly anymore as the related localized strings contain the formatting `"%d"`. This PR goes back to the old formatting and resolves the warnings through casting to `int`. As a result the existing translations are again in use.
Screenshots (French): https://abload.de/img/bildschirmfoto2021-09kwkad.png
Second change removes a superfluous string which is not needed as the text is overwritten with the desired text for the current state of the pull-down-sync menu when displayed. …
=> Bugfix: Go back to  %d formatting to use existing translations

XBMC Remote/RemoteController.m
As discussed in https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/344 the new remote control toolbar buttons shall not be drawn into iPhone´s safe area.
Screenshot: https://abload.de/img/bildschirmfoto2021-09oukpo.png
Optimization: Do not draw remote control toolbar into safe area
=> Optimization: Do not draw remote control toolbar into safe area

XBMC Remote/DetailViewController.m, XBMC Remote/SDWebImage/UIImageView+WebCache.m, XBMC Remote/ShowInfoViewController.m
This PR provides several bugfixes and minor refactoring:
1. Recording details shall not show jewel cases. This is consistent with the TV logo in the list views
<a href="https://abload.de/image.php?img=bildschirmfoto2021-09ztkw4.png"><img 
src="https://abload.de/img/bildschirmfoto2021-09ztkw4.png" /></a>
2. Fix automatic background color for TV logos in recording details (regression of rounded corners feature)
<a href="https://abload.de/image.php?img=bildschirmfoto2021-09dhj9v.png"><img src="https://abload.de/img/bildschirmfoto2021-09dhj9v.png" /></a>
3. Provide default images on a failed load attempt (verified with non-existing TV logo images and empty thumbnail paths)
<a href="https://abload.de/image.php?img=bildschirmfoto2021-0939jpa.png"><img …
=> Bugfix: Recording details and failed attempts to load images

XBMC Remote/SDWebImage/UIImageView+WebCache.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/394.
Since we now directly call  `setImageWithURL:placeholderImage:options:andResize:withBorder:progress:completed:` from DetailViewController `size` must be scaled up to the native resolution _in_ this function. Before, this was only done for helper functions which are now not called anymore.
Screenshot:
<a href="https://abload.de/image.php?img=bildschirmfoto2021-092gk6y.png"><img src="https://abload.de/img/bildschirmfoto2021-092gk6y.png" /></a>
Bugfix: Fix reduced resolution for thumbnails
=> Bugfix: Fix reduced resolution for thumbnails

XBMC Remote/tcpJSONRPC.m
Kodi versions < 16 do not support the setting to show or ignore movie sets with only 1 movie (`videolibrary.groupsingleitemsets`). For these Kodi versions we need to allow 1-movie sets.
Bugfix: Do not ignore 1-movie-sets for Kodi versions  < 16
=> Bugfix: Do not ignore 1-movie-sets for Kodi versions  < 16

XBMC Remote/AppDelegate.m, XBMC Remote/Settings.bundle/Root.plist
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/392.
This PR adds the missing definition of two default values for the App settings. In addition, it implements a suggestion by @kambala-decapitator to initialize the user defaults using `registerDefaults`. This will allow to avoid `nil` checks when interpreting the settings.
Bugfix: Default value not shown for 2 settings
Maintenance: Use registerDefaults to set settings for all values
=> Rework userdefaults and define missing default values

XBMC Remote/ViewControllerIPad.m
Fixes 1 out of 4 reported crashes in App version 1.8 (also see https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/401).
Creating a new instance of `HostManagementViewController` before calling `presentViewController` avoids possible crash.
Bugfix: Avoid presentViewController crash
=> Bugfix: Avoid presentViewController crash

XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/XBMCVirtualKeyboard.m
Fixes 2 out of 4 reported crashes in App version 1.8 (also see #401).
Calling `stringWithContentsOfURL:encoding:error:` could block the main thread. This PR asynchronously calls`NSUrlSession` to fix it. In addition, some code duplication is resolved.
Bugfix: Avoid crash when sending HTTP request to Kodi
=> Bugfix: Avoid crash by blocked stringWithContentsOfURL:encoding:error:

XBMC Remote/tcpJSONRPC.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/405.
In all Remote App versions from 1.6.2 to 1.8 the App crashes when attempting to connect to a XBMC 11 server. This PR fixes this issue and brings back the support for this quite old server version.
In future it might be a good idea to remove the support for XBMC 11 (and earlier). This allows to remove a good amount of special treatment in the code. Nevertheless, this should be done not only as part of a minor update.
Bugfix: Re-enable support for XBMC 11
=> Bugfix: Support XBMC 11 and earlier when checking the API version

XBMC Remote/AppDelegate.m, XBMC Remote/Settings.bundle/Root.plist, XBMC Remote/Settings.bundle/de.lproj/Root.strings, XBMC Remote/Settings.bundle/en.lproj/Root.strings, XBMC Remote/de.lproj/Localizable.strings, XBMC Remote/en.lproj/Localizable.strings
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/387.
- Have "Videos" main menu entry
- "Videos" toolbar direct access: "Music Videos", "Recently Added Music Videos", "File mode", "Video Add-ons"
- "Videos" toolbar "more menu": "Video Playlists"
- In "Movies" toolbar's "more menu" the entry for "Music Videos" will be removed
- In "TV Show" toolbar's "more menu" an entry for "Video Playlists" will be added
Screenshots:
<a href="https://abload.de/image.php?img=simulatorscreenshot-ieek1d.png"><img src="https://abload.de/img/simulatorscreenshot-ieek1d.png" /></a> <a href="https://abload.de/image.php?img=simulatorscreenshot-itfjsp.png"><img src="https://abload.de/img/simulatorscreenshot-itfjsp.png" /></a>
Feature: Introduce Videos main menu entry
=> Feature: Introduce Videos main menu entry

XBMC Remote/AppDelegate.m
Issue was introduced with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/426 and caused by calling `imageNamed` with an empty string.
Bugfix: Fix runtime warning caused by imageNamed: with empty string
=> Bugfix: Fix runtime warning caused by imageNamed:@""

XBMC Remote/ShowInfoViewController.h, XBMC Remote/ShowInfoViewController.m
In the details view for a broadcast (TV > All channels > Select channel > Channel guide > Select broadcast) the channel logo background is not set. This PR fixes this minor issue.
Bugfix: Fix channel logo background in broadcast detail view
=> Bugfix: Fix broadcast detail view

XBMC Remote/ShowInfoViewController.xib
This PR moves `coverView` fully into the visible area. This (minor) glitch could so far only be recognized when showing an artist image which fills the view and the user at same time has "rounded corners" enabled.
Bugfix: Move detail view fully into visible area
=> Bugfix: Move detail view fully into visible area

XBMC Remote/DetailViewController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/cs.lproj/Localizable.strings, XBMC Remote/de.lproj/Localizable.strings, XBMC Remote/en.lproj/Localizable.strings, XBMC Remote/es.lproj/Localizable.strings, XBMC Remote/fr.lproj/Localizable.strings, XBMC Remote/it.lproj/Localizable.strings, XBMC Remote/nl.lproj/Localizable.strings, XBMC Remote/pl.lproj/Localizable.strings, XBMC Remote/pt-PT.lproj/Localizable.strings, XBMC Remote/sv.lproj/Localizable.strings, XBMC Remote/tr.lproj/Localizable.strings, XBMC Remote/zh-Hans.lproj/Localizable.strings
Should be merged after #440.
This PR avoids code duplication via tailoring `getDateFromItem` and changes date formatting to make use of `NSDateFormatterStyle` instead of localized strings. This solves the `setDateStyle`-part of https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/442.
In Addition, the German translation of "First aired on" is corrected. It details a _date_, and not a _channel_.
Bugfix: Correct German translation for "First aired on"
Maintenance: Simplify date formatting
=> Rework date formatting

XBMC Remote/DetailViewController.m, XBMC Remote/RemoteController.m, XBMC Remote/Settings.bundle/Root.plist, XBMC Remote/Settings.bundle/cs.lproj/Root.strings, XBMC Remote/Settings.bundle/de.lproj/Root.strings, XBMC Remote/Settings.bundle/en.lproj/Root.strings, XBMC Remote/Settings.bundle/es.lprj/Root.strings, XBMC Remote/Settings.bundle/fr.lproj/Root.strings, XBMC Remote/Settings.bundle/it.lproj/Root.strings, XBMC Remote/Settings.bundle/nl.lproj/Root.strings, XBMC Remote/Settings.bundle/pl.lproj/Root.strings, XBMC Remote/Settings.bundle/pt-PT.lproj/Root.strings, XBMC Remote/Settings.bundle/sv.lproj/Root.strings, XBMC Remote/Settings.bundle/tr.lproj/Root.strings, XBMC Remote/Settings.bundle/zh-Hans.lproj/Root.strings, XBMC Remote/Utilities.m, XBMC Remote/cs.lproj/Localizable.strings, XBMC Remote/de.lproj/Localizable.strings, XBMC Remote/en.lproj/Localizable.strings, XBMC Remote/es.lproj/Localizable.strings, XBMC Remote/fr.lproj/Localizable.strings, XBMC Remote/it.lproj/Localizable.strings, XBMC Remote/main.m, XBMC Remote/nl.lproj/Localizable.strings, XBMC Remote/pl.lproj/Localizable.strings, XBMC Remote/pt-PT.lproj/Localizable.strings, XBMC Remote/sv.lproj/Localizable.strings, XBMC Remote/tr.lproj/Localizable.strings, XBMC Remote/zh-Hans.lproj/Localizable.strings
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/442.
Current implementation for language selection ignores the iOS preferred language, and only the Remote App language is used (see screenshots below). This App-specific implementation lets the selected language define the locale via the localized string `LocaleIdentifier`.
This PR uses the preferred language as provided by iOS and reads `currentLocale` from the system settings. The language can still be selected for the App specifically by the user (see screenshots below), but `currentLocale` is used. All settings and translations related to the former language selection are removed.
[![](https://camo.githubusercontent.com/af017c1f93d94fa9be59b115a0b3297b04a22c2298d35db33068528672d7701c/68747470733a2f2f61626c6f61642e64652f696 …
=> Maintenance: Rework handling of language and locale

XBMC Remote/DetailViewController.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/453.
The code has a hard coded access pattern instead of using the correct array index. This results in a crash when trying to access a non-existing array index after we moved the channel groups to tab index 1 with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/386.
Bugfix: Fix crash when accessing channel guide from channel group list
=> Use correct array index when reading epg

XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/SDWebImage/UIImageView+WebCache.m, XBMC Remote/ShowInfoViewController.m
This PR covers four aspects:
1. Improve the performance when "rounded corners" is enabled. Adding rounded corners to images is now processed a lot less, and only where needed. Before, especially the season view was lagging.
2. Improve the readability of the search bar. The text color now is the same as for the album/season details view, which provides better contrast. When there is no coloring available, the search bar text color follows Dark/Light mode.
3. Ensure that in episode view always the top most season's color is chosen to colorize the search bar and navigation bar. Before, the wrong color was chosen when moving from season view to TV show details and back.
4. Refactor some code to avoid code duplication.
Improvement: Better performance when "rounded corners" is enabled …
=> Improvement: Performance and color handling

XBMC Remote/Utilities.m
Suggestion from [forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3069432#pid3069432): Do not show years <= 0.
<a href="https://abload.de/image.php?img=bildschirmfoto2021-11juj93.png"><img src="https://abload.de/img/bildschirmfoto2021-11juj93.png" /></a>
Improvement: Ignore year <= 0 and show empty string instead
=> Improvement: Ignore year <= 0 and show empty string instead

XBMC Remote/HostManagementViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.h, XBMC Remote/RemoteController.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/456.
For TF build 1.8.2-b4  it was reported that the remote screen behaved strange when the remote screen was entered via the newly added navigation bar remote-button. In this case the pan gesture was not handled properly. This PR fixes this and follows the behaviour of the `NowPlaying` screen.
First issue was caused by a missing reaction to the signals `"ECSlidingViewUnderRightWillAppear"` (attempting to show the so-called underRight menu, in the remote's case this is the settings menu with the custom buttons) and `"ECSlidingViewTopDidReset"` (when the underRight menu was closed again) from `ECSlidingViewController`. This fixes a problem where you could see other screens scrolled in a small frame on the left side of the …
=> Bugfix: Pan gestures and gesture view conflicted when remote screen was opened via navigation bar button

XBMC Remote/DetailViewController.m
As I wrote in a forum post alley, the common handling of thumbnails and icons is a nightmare. Here are some more icon/thumbnail types which should not have borders around them.
Bugfix: Do not draw unwanted borders for several icon types
=> Bugfix: Do not draw unwanted borders for several icon types

XBMC Remote/RemoteController.m
Fixes an issue reported in a [forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3069607#pid3069607). When the remote screen has the gesture zone active the pan gestures were blocked even if the App was showing the remote's `underRight` screen (remote was swiped left to show the custom button screen). This PR allows the pan gesture in this case now.
In addition, a minor refactoring is done to introduce a helper function for setting the area of the pan gesture (no functional change).
Bugfix: Pan gesture not working when showing Remote's underRight screen
=> Bugfix: Pan gesture not working when showing Remote's underRight screen

XBMC Remote/ECSlidingViewController/ECSlidingViewController.m
When swiping left, the velocity is < 0. To detect a swipe gesture to the left we need to check for a minimum velocity which is smaller than a certain negative value.
Bugfix: Correctly detect swipe left
=> Bugfix: Correctly detect swipe left

XBMC Remote/RightMenuViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/465.
Avoid possible out-of-bounds access in `canEditRowAtIndexPath`. In case we are out of bounds, respond with `NO` (= not editable).
Bugfix: Fix potential crash in canEditRowAtIndexPath
=> Bugfix: Fix potential crash in canEditRowAtIndexPath

Kodi Remote.xcodeproj/project.pbxproj
Xcode project contains some text files (readme, license, contributing) that are copied to app bundle. PR prevents their copying.
=> [not app] don't bundle text files that end user never sees

XBMC Remote/AppDelegate.m
In https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/445 I had overseen two obvious issues of exactly the same type. Again, this fixes runtime warnings when trying to load images with name `@"".`
Bugfix: Fix two more runtime warnings caused by imageNamed: with empty string
=> Bugfix: Fix two more runtime warning caused by imageNamed: with empty string

XBMC Remote/RemoteController.m
The gesture zone needs to be initialized including its gestures also for the embedded screen. This was broken -- but not reported yet -- since App version 1.8.0.
Bugfix: Fix non-working gesture zone when entering remote from NowPlaying
=> Bugfix: Fix non-working gesture zone when entering remote from NowPlaying

XBMC Remote/RemoteController.m
This PR simplifies the logic to support or block the pan gestures in the Remote screen, depending on its current mode (active or inactive gesture zone). The former solution was enabling or disabling the pan gesture based on the mode. This needed some special handling for the so-called underRight (aka custom buttons) screen which still was showing some problems. This PR is re-using the iPad's solution for the iPhone as well: Pan gesture is always supported for the full screen, but ignored if the gesture zone is touched. This implicitly takes into account the status of the gesture zone and avoid special handling of other screens.
Bugfix: Pan gesture in remote not working after entering underRight screen for the first time
=> Rework pan gesture for iPhone, re-using iPad's solution

XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
Since the rework of `ShowInfoViewController` (see https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/438) it is not required anymore to differentiate the way how to represent non-existing data. Formerly, the detail screens where using `"-"`, whereas all other screen simply used `""`. This rework now allows to remove the parameter `emptyString:` from several helper functions, and to simplify the check for non-existing data in `ShowInfoViewController`. 
In addition, this PR changes the helper function's parameters to directly use `id` objects instead of separate dictionary and key parameters. This simplifies the calls itself.
Maintenance: Refactor several helper functions
=> Maintenance: Refactor several helper functions

XBMC Remote/DetailViewController.m
This PR fixes an interesting regression caused by https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/461/commits/f5c2606b08c38531ab5b79793526db4b91e3badf.
Since long ago the recording list was by fault showing the content of the key `"year"`. This key was obviously by fault filled with the content of `"plot" `before. Since https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/461/commits/f5c2606b08c38531ab5b79793526db4b91e3badf the processing of year strings is corrected and will not show any non-number strings anymore. In consequence the recording list was not showing the plot anymore. 
The fix is simply to use the correct key `"plot"`.
Bugfix: Show plot in recording list
=> Bugfix: Show plot in recording list

XBMC Remote/HostManagementViewController.xib
Since the latest update of German strings I found the readability of the buttons in `HostManagementVC` is really bad for longer localized strings. This PR improves the readability by allowing more space/width.
Screenshots (German/Portuguese):
<a href="https://abload.de/image.php?img=bildschirmfoto2021-115qkkx.png"><img src="https://abload.de/img/bildschirmfoto2021-115qkkx.png" /></a>
Improvement: Better readability of buttons in host management screen
=> Improvement: Better readability of buttons in host management screen

XBMC Remote/DetailViewController.m
Fixes a regression of https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/476 which caused the default thumbs of non-timer item's wall views to fall back to recording thumbs. The fix is to check if the key `"isreminder"` is present or not. If not, keep the default thumb. If it is present, the item is a timer and we can read the value to decide whether to show a recording or a reminder thumb.
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2021-11bdkdi.png"><img src="https://abload.de/img/bildschirmfoto2021-11bdkdi.png" /></a>
Bugfix: Keep default thumbs in wall view of non-timer items
=> Bugfix: Keep default thumb if key "isreminder" is not present

XBMC Remote/ECSlidingViewController/ECSlidingViewController.m
This PR is taking up a discussion from [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3072368#pid3072368). Main idea is to align the slide/pan behaviour of the App-internal and the iOS implementation. The change is quite simple and now does check _both_ the _velocity_ of a sliding gesture (flicking) and the _amount_ of the slide (snap back when moved <=50% of the screen width, slide when >50%).
Improvement: Similar behaviour for App's and iOS pan gesture
=> Improvement: Similar behaviour for App's and iOS pan gesture

XBMC Remote/SettingsValuesViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/485.
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/486.
This PR is just fixing two observed topics which are easily recognized by users: Non-usable displayed values in sliders (e.g. "{0:d}") and truncated strings.
The first issue is caused by Kodi server providing different format strings in different versions. Examples (old -> new -> display):
`"%i %%"` -> `"{0:d} %"` -> "3 %" (UI Zoom)
`"%i.0 dB"` -> `"{0:d}.0 dB"` -> "96.0 dB" (Music Replaygain)
`"%i ms"` -> `"{0:d} ms"` -> "750 ms" (Delays)
`"%i"` -> `"{0:d}"` -> "5" (Stereoscopic 3D effect)
This PR handles above cases -- tested with Kodi 17.6 and Kodi 19.3.
The second issue is caused by the App just hardcoding the label height for different types of …
=> Bugfixes: Settings view controller

XBMC Remote/AppDelegate.h, XBMC Remote/AppDelegate.m, XBMC Remote/HostManagementViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/488.
This PR will trigger the Local Network Privacy Alert when a user manually selects a server. It is expected to resolve a problem where users could not connect to Kodi server after iOS upgrade from iOS before 14 to iOS 14 or later. Without this PR users need to run "Find Kodi" at least once after an update or clean install of the Remote App.
Improvement: Trigger Local Network Privacy Alert on manual sever selection
=> Improvement: Trigger Local Network Privacy Alert on manual sever selection

Kodi Remote.xcodeproj/project.pbxproj, XBMC Remote/Settings.bundle/en-us.lproj/Root.strings, XBMC Remote/en-US.lproj/InfoPlist.strings, XBMC Remote/en-US.lproj/Localizable.strings
Based on a discussion on the forums. This PR add US localization for the English translations. Only current difference is _Favourites_ vs. _Favorites_.
Feature: Add en-us as localized language
=> Feature: Add en-us as localized language

XBMC Remote/Utilities.m
The key `"activeyears"` provides an array of length 1 with a string inside. This results in a crash when calling `[item integerValue].`
Bugfix: Fix crash when handling an array inside getYearFromItem
=> Bugfix: Properly handle arrays in getYearFromItem

XBMC Remote/DetailViewController.m, XBMC Remote/ECSlidingViewController/ECSlidingViewController.m, XBMC Remote/ShowInfoViewController.m
When the anchor is visible (partially displayed screen on the left or right), the anchor always opened to full view once touched. The user would expect that the anchor is snapping back to its position when the anchor is moved less than 50% of the screen width.
This PR does a bit of rework and refinement of the sliding conditions. Now the anchor's behaviour is same as for the fullscreen:
1. Flicking a fully visible screen moves it into an anchor
2. Moving a fully visible screen >50% moves it into an anchor
3. Moving a fully visible screen <50% lets it snap back to full screen
4. Flicking an anchor will switch to full screen
5. Moving an anchor >50% opens it to a full screen
6. Moving an anchor  <50% lets it snap back to the anchor
In addition, the PR removes the obsolete notification …
=> Improvement: Slide behaviour for anchor

XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/500.
The automatic background color for TV station logos shall not be set, if the attempt to load the station logo fails. In this case the default thumb shall be shown without any adaption of the background color (defaults to clear color). Screenshots can be seen in the issue linked above.
Bugfix: Fix potentially wrong background color for default thumbs
=> Bugfix: Fix potentially wrong background color for default thumbs

XBMC Remote/ViewControllerIPad.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/506.
Button presses (repeat and shuffle) in the song details overlay were not recognized on iPad. The overlay window was simply closed.
Bugfix: Fix repeat/shuffle in song details overlay on iPad
=> Bugfix: Fix processing button presses in song details overlay on iPad

XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/520.
The animation can interfere with restoring the active keyboard after e.g. leaving for "Search Wikipedia" and re-entering the search. This results in a crash. Removing the animation resolves this problem.
Bugfix: Fix crash after using "Search Wikipedia" during active search
=> Bugfix: Fix crash after using "Search Wikipedia" during active search

XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/523.
Hide button list when editing the searchbar text field. Avoids issues when attempting to change the mode while a search is active and you do not press keyboard's "Enter". Typically this happens when using an external keyboard or hiding the popup keyboard.
Bugfix: Hide toolbar while active search
=> Bugfix: Hide toolbar while active search

XBMC Remote/ShowInfoViewController.m
The review checker was not called when starting the playback from the info view controller ("Play" or "Resume from"). This PR also triggers the check in this case.
Screenshot:
<a href="https://abload.de/image.php?img=bildschirmfoto2021-12u9j5w.png"><img src="https://abload.de/img/bildschirmfoto2021-12u9j5w.png" /></a>
Improvement: Also check for review when starting playback from ShowInfoVC
=> Improvement: Also check for review when starting playback from ShowInfoVC

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/Kodi Remote-Info.plist, XBMC Remote/ShowInfoViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/299.
The action "Open with VLC" was not working and not enabled. This PR removes the obsolete code.
Maintenance: Remove openWithVLC
=> Maintenance: Remove openWithVLC

XBMC Remote/AppDelegate.h, XBMC Remote/AppDelegate.m, XBMC Remote/MasterViewController.m, XBMC Remote/cellView.xib, XBMC Remote/cellViewIPad.xib, XBMC Remote/cs.lproj/Localizable.strings, XBMC Remote/de.lproj/Localizable.strings, XBMC Remote/en-US.lproj/Localizable.strings, XBMC Remote/en.lproj/Localizable.strings, XBMC Remote/es.lproj/Localizable.strings, XBMC Remote/fr.lproj/Localizable.strings, XBMC Remote/iPad/MenuViewController.m, XBMC Remote/it.lproj/Localizable.strings, XBMC Remote/mainMenu.h, XBMC Remote/mainMenu.m, XBMC Remote/nl.lproj/Localizable.strings, XBMC Remote/pl.lproj/Localizable.strings, XBMC Remote/pt-PT.lproj/Localizable.strings, XBMC Remote/sv.lproj/Localizable.strings, XBMC Remote/tr.lproj/Localizable.strings, XBMC Remote/zh-Hans.lproj/Localizable.strings
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/505.
This PR implements a suggestion coming from a Team Kodi member. The so-called "upper labels" (e.g. "Listen to") above the main menu label (e.g. "MUSIC") are hardly readable and do not add a real value. In addition, these strings are not translating well into German where the common rule is to not directly address the user, but use a passive form (e.g. "Höre deine Musik" would become "Deine Musik hören"). Kodi server also simply shows the icon and label in the main menu.
Changes in this PR:
- Remove upper labels from xib and code
- Alignment of icon and label in the cell
- Same cell height for iPhone and iPad
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2021-11f4j0l.png"><img …
=> Improvement: No upper labels in main menu

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/517.
This PR implements a suggestion by a user to show TV/Radio channel numbers. The code change is pretty simple and straight forward. I keep this as draft as I need to check, if the parameter `"channelnumber"` is available in older APIs as well, and how this looks like when IPTV channels are added.
Screenshots (only shown for TV - All channels, works as well for the lists under channel groups and for Radio):
<a href="https://abload.de/image.php?img=bildschirmfoto2021-12pnkhj.png"><img src="https://abload.de/img/bildschirmfoto2021-12pnkhj.png" /></a>
Improvement: Show TV/Radio channel numbers
=> Improvement: Show TV/Radio channel numbers

XBMC Remote/NowPlaying.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/515.
This PR improves the usability of the the playlist view toolbar. The button to toggle between the playlist and the NowPlaying view was showing an unreadable icon if nothing is playing.
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2021-12qkj5g.png"><img src="https://abload.de/img/bildschirmfoto2021-12qkj5g.png" /></a>
Improvement: Better usability of playlist toggle button
=> Improvement: Better usability of playlist toggle button

XBMC Remote/AppDelegate.m, XBMC Remote/cs.lproj/Localizable.strings, XBMC Remote/de.lproj/Localizable.strings, XBMC Remote/en-US.lproj/Localizable.strings, XBMC Remote/en.lproj/Localizable.strings, XBMC Remote/es.lproj/Localizable.strings, XBMC Remote/fr.lproj/Localizable.strings, XBMC Remote/it.lproj/Localizable.strings, XBMC Remote/nl.lproj/Localizable.strings, XBMC Remote/pl.lproj/Localizable.strings, XBMC Remote/pt-PT.lproj/Localizable.strings, XBMC Remote/sv.lproj/Localizable.strings, XBMC Remote/tr.lproj/Localizable.strings, XBMC Remote/zh-Hans.lproj/Localizable.strings
This PR removes the unused string "Stream to iPhone" from localized strings.
Maintenance: Remove unused string "Stream to iPhone"
=> Maintenance: Remove unused string "Stream to iPhone"

XBMC Remote/DetailViewController.m, XBMC Remote/SDWebImage/UIImageView+WebCache.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3076909#pid3076909)
Instead of calling the method `applyRoundedEdgesImage` which checks the App settings, the method `roundedCornerImage` which directly applies the rounded corner was called. In effect default thumbs and thumbs in the info screen were always shown with rounded corners.
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2021-12dzjyn.png"><img src="https://abload.de/img/bildschirmfoto2021-12dzjyn.png" /></a>
Bugfix: Applied unwanted rounded corners
=> Bugfix: Applied unwanted rounded corners

XBMC Remote/AppDelegate.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/537.
This PR fixes a regression caused by https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/518. The channel guide was not showing anymore as the configuration for JSON commands uses the key `"row6"` to load channel details which require they object `"channelid"`.  As a fix this PR moves the object `"channelnumber"` to the otherwise unused key "`row10"`. As a result the details can be loaded again, and also the channel numbers are still available.
Bugfix: Channel guide not showing up
=> Bugfix: Channel guide not showing up

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m
Fixes a issues when searching for albums of an artist for a certain music role. Before this change only "artist" music roles where working properly. All other music roles where resulting in an empty album list in most cases. In addition, the artist's for roles are now _always_ taken from the pool of _all_ artists and not only album artists (if this should be configured in Kodi). This way you can always see Composers, even if they are not an album artist.
The code changes itself ensure to add the parameter `"albumartistsonly": "NO"` and to retain `"albumartistsonly"` and `"combinedFilter"` in the parameter set. This lets the JSON request for the artists and albums use the correct filter for the music roles and artists.
Bugfix: Empty list of albums for most music roles
Improvement: Music …
=> Bugfix: Empty list of albums for most music roles

XBMC Remote/DetailViewController.m
This PR improves the readability of the section header when sorting for `playcount`. Use `NSNumberFormatterDecimalStyle` to show a decimal number instead of spelling out the number (e.g. "37" instead of "thirty-seven"). This is especially helpful for music files which have been played a lot.
Screenshot:
<a href="https://abload.de/image.php?img=bildschirmfoto2021-12tpknb.png"><img src="https://abload.de/img/bildschirmfoto2021-12tpknb.png" /></a>
Improvement: Better readability of section header when sorting for playcount
=> Improvement: Better readability of section header when sorting for playcount

XBMC Remote/MasterViewController.m, XBMC Remote/iPad/MenuViewController.m
This PR improves the visualization of the selected main menu item. Dark icons are shown when not highlighted. The icon turns bright when highlighted. This is aligned with the visualization of the Kodi 19.x main menu.
Screenshot (left = before, middle = after, right = Kodi 19.x):
<a href="https://abload.de/image.php?img=bildschirmfoto2021-12p6koy.png"><img src="https://abload.de/img/bildschirmfoto2021-12p6koy.png" /></a>
Improvement: Highlight selected main menu icon
=> Improvement: Highlight selected main menu icon

XBMC Remote/NowPlaying.m, XBMC Remote/NowPlaying.xib, XBMC Remote/cs.lproj/Localizable.strings, XBMC Remote/de.lproj/Localizable.strings, XBMC Remote/en-US.lproj/Localizable.strings, XBMC Remote/en.lproj/Localizable.strings, XBMC Remote/es.lproj/Localizable.strings, XBMC Remote/fr.lproj/Localizable.strings, XBMC Remote/it.lproj/Localizable.strings, XBMC Remote/nl.lproj/Localizable.strings, XBMC Remote/pl.lproj/Localizable.strings, XBMC Remote/pt-PT.lproj/Localizable.strings, XBMC Remote/sv.lproj/Localizable.strings, XBMC Remote/tr.lproj/Localizable.strings, XBMC Remote/zh-Hans.lproj/Localizable.strings
Adresses suggestions from [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3076638#pid3076638).
1. Remove "Nothing is playing" text and translations
2. No transparency for Kodi icon on iPad's NowPlaying screen for better readability (same as on iPhone)
3. More space between icon and "No items found" for better readability
Screenshots: https://abload.de/img/bildschirmfoto2021-12cnklx.png
Improvement: Better readability of "No items found" in playlist
Improvement: Remove obsolete text "Nothing is playing"
=> Improvements around NowPlaying screen

XBMC Remote/HostManagementViewController.h, XBMC Remote/HostManagementViewController.m, XBMC Remote/HostManagementViewController.xib, XBMC Remote/playlistCellView.xib
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/389.
This PR implements a detailed server info, comparable to Kodi's System Info. The current state is shown in the screenshot below. More details can be shown, if this should be required. I am avoiding to add eye-candy like bars for memory consumption or the CPU load as I would need to parse Kodi's responses, and I am already seeing different string formats between my main test systems 17.6 and 19.3.
Screenshots (Kodi 19.3 on a VM):
<a href="https://abload.de/image.php?img=bildschirmfoto2021-121tk7s.png"><img src="https://abload.de/img/bildschirmfoto2021-121tk7s.png" /></a>
Feature: Server info
=> Feature: Server info

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m, XBMC Remote/NowPlaying.xib, XBMC Remote/de.lproj/Localizable.strings, XBMC Remote/en.lproj/Localizable.strings
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/477.
This PR has several changes around `NowPlaying`, with a focus to the playlists and especially picture playlist.
- Support "Pictures" playlists (deleting, but no editing supported)
- Support queueing pictures into playlist ("Queue", but no "Queue after current" supported)
- Use icons instead of text items for playlist's `UISegmentedControl`
- Right-align `"Edit"` button in playlist's segment control
- Remove unneeded code, magic numbers and avoid code duplication
Screenshots: https://abload.de/img/bildschirmfoto2021-1215jis.png
Bugfix: Show playback time and duration after running a pictures playlist
Bugfix: Fix German translation for playlist deletion popup
Improvement: Support "Pictures" playlist incl. layout update of …
=> Maintenance: Rework playlist

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m
This PR applies some rework to the visibility of sections/index in combination with sort mode. In general it is desired to only show sections/index if: 
a) The list has more than 100 entries
b) The user applied a different sort (method or order) than default
The code changes fix rule b) for Music Artists which was broken due to a missing configuration. In addition, this PR refactors building of sections to avoid code duplication and allows section/index for few more submenus which tend to have >100 list items.
Screenshots:
https://abload.de/img/bildschirmfoto2022-01ozkcn.png (remove unwanted sections)
https://abload.de/img/bildschirmfoto2022-018djcz.png (section/index for submenus if >100 list items)
Bugfix: Align visibility of sections in artists list with other lists
Bugfix: Do not show …
=> Rework: Sort / section behaviour

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/ShowInfoViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/430.
With Kodi Nexus (API 12.7.0) the handling of recordings was improved. This allows to add `recordingid` to `Playlist.Insert` and `Playlist.Add`. This fixes multiple problems:
- Now `playcount` increases when recording playback is triggered from the App
- The correct recording name is shown in the UI (before the file name was shown)
- Icon art and plot is provided when asking for "Playlist.GetItems"
With this the App now again supports sorting by playcount. In addition, the NowPlaying screen and the Playlist will use icon art (typically the broadcast station logo).
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-01owj9x.png"><img src="https://abload.de/img/bildschirmfoto2022-01owj9x.png" /></a>
<a …
=> Improvements around recordings (needs Kodi Nexus)

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m
- Fix sort by `"track"` and by `"playcount"`. Both sort methods shall result in a section per count. Regression of [#541](https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/541).
- Use `"Play count"` instead  of `"Playcount"` for the action sheet. This will correctly pick the localized translations.
Bugfix: Fix sort by playcount & track (regression of PR#541)
Bugfix: Fix localized string "Play count" for recordings (issue of PR#543)
=> Bugfix: Fix sort issues caused by latest features/reworks

XBMC Remote/Utilities.m
Fixes a regression caused by https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/535. The iPhone uses the top most cell of the main menu as connection status. This should not be faded/unfaded.
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-0111kv6.png"><img src="https://abload.de/img/bildschirmfoto2022-0111kv6.png" /></a>
Bugfix: Do not fade iPhone connection status in main menu (regression of PR#535)
=> Bugfix: Do not fade iPhone connection status in main menu

XBMC Remote/AppDelegate.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/554.
Use the correct width for the thumbs fixes the aspect ratio.
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-01cvjqm.png"><img src="https://abload.de/img/bildschirmfoto2022-01cvjqm.png" /></a>
Bugfix: Use correct aspect ratio for Music Playlist thumbs
=> Bugfix: Use correct aspect ratio for Music Playlist thumbs

XBMC Remote/DetailViewController.m
This PR implements a fix/improvement for a issue described in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3079674#pid3079674). The keyboard which is shown during search should be hidden when swiping back.
Screenshots (after swiping back from a search for music albums):
<a href="https://abload.de/image.php?img=bildschirmfoto2022-01ccj6z.png"><img src="https://abload.de/img/bildschirmfoto2022-01ccj6z.png" /></a>
Improvement: Hide the keyboard when swiping back
=> Improvement: Hide the keyboard when swiping back

XBMC Remote/RightMenuViewController.m
For iPhones with enough screen height to show the volume control on the remote screen itself, the volume control can be removed from right panel. All items which do not need to be shown on the right pane are configured in `itemShownInRemoteToolBar`.
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-01cfklr.png"><img src="https://abload.de/img/bildschirmfoto2022-01cfklr.png" /></a>
Improvement: Remove doubled volume control from iPhone
=> Improvement: Remove doubled volume control from remote screen's right panel

XBMC Remote/DetailViewController.m
Fixes a regression of https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/541 and improves the information shown in the navigation title.
The App uses the flag `enableSection` to determine whether a submenu's result list shall have sections or not.  This flag was also misused to decide, if a navigation title shall show the amount of results for a certain submenu -- e.g. "Albums (21)" -- or not. Since the latest changes to allow sections for more submenus this caused the problem of showing wrong navigation titles.
This PR reworks the logic to not misuse `enableSection` anymore and always show the applied filter and amount of results in the navigation title. This automatically brings additional value for several submenus. A required exception is the album view which must only show the …
=> Bugfix: Fix wrong navigation titles

XBMC Remote/MasterViewController.m
Fixes an issue where the main menu was overlapping with the status bar on older iPhones with iOS 10. The problem is a regression of https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/535, in which a hardcoded layout calculation was removed. This had no effect on iOS 11 or newer but broke older setups (in this case iPhone 5 with iOS 10). The fix does now correct the calculation to take into account the proper height of the status bar to set the frame dimension of the main menu view.
Screenshot:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-01eekej.png"><img src="https://abload.de/img/bildschirmfoto2022-01eekej.png" /></a>
Bugfix: Correct the frame dimension for the main menu
=> Bugfix: Correct the frame dimension for the main menu

XBMC Remote/AppDelegate.m, XBMC Remote/RightMenuViewController.m
On iPhone there are two screens which have a volume bar: "remote" and "embedded remote" (reachable only from NowPlaying). For the "remote" the visibility is handled by `itemShownInRemoteToolBar`. For the "embedded remote" the volume bar always needs to be shown, this is now checked by `showEmbeddedVolumeBar`. This also works for iPhone which have a small screens (volume bar shown on "embedded remote" and the right panel of the "remote").
Screenshots:
https://abload.de/img/bildschirmfoto2022-01wlj8p.png
Bugfix: Volume bar must be visible on embedded screen
=> Bugfix: Volume bar must be visible on embedded screen

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m
This PR provides two bugfixes:
1. Show correct title in fullscreen album view. This was caused by not correctly handling the album view in modal view mode.
2. Show correct albumartist in album view. This was simply never implemented. Now the App requests "albumartist" from Kodi and displays this in the album view.
Screenshots:
https://abload.de/img/bildschirmfoto2022-01fekr6.png (before)
https://abload.de/img/bildschirmfoto2022-01iij51.png (after)
Bugfix: Show correct title in fullscreen album view
Bugfix: Show correct albumartist in album view
=> Bugfix: Show correct albumview content 

XBMC Remote/NowPlaying.m
This PR fixes the runtime in the movie detail screen when opening it via long pressing a movie item in the playlist. Before this change the runtime was shown as a number representing the seconds (e.g. "8100"). Now it will properly show the minutes (e.g. "135 min").
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-013zjbn.png"><img src="https://abload.de/img/bildschirmfoto2022-013zjbn.png" /></a>
Bugfix: Fix runtime when showing movie details from playlist item
=> Bugfix: Fix runtime when showing movie details from playlist item

XBMC Remote/NowPlaying.m
This PR adds more information for music videos and recordings in the playlist view. 
Remark: The additional channel name for recordings is only supported from Kodi 20.0 on.
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-01b0k73.png"><img src="https://abload.de/img/bildschirmfoto2022-01b0k73.png" /></a>
Improvement: More information for music videos and recordings in playlist
=> Improvement: More information for music videos and recordings in playlist

XBMC Remote/NowPlaying.m, XBMC Remote/cs.lproj/Localizable.strings, XBMC Remote/de.lproj/Localizable.strings, XBMC Remote/en-US.lproj/Localizable.strings, XBMC Remote/en.lproj/Localizable.strings, XBMC Remote/es.lproj/Localizable.strings, XBMC Remote/fr.lproj/Localizable.strings, XBMC Remote/it.lproj/Localizable.strings, XBMC Remote/nl.lproj/Localizable.strings, XBMC Remote/pl.lproj/Localizable.strings, XBMC Remote/pt-PT.lproj/Localizable.strings, XBMC Remote/sv.lproj/Localizable.strings, XBMC Remote/tr.lproj/Localizable.strings, XBMC Remote/zh-Hans.lproj/Localizable.strings
Based on a discussion in https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/559 this PR replaces a constructed message with the complete string. This resolves issues with the localization for several languages. The translations were checked and adapted with help of Google Translator.
Maintenance: Replace constructed message with complete strings
=> Maintenance: Replace constructed message with complete strings

XBMC Remote/NowPlaying.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/iPad/MenuViewController.m
When entering item details from outside the menu structure on iPad (e.g. long press on an item in a playlist) any active submenu is overwritten with this detail screen. The App had an implementation to select the related main menu (e.g. "MUSIC" when showing the album details). Since the support for user configurable main menu the wrong main menu was highlighted.
Instead of this automatic selection it is recommended to just _deselect_ the current main menu as users can now enable any desired submenu again with a single click. Before this PR users always needed to first deselect and then select again (two clicks).
Improvement: Deselect main menu on iPad when entering details via playlist
=> Improvement: Deselect main menu on iPad when entering details via playlist

XBMC Remote/DetailViewController.m
The search needs to be deactivated before updating the data after a "Pull-To-Sync" was triggered. Without this the search bar will be locked up and only re-entering the main menu (e.g. MOVIES) will resolve this.
This PR resolves an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3081376#pid3081376). When having an active search and then triggering "pull-to-sync", the search bar is locking up and shown always on top. You cannot end the search or start any new search until you re-enter from the main menu again. To fix this the active search is explicitly stopped when "pull-to-sync" was performed by the user.
Bugfix: Avoid lockup of an active search after "Pull-To-Sync"
=> Bugfix: Avoid lockup of an active search after "Pull-To-Sync"

XBMC Remote/NowPlaying.m
Fix a minor glitch reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3081481#pid3081481). The "Party" button is sliding in and out with an animation. It needs to be hidden as well to avoid unveiling when swiping a video or picture playlist to the right.
Screenshot: https://abload.de/img/bildschirmfoto2022-01r4j43.png
Bugfix: Hide Partybutton while swiping non-Music playlist
=> Bugfix: Hide Partybutton swiping non-Music playlist

XBMC Remote/AppDelegate.h, XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.h, XBMC Remote/GlobalData.h, XBMC Remote/KenBurns/JBKenBurnsView.h, XBMC Remote/MessagesView.h, XBMC Remote/MoreItemsViewController.h, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.h, XBMC Remote/SettingsValuesViewController.h, XBMC Remote/ShowInfoViewController.h, XBMC Remote/ViewControllerIPad.h, XBMC Remote/VolumeSliderView.h, XBMC Remote/customButton.h, XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSARCHelpers.h, XBMC Remote/de.lproj/Localizable.strings, XBMC Remote/en-US.lproj/Localizable.strings, XBMC Remote/en.lproj/Localizable.strings, XBMC Remote/iPad/MenuViewController.h, XBMC Remote/iPad/StackScrollViewController.h, XBMC Remote/mainMenu.h
This PR implements the longpress functionality for music videos and recordings in the playlist. This is consistent with the longpress functionality for music, movies and TV shows.
Remark: The new functionality for recordings will only work with Kodi 20.0 and later.
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-01fzjpk.png"><img src="https://abload.de/img/bildschirmfoto2022-01fzjpk.png" /></a>
Feature: Playlist longpress details for music videos and recordings
=> Feature: Playlist longpress details for music videos and recordings

XBMC Remote/HostManagementViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/574.
Add an error message to the server info screen while the App is not connected to a Kodi server. The error message is taken from the JSON response.
Screenshot:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-01fmjs2.png"><img src="https://abload.de/img/bildschirmfoto2022-01fmjs2.png" /></a>
Improvement: Show error message in server info view while disconnected
=> Improvement: Show error message in server info view while disconnected

XBMC Remote/DetailViewController.m
Fixes an issue reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3084017#pid3084017). An active keyboard was hidden when swiping left towards the main menu. When bringing the view back the keyboard shall be brought up again.
Bugfix: Show the keyboard after hiding it when moving to main menu (iPhone)
=> Bugfix: Show the keyboard after hiding it when moving to main menu (iPhone)

XBMC Remote/NowPlaying.m
Fixes an issue reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3084204#pid3084204). The NowPlaying view shall start with hidden ProgressSlider (initialized in `viewDidLoad`). It will be unhidden when playback is detected. This avoids to have a visible ProgressSlider for a fraction of a second before "Nothing is playing" is detected.
Bugfix: Start NowPlaying with hidden ProgressSlider
=> Bugfix: Hide ProgressSlider in viewDidLoad

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/de.lproj/Localizable.strings, XBMC Remote/en-US.lproj/Localizable.strings, XBMC Remote/en.lproj/Localizable.strings
This PR adds the possibility to show movie set details, incl. plot, art and fanart.
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-01lujso.png"><img src="https://abload.de/img/bildschirmfoto2022-01lujso.png" /></a>
Feature: Add details for movie sets
=> Feature: Movieset details

XBMC Remote/ShowInfoViewController.m
Fixes an observation from [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3083990#pid3083990).
Three options for heading and text are supported, depending on availability of director and year:
- Directed by (Year)
- Directed by
- Year
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-01jlk7w.png"><img src="https://abload.de/img/bildschirmfoto2022-01jlk7w.png" /></a>
Improvement: Tailor heading and text for Director/Year
=> Improvement: Tailor heading and text for Director/Year

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/544.
This PR adds view options for TV Shows like for other views.
- Support grid view and fullscreen (iPad only)
- Add specific `"banner"` key instead of overwriting `"thumbnail"` to allow loading both in parallel
- Needs re-sync of data to show correct thumbs when toggling the views
Screenshots:
https://abload.de/img/bildschirmfoto2022-01xhkbm.png (iPhone)
https://abload.de/img/bildschirmfoto2022-01e1jic.png (iPad fullscreen)
Feature: Add view options for TV Shows
=> Feature: Add view options for TV Shows

XBMC Remote/DetailViewController.m
When there are no results for movie sets we need to call `showNoResultsFound` to end the animation and show "No results found". In addition change a few spaces and brackets for better readability.
Bugfix: Show "No results found" for movie sets
=> Bugfix: Show "No results found" for movie sets

XBMC Remote/NowPlaying.m
Fixes a race condition which caused the in-playlist progress bar not to be shown under certain conditions. Setting `lastSelected = SELECTED_NONE` will now force any running playback to select the related row and show the progress bar. Use case: Show the Music Playlist in the App, and then trigger playback of a movie via Kodi.
In addition, this PR removes the inner checks for `(playlistPosition > 0)` and `(lastSelected != playlistPosition)`. Both conditions were already checked in the outer condition.
Bugfix: Playlist possibly not highlighting played item
=> Bugfix: Playlist possibly not highlighting played item

XBMC Remote/DetailViewController.m
This fixes a visible index which is not related to the "more" menu content when entering "more" menu from a grid view with index. The issue was reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3086045#pid3086045).
Bugfix: Hide index when entering "more" tab
=> Hide index when entering "more" tab

XBMC Remote/Settings.bundle/Root.plist, XBMC Remote/Settings.bundle/de.lproj/Root.strings, XBMC Remote/Settings.bundle/en-us.lproj/Root.strings, XBMC Remote/Settings.bundle/en.lproj/Root.strings, XBMC Remote/Settings.bundle/pl.lproj/Root.strings
This change was missed during rebasing. The PR simply adds the option to also select the recently "Global Search" to the new app setting "Start in view".
Feature: Add Global Search as option for "Start in view"
=> Add Global Search as option for "Start in view"

XBMC Remote/AppInfoViewController.m, XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m, XBMC Remote/NSString+MD5/NSString+MD5.h, XBMC Remote/NSString+MD5/NSString+MD5.m, XBMC Remote/SDWebImage/SDImageCache.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/customButton.m
This change ensures the cache is refreshed when a new app version is installed. It does this by adding the App version to the calculation of the MD5 hash for each cache file.
**Pro:**
The benefit is that there is no inconsistency between the cached data format and the expected one. This avoids glitches when presenting the results. In the past users which observed such glitches were asked to re-synchronize the data manually via the pull-down menu.
**Con:**
The downside is a re-sync is done for the first time entering a certain menu or view. This is a performance impact for the very first time.
Improvement: Force cache updates for new App versions to ensure data consistency
Improvement: Use SHA256 instead of MD5 for the hash calculation
=> Let MD5 hash for cache also consider App version

XBMC Remote/DetailViewController.m, XBMC Remote/RemoteController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/iPad/StackScrollViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/604.
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/606.
1. Out-of-bounds crash in iPad's `StackViewController`. In 1.10 test builds this could be triggered by pressing remote's settings twice.
2. Crash of `componentsWithURL:resolvingAgainstBaseURL:` when handing `url == nil`.
3. Crash of `checkDiskCache` after wakeup.
3. Adding a "close" button to the iPad's remote toolbar to allow closing the modal view.
Bugfix: Fix crash when loading movie details (processing trailer URL)
Bugfix: Fix crash when pressing remote setting twice on iPad (1.10 test builds only)
Bugfix: Fix possible UI lock up when entering remote on iPad and iOS 13 and earlier (1.10 test builds only)
=> Bugfix: Fix crashes

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.m, XBMC Remote/MasterViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.m, XBMC Remote/ViewControllerIPad.m, XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/589 and closes most topics addressed in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/570 (which needs more changes in `NowPlaying`). 
Following changes are done:
- Use `for (... in ...)` instead of `for (int = 0; ...)`
- Do not cast type `id` to `(NSNull*)`
- Use `NSUserDefaults` methods `boolForKey:`, `integerForKey:`, `setBool:forKey:` and `setInteger:forKey:`
- Use `longValue` when dealing with database IDs, window IDs and JSON IDs
- Use literals in some more cases
- Some new lines removed and added where appropriate
Maintenance: Coding style changes
=> Maintenance: Coding style changes

XBMC Remote/ShowInfoViewController.h, XBMC Remote/ShowInfoViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/607.
Since App version 1.9 the top bar item in the detail view were not shown under iOS 11 and earlier. This PR adds a special treatment for these old versions. In addition, it removes the possibility to enter a blocking state in the UI when selecting the so-called "extraButton" in detail view while in fullscreen mode.
Bugfix: Fix missing top bar items in detail view for iOS 11 and earlier
Bugfix: Fix possible UI lock up in iPad fullscreen for iOS 13 and earlier
=> Bugfix: Special handling for old iOS

XBMC Remote/Utilities.m
The review popup counter will increase faster in app versions after 1.9. Therefore use a less aggressive condition to show the app review popup. Review requests come after 50/150/300 attempts, followed by each 300th attempt.
Maintenance: Less aggressive trigger for the app review popup
=> Maintenance: Less aggressive trigger for the app review popup

XBMC Remote/Settings.bundle/Root.plist, XBMC Remote/Settings.bundle/de.lproj/Root.strings, XBMC Remote/Settings.bundle/en-us.lproj/Root.strings, XBMC Remote/Settings.bundle/en.lproj/Root.strings, XBMC Remote/ShowInfoViewController.m
If "fanart" is missing, the user can now allow a fallback to "art" (typically the thumbnail). Making this an option as users might not have "fanart" intentionally.
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-01utjp0.png"><img src="https://abload.de/img/bildschirmfoto2022-01utjp0.png" /></a>
Feature: Add an app setting to allow fanart to fall back to art
=> Feature: Add an app setting to allow fanart-fallback to art

XBMC Remote/Settings.bundle/Root.plist, XBMC Remote/Settings.bundle/de.lproj/Root.strings, XBMC Remote/Settings.bundle/en.lproj/Root.strings, XBMC Remote/tcpJSONRPC.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/602.
This PR adds the option to let the App send Wake-On-LAN when attempting to connect a server. The option is inactive per default.
Feature: Automatic Wake-On-LAN on connection attempt
=> Feature: Automatic Wake-On-LAN on connection attempt

XBMC Remote/MasterViewController.m, XBMC Remote/Settings.bundle/Root.plist, XBMC Remote/Settings.bundle/de.lproj/Root.strings, XBMC Remote/Settings.bundle/en-us.lproj/Root.strings, XBMC Remote/Settings.bundle/en.lproj/Root.strings, XBMC Remote/iPad/MenuViewController.m
To align the app look&feel with Kodi's default UI the main menu entries are not shown in capital letters anymore. This also allows to simplify the app settings related to the active main menu items. Instead of "Show MUSIC" it will only display "Music" left of the toggle button. This simplifies the translations and also avoid inconsistencies, if the drop-down list for the default view was not matching the entries listed in the main menu settings. This could happen, if translations were not finished.
The second change is re-grouping the app settings into meaningful sections: General, Cache Settings, Interface and Main Menu Items. Before, the grouping was a bit mixed up.
Screenshots:
https://abload.de/img/simulatorscreenshot-i3yjua.png (main menu) …
=> Improvement: Rework of main menu and app settings

XBMC Remote/AppDelegate.m, XBMC Remote/Settings.bundle/de.lproj/Root.strings, XBMC Remote/ViewControllerIPad.m, XBMC Remote/cs.lproj/Localizable.strings, XBMC Remote/de.lproj/Localizable.strings, XBMC Remote/en-US.lproj/Localizable.strings, XBMC Remote/en.lproj/Localizable.strings, XBMC Remote/es.lproj/Localizable.strings, XBMC Remote/fr.lproj/Localizable.strings, XBMC Remote/it.lproj/Localizable.strings, XBMC Remote/nl.lproj/Localizable.strings, XBMC Remote/pl.lproj/Localizable.strings, XBMC Remote/pt-PT.lproj/Localizable.strings, XBMC Remote/sv.lproj/Localizable.strings, XBMC Remote/tr.lproj/Localizable.strings, XBMC Remote/zh-Hans.lproj/Localizable.strings
Different naming conventions are used for WOL: "Wake On Lan", "Wake-On-LAN", "Wake on LAN". This PR unifies the naming to "Wake on LAN".
Maintenance: Unify WOL naming to "Wake on LAN"
=> Maintenance: Unify WOL naming to "Wake on LAN"

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/HostViewController.m, XBMC Remote/KenBurns/JBKenBurnsView.m, XBMC Remote/MessagesView.m, XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.m, XBMC Remote/SettingsValuesViewController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/ViewControllerIPad.m, XBMC Remote/customButton.m, XBMC Remote/iPad/StackScrollViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/599.
This PR has four main sections:
1. Prepare migration of `NSKeyedArchiver` methods
The method `unarchiveObjectWithFile` and `archiveRootObject:toFile:` are deprecated since iOS 11. This PR refactors reading/writing persistent data and already prepares the migration to the newly introduced `unarchivedObjectOfClasses` and `archivedDataWithRootObject:requiringSecureCoding:error:`. 
2. Move duplicate animation related code to Utilities
This allows to remove code duplication and unneeded code, as well as prepares for the next third step.
3. Migrate to block-based animation
All parameters and options were taken over into the block-based animation.
4. Optimizations and bugfixes around animation in `NowPlaying`
The code was …
=> Maintenance: Prepare migration of NSKeyedArchiver methods and move to block-based animation

XBMC Remote/iPad/MenuViewController.m
The selection of menu A was not working in the following sequence: menu A > NowPlaying > menu A. Root cause was the local variable `lastSelected` not being updated when entering NowPlaying.
Bugfix: Fix iPad main menu selection
=> Bugfix: Fix iPad main menu selection

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.m, XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m, XBMC Remote/mainMenu.h, XBMC Remote/mainMenu.m
The `mainLabel` might be changed when entering a next level while browsing (e.g. "Music" > "Genre" > "Pop" > "Genesis"). But in case it is not changed the navigation bar title shall show the parameter set's label (e.g. "Albums"). To achieve this we save the initial `mainLabel` as `rootLabel`. If `mainLabel` changed, show it. If not, show `parameters["label"]`.
Bugfix: Fix wrong navbar titles when browsing menus
=> Bugfix: Fix wrong navbar titles when browsing menus

XBMC Remote/ViewControllerIPad.m
When enabling the remote from the iPad's bottom toolbar we need to explicitly send the "StackScrollOnScreen" notification to move the NowPlaying view under the rootView.
Bugfix: Fix visible progress bar on iPad after enabling remote from bottom toolbar
=> Bugfix: Fix visible progress bar on iPad after enabling remote from bottom toolbar

XBMC Remote/DetailViewController.m, XBMC Remote/ShowInfoViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/629.
Regression of build 1.10-b7. Fix is to use `longValue` for correct comparison.
Bugfix: Fix start/stop recording from channel guide
=> Bugfix: Fix start/stop recording from channel guide

XBMC Remote/en.lproj/Localizable.strings
Use "Now Playing" instead of "Now playing".
Bugfix: Fix writing of "Now Playing" in main menu for en and en-US
=> Bugfix: Fix writing of "Now Playing" in main menu

XBMC Remote/AppDelegate.h, XBMC Remote/RightMenuViewController.m, XBMC Remote/ViewControllerIPad.m, XBMC Remote/tcpJSONRPC.m
Due to a typo the port 0 was used for auto-WOL instead of the desired port 9.
Bugfix: Use correct port for auto-WOL
=> Bugfix: Use correct port for auto-WOL

XBMC Remote/HostViewController.h, XBMC Remote/HostViewController.m
To get the MAC address we need to wait for the result of a ping which is done via `NSURLSessionDataTask`. For this we need to implement a delegate handler and use a dedicated `NSURLSession` instead of `sharedSession`.
This function broke already with 1.6.2 which was never reported as broken -- most like because many users either keep using the old setups or entered the MAC address manually.
Bugfix: Fix reading MAC address during "Find Kodi"
=> Bugfix: Fix getting MAC address

XBMC Remote/Utilities.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/649.
When handling Kodi server settings the key `"year"` is mis-used for the type of custom button created. The allowed values are `"boolean"` (on/off toggle), `"integer"` (indexed list or a value) and `"list"` (named list items). The missing special treatment broke on/off toggle and indexed list selection.
Bugfix: Fix creation of custom buttons
=> Bugfix: Fix creation of custom buttons

XBMC Remote/AppDelegate.m
Define the "label" key for "Global Search" which is used for the navigation title bar.
Bugfix: Fix Global Search navigation bar title
=> Bugfix: Fix Global Search navigation bar title

XBMC Remote/SettingsValuesViewController.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3092438#pid3092438).
For the setting type "list" a slider is used for the visualization. Therefor use the same (still hardcoded) `cellHeight` as for "spinner" which also is visualized a slider.
<a href="https://abload.de/image.php?img=bildschirmfoto2022-03irj8h.png"><img src="https://abload.de/img/bildschirmfoto2022-03irj8h.png" /></a>
Bugfix: Fix layout for slider-type Kodi setting
=> Bugfix: Fix layout for Kodi settings layout (type = "list")

XBMC Remote/Utilities.m
Since introduction of `unarchivedObjectOfClass` #609 in combination with the unspecific `[NSObject class]` a huge amount of runtime warnings is thrown which impacts the performance of reading cache data. The real fix is to specify all classes explicitly. To not risk the 1.10.1 bugfix version for now `unarchivedObjectOfClass` is rolled back (partial revert of 01bbb1d).
The real fix will come via https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/640.
Hotfix: Solve performance problem when reading cached data
=> Hotfix: Solve performance problem with unarchivedObjectOfClass

XBMC Remote/HostManagementViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/655.
Ensure `methodResult` is of class NSDictionary before accessing it. In other case throw an error message.
Bugfix: Avoid potential crash when showing server info
=> Bugfix: Avoid potential crash when showing server info

XBMC Remote/ShowInfoViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/655.
Avoid division by 0 and `resumePointPercentage` becoming `+Inf` as this crashes in `NSJSONSerialization dataWithJSONObject:options:error:` when handing over `+Inf` or `NaN` over as a `NSNumber`.
Bugfix: Fix potential crash when resuming
=> Bugfix: Fix potential crash when resuming

XBMC Remote/RemoteController.h, XBMC Remote/RemoteController.m, XBMC Remote/RemoteController.xib
When migrating to block based animation unhiding the label was missed. Now the label is unhidden by default, but with an alpha of 0. The animation is now simply setting the alpha values and does not need a timer anymore.
Screenshot: 
<a href="https://abload.de/image.php?img=bildschirmfoto2022-04h1jvg.png"><img src="https://abload.de/img/bildschirmfoto2022-04h1jvg.png" /></a>
Bugfix: Fix missing notification of selected or missing subtitle and audio stream
=> Fix notification of selected or missing subtitle and audio stream

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/411.
To fix the issue with the padding above new sections the new iOS 15 property `sectionHeaderTopPadding` needs to be set. See https://developer.apple.com/forums/thread/683980.
For the second issue with the navigation bar I do not have a fully satisfying solution yet.
What I want: A translucent navigation bar which blurs the underlying view.
What I got until now: A non-translucent, non-blurred navigation bar background.
Screenshots: https://abload.de/img/bildschirmfoto2021-10atklq.png
Maintenance: iOS 15 and XCode 13 migration
=> Maintenance: iOS 15 migration

XBMC Remote/NowPlaying.m
- Avoid out-of-bounds access in `moveRowAtIndexPath`
- Ensure dealing with proper `NSArray` type before accessing the variable
Bugfix: Fix crashes reported via AppStore
=> Bugfix: Fix crashes reported via AppStore

XBMC Remote/DetailViewController.m
Crash reports from AppStore point to few cases (1.9 and later) of crashes inside `getItemFromIndexPath`. These were caused by out-of-bounds access to `filteredListContent`. In addition, change some mutable variables to non-mutable as this is not required.
Bugfix: Fix potential crash when selecting item from search list
=> Bugfix: Fix potential crash when selecting item from search list

XBMC Remote/DetailViewController.m, XBMC Remote/InitialSlidingViewController.m, XBMC Remote/Kodi Remote-Info.plist, XBMC Remote/ViewControllerIPad.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/673.
Status bar color is set to `UIStatusBarStyleLightContent` application wide. Tested on iOS 15.2 and 14.5 simulators with Xcode 13.2.1 builds.
Bugfix: Correct handling of status bar color (Xcode 13 and iOS 15)
=> Bugfix: Correct handling of status bar color (Xcode 13 and iOS 15)

XBMC Remote/RightMenuViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/672.
`cell.contentView addSubview:` needs to be called outside of the singleton condition. This seems to be a change in behaviour only showing when running a Xcode 13 build on iOS 15. 
Bugfix: embedded remote not shown with Xcode 13 and iOS 15
=> Bugfix: embedded remote not shown with Xcode 13 and iOS 15

XBMC Remote/RightMenuViewController.m, XBMC Remote/VolumeSliderView.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/678.
Main amount of reported crashes with App version 1.10.1 is this one. the majority of crashes happen when `cellForRowAtIndexPath` is called from an animation. This PR removes this and simply updates the table list without an animation. In addition the initialization of `VolumeSliderView` is reworked to not overwrite the instance itself.
Bugfix: Fix potential crash in remote's custom button view
=> Bugfix: Fix crash in NSBundle(UINSBundleAdditions) loadNibNamed:owner:options

XBMC Remote/ShowInfoViewController.m
Improve information shared in recording details by showing the year of the recording in addition to day of the week, day and month.
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-03yykb9.png"><img src="https://abload.de/img/bildschirmfoto2022-03yykb9.png" /></a>
Improvement: Show year as part of recording date
=> Improvement: Show year as part of recording date

XBMC Remote/NowPlaying.m
The chosen playlist thumbnail for music videos shall be same as while browsing the database. This can be achieved via showing the `"thubmnail"` key's object and not calling `getThumbnailFromDictionary` to ignore unwanted `"poster"` from `"art"` key.
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-034mkwg.png"><img src="https://abload.de/img/bildschirmfoto2022-034mkwg.png" /></a>
Improvement: Show same music video thumbnails in NowPlaying, playlist and while browsing
=> Improvement: Show same music video thumbnails in NowPlaying, playlist and while browsing

XBMC Remote/SettingsValuesViewController.h, XBMC Remote/SettingsValuesViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/647.
`viewWillDisappear` indicates a swipe-attempt is made. When snapping back from such attempt the animation in `scrollToRowAtIndexPath` should be switched off. This keeps the list representation unchanged after a swipe-attempt, but keep the animation when entering the list for the first time.
Improvement: Do not animate settings list after a swipe-attempt
Bugfix: Correct inset of settings list after a swipe-attempt
=> Improvement: Do not animate settings list after a swipe-attempt

XBMC Remote/DetailViewController.m
Implements a suggestion made in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3092162#pid3092162).
Improves usability for list and grid view. The keyboard will be dismissed when starting to scroll the search result list.
Improvement: Dismiss keyboard on drag
=> Improvement: Dismiss keyboard on drag

XBMC Remote/DetailViewController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
While working on the fix for the crash when resuming I came across a potential division-by-0 and code duplication. This PR addresses both.
Maintenance: Avoid code duplication when calculating elapsed percentage
=> Maintenance: Avoid code duplication when calculating elapsed percentage

XBMC Remote/DetailViewController.m
Action sheets shall be presented from `self.searchController` while a search is active -- change is only needed for iPhone as the same is already done for iPad. This fixes few lists not showing the actions sheet while active search. One case related to adding custom buttons is described in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3091345#pid3091345).
Bugfix: Fix action sheets not showing on few filtered lists
=> Bugfix: Fix action sheets not showing on few filtered lists

XBMC Remote/NowPlaying.m, XBMC Remote/NowPlaying.xib
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/680.
Rework layout of NowPlaying toolbar
- Remove flex spaces from xib
- Add flex spaces for iPhone in obj c
- Add trailing flex space for iPad iOS11+
- Special workaround for iPad with iOS10 and earlier, using fixed spaces with magic width
Bugfix: Remote icon overlaps with skip next button on iPads with iOS10 and earlier
=> Bugfix: Remote icon overlaps with skip next button on iPads with iOS10 and earlier

XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/682.
As per documentation it is not allowed to call `reloadData` between `beginUpdate`/`endUpdate`, which might happen in the current implementation. To avoid this situation we now simply use `reloadData` instead of `beginUpdate`/`endUpdate`. In consequence now the full TV station list is updated each minute, and not only the visible list.
Bugfix: Avoid crash when updating station list
=> Bugfix: Avoid crash when updating station list

XBMC Remote/AppInfoViewController.m, XBMC Remote/AppInfoViewController.xib, XBMC Remote/en.lproj/Localizable.strings
This PR updates the AppInfo text and the screen layout:
- Do not refer to fanart.tv anymore.
- Art is either loaded from Kodi server or from the internet
- Refer to Universal Scraper or scraper add-ons
- Increase width of the text field and let it autoresize
- Limit the upscaling of the logo size
- Remove old text from en/en-US and add new strings to en/en-US
- Adding German translation
Improvement: Updated AppInfo text and layout
=> Improvement: Updated AppInfo text and layout

XBMC Remote/Utilities.m
When loading persistent file in simulator a security warning pops up:
> NSSecureCoding allowed classes list contains [NSObject class], which bypasses security by allowing any Objective-C class to be implicitly decoded. Consider reducing the scope of allowed classes during decoding by listing only the classes you expect to decode, or a more specific base class than NSObject.
`NSKeyedUnarchiver:unarchivedObjectOfClass:fromaData:error:` throws a warning when `[NSObject call]` is used as this covers all object classes. Instead, list the classes which shall be unarchived.
Bugfix: Fix NSSecureCoding warning while unarchiving
Bugfix: Resolve performance issues when reading cached data
=> Fix NSSecureCoding warning while unarchiving

XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/Settings.bundle/Root.plist, XBMC Remote/Settings.bundle/en.lproj/Root.strings, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/545.
The UI colorization follows the average color of images (e.g. thumbnails or artwork). Now let the average color be returning a fixed gray color (which supports LightMode and DarkMode) in case the UI-colorization feature is switched off. As the same method is also used to determine TV logo background a new parameter is introduced to allow ignoring the UI-colorization setting in this case.
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-03fukwc.png"><img src="https://abload.de/img/bildschirmfoto2022-03fukwc.png" /></a>
Feature: Add auto-color setting for UI
=> Feature: Add auto-color setting for UI

XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/ViewControllerIPad.m
This PR mainly reworks the NowPlaying animations for the iPhone's playlist / now playing toggle button. In the course of doing this there are magic numbers and unneeded variables removed, as well as helper functions introduced to avoid code duplication.
Maintenance: Rework NowPlaying
=> Maintenance: Rework NowPlaying

XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.m, XBMC Remote/RightMenuViewController.h, XBMC Remote/RightMenuViewController.m, XBMC Remote/SettingsValuesViewController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/XBMCVirtualKeyboard.m, XBMC Remote/tcpJSONRPC.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/644.
Resolves some auto-layout problems with moving button labels and transparencies. Now the button labels do not change their positions and the safe area stays colored correctly after coming back from Kodi settings menu.
In addition applies coding style changes:
- Use literals
- Unify spaces and new lines
- Remove commented code
- Remove obsolete variables
- ...     
Bugfix: Fix moving button labels and transparency in custom button view
=> Rework RightMenuViewController

XBMC Remote/DetailViewController.m
The parameter set `mutableParameters` is the one sent to the JSON API. Show the correct parameters in the error message.
Bugfix: Show the correct parameters in the error message
=> Bugfix: Show the correct parameters in the error message

XBMC Remote/DetailViewController.m
In [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3105963#pid3105963) a layout issue was reported when showing "no results found". In this screen the searchBar layout was not correct, and in many cases the searchBar was shown as the inset was not set properly.
This PR fixes this by calling `displayData` after preparing the "no results found" message. This set the layout and inset properly. In effect, the now correctly colored searchBar is not shown per default anymore and you need to pull down the menu. This is in line with other views.
Bugfix: Correct layout when showing "no results found"
=> Bugfix: Correct layout when showing "no results found"

XBMC Remote/DetailViewController.m
The App in few cases receives an invalid path to a thumb. For some item types this invalid path was used to overwrite the default thumb, resulting in no default thumb being loaded at all. Solution is to not overwrite the default thumb to allow the default thumb to fall back to a valid one -- e.g. a folder icon.
Screenshots (use case Video add-on "Library Data Provider"):
<a href="https://abload.de/image.php?img=bildschirmfoto2022-0755kmg.png"><img src="https://abload.de/img/bildschirmfoto2022-0755kmg.png" /></a>
Remark: To be able to test with "Library Data Provider" you need to apply a fix to the add-on which is described in [this forum post](https://forum.kodi.tv/showthread.php?tid=369077&pid=3105995#pid3105995).
Bugfix: Ensure proper fallback to default thumb
=> Bugfix: Ensure proper fallback to default thumb

Kodi Remote.xcodeproj/project.pbxproj
Closes #705.
This PR adds support for two more languages which reached a high translation grade:
- ca-es, Catalan (Spain)
- es-mx, Spanish (Mexico)
This PR shall be merged after #704. 
Feature: Support languages ca-es and es-mx
=> Feature: Support languages ca-es and es-mx

XBMC Remote/Utilities.m
From AppStore metrics it is evident that a trigger count of 50 equals 3+ months for the majority of users. We aim to get the feedback 1-2 months after a release. This way there is enough headroom to provide hotfixes and enough time left before a next major release is coming up.
Maintenance: Raise frequency of review popup
=> Maintenance: Raise frequency of review popup

XBMC Remote/Utilities.m
As reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3109151#pid3109151) the clear art and clear logo shown by the Remote App was not matching Kodi UI.
This PR adds preferences for clear art:
1. Select `"albumartist.clearart"` if available. This will kick in only for music and will avoid picking `"artist.clearart"`.
2. Select `"clearart"` if available. This will avoid picking `"set.clearart"` for movies sets.
As default take the first matching object for key containing "clearart".
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-08axdzw.png"><img src="https://abload.de/img/bildschirmfoto2022-08axdzw.png" /></a>
Bugfix: Prefer album artist over artist clear art
Bugfix: Prefer movie over movie set clear art
=> Bugfix: Align clearart behaviour with Kodi UI

XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/713.
For albums with more than `SECTIONS_START_AT` (hard coded to 100) titles the album view used a wrong layout with sections. Simply avoid that album view enters this mode.
Bugfix: Wrong layout for album view with >100 titles
=> Never allow sections for album view

XBMC Remote/ShowInfoViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/712.
Playing movie sets is not supported by Kodi API. Therefore hide the "Play" button in the navbar. Instead, show the "movie set" icon which brings the user back to the movie set list.
<a href="https://abload.de/image.php?img=bildschirmfoto2022-096gelf.png"><img src="https://abload.de/img/bildschirmfoto2022-096gelf.png" /></a>
Improvement: Change navbar buttons for movie sets
=> Improvement: Change navbar buttons for movie sets

XBMC Remote/DetailViewController.m
As reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3106513#pid3106513) it is not possible to mark a complete TV Show as watched/unwatched with Kodi 19.4. Even though the App is sending the valid command
`{"jsonrpc":"2.0","method":"VideoLibrary.SetTVShowDetails","params":{"tvshowid":11, "playcount":1}, "id":2}`
and receives the response `"OK"` from the API, Kodi server does not change the playcount.
This PR implements a solution similar to Chorus Web Interface which simply sets the playcount for each episode of a TV Show. As I am not sure if Kodi server itself should be fixed (in case the JSON command from above should suffice), or if the App shall work around this, I am keeping this draft for now.
Bugfix: Fix marking TV Shows as watched/unwatched
=> Bugfix: Fix marking TV Shows as watched/unwatched

XBMC Remote/DetailViewController.m
Fixes an issue reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3112321#pid3112321).
Also closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/603 with a different solution. Instead of waiting for the last item index, the amount of processed items is counted. This ignores the order.
Improvement: Do not show results for movie sets prematurely
Improvement: Do not end animation before movie sets are loaded
=> Bugfix: Do not end animation before movie sets are loaded

XBMC Remote/DetailViewController.m
Fixes a regression caused by https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/717.
With the introduction of `dispatch_group_notify` for a thread safe processing of 1-movie sets a bug was introduced which causes the some issues with the displayed list of item after sync. In this case some items are shown twice and the also the sections are screwed up. This is only seen when showing lists with sections (typically > 100 items).
To fix this the processing of `dispatch_group_notify` must only run if `ignoreSingleMovieSets` is set.
Screenshot (left = bug, right = fixed):
<a href="https://abload.de/image.php?img=bildschirmfoto2022-101cif2.png"><img src="https://abload.de/img/bildschirmfoto2022-101cif2.png" /></a>
Bugfix: Only process dispatch_group_notify when ignoreSingleMovieSets is …
=> Bugfix: Only process dispatch_group_notify when ignoreSingleMovieSets is enabled

XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/725.
This PR reworks the synchronization processing to keep filters for music, artists and movie sets active -- like done already for movies, music videos, TV shows and episodes. Details are described in the commit messages.
Bugfix: Keep music, artists and movie set filters active after synchronizing
=> Bugfix: Keep music, artists and movie set filters active after synchronizing

XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/571.
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/728.
Clean up initialization and update of `UICollectionView`
- Only initialize grid view in `viewDidLoad` when supported in this view
- Remove obsolete assignment while initializing grid view
- Update `contentInset` when switching to grid view. This fixes a glitch when first synchronizing in list view and then switching to grid view.
Force re-initialization of `UISearchController`
- Remove workaround
- Re-create search controller each time when toggling between grid and list view.
Bugfix: Wrong grid view layout after refresh in list view
Bugfix: Sometime search bar not visible in grid view
=> Bugfixes: Grid view layout glitch and invisible search bar

XBMC Remote/DetailViewController.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3113064#pid3113064) (see the video).
The sync animation was stopped prematurely. This PR simply moves stopping the animation to the end of the load-activity for the global search data. The behaviour is now in line with other data sets loaded.
Bugfix: Show sync animation until global search data is fully loaded
=> Bugfix: Show sync animation until global search data is fully loaded

XBMC Remote/ShowInfoViewController.h, XBMC Remote/ShowInfoViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/729.
This PR reworks the animation inside `ShowDetailsViewController` from scroll view (e.g. move details) to the fanart fullscreen. Main changes are a proper order of the animation steps, ignoring arrow visibility checks while in fullscreen mode and always taking the screen's full size when creating the Ken Burns effect.
The changes improve and fixes multiple issue around the animation.
- Avoids arrows to be toggling on/off during animation 
- Avoids visible up arrow during fullscreen fanart is shown
- Smoother transition to Ken Burns fullscreen effect on iPad
- Avoids empty safe area on iPhone during first seconds of Ken Burns effect
Improvement: Smoother transition to KenBurns fullscreen on iPad
Improvement: No empty safe …
=> Improvement: Rework animation to fullscreen fanart

XBMC Remote/DetailViewController.m
This fixes an issue where the sync animation was hidden behind the navigation bar when in grid view.
Bugfix: Show animation when synchronizing in grid view
=> Bugfix: Show animation when synchronizing in grid view

Kodi Remote.xcodeproj/project.pbxproj, XBMC Remote/DetailViewController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/VersionCheck.h, XBMC Remote/VersionCheck.m
This PR fixes a problem with a version check which was not correctly handling major versions from 13 on, e.g. the check would have failed for version 13.0 to 13.6. Currently there is no JSON API 13, but the code must be future proof.
Bugfix: Correct API version check to support major versions >13
=> Bugfix: Correct API version check to support major versions >13

XBMC Remote/RightMenuViewController.m
Fixes crash when editing the custom button label.
Fixes a crash reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=370085&pid=3114896#pid3114896).
`tableData` element must be `mutable` as this is changed when editing a custom button label.
Bugfix: Fixes crash when editing a custom button label
=> Bugfix: Fixes crash when editing a custom button label

XBMC Remote/NowPlaying.m
Fixes an issue reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3115570#pid3115570).
The `percentage` property reports fluctuating values when pausing playback. This causes the playlist to be reloaded while in partymode. As a fix, use the playtime (position in seconds) instead of the `percentage`. This still allows to detect the start of a new song, which is needed to reload the partymode playlist.
Bugfix: Fix flickering playlist when pausing in partymode
=> Bugfix: Fix flickering playlist when pausing in partymode

XBMC Remote/NowPlaying.m
Ignore moving playlist item to same position. This resolves a flickering playlist when long pressing the "burger" in edit mode.
Bugfix: Fix flickering playlist when long pressing the "burger" in edit mode
=> Bugfix: Fix flickering playlist when long pressing the "burger" in edit mode

XBMC Remote/DetailViewController.m
Set the correct searchbar dimensions also while not being active.
Screenshots: https://abload.de/img/bildschirmfoto2022-10hyf6p.png
Bugfix: Fix searchbar not showing the Cancel button on iPad when not yet active
=> Bugfix: Fix searchbar not showing the Cancel button on iPad when not yet active

XBMC Remote/DetailViewController.m, XBMC Remote/RemoteController.m
Fixes an issue reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3115912#pid3115912).
When in fullscreen mode on iPad it is important to properly leave the fullscreen mode when entering the remote setting ("gear" button). Otherwise an inconsistent UI state is entered.
Bugfix: Leave fullscreen on iPad when entering remote settings
=> Bugfix: Leave fullscreen on iPad when entering remote settings

XBMC Remote/iPad/MenuViewController.m
When selecting the remote in the iPad main menu, the former selected item shall be kept active. The remote on iPad is a popover, so there is is no reason to deselect the current active menu.
Improvement: Select/Deselect behavior for remote in iPad main menu
=> Improvement: Select/Deselect behavior for remote in iPad main menu

XBMC Remote/RemoteController.m
Improves an observation reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3116387#pid3116387).
Dismiss keyboard when leaving NowPlaying remote. This results in a consistent behavior for both full screen and "under right" (aka NowPlaying) remote.
Improvement: Dismiss keyboard when leaving NowPlaying remote
=> Improvement: Dismiss keyboard when leaving NowPlaying remote

XBMC Remote/ShowInfoViewController.m
For IPad the formerly removed special treatment needs to be re-added (#730). This is obviously important to let the Ken  Burns animation always use the whole screen. This is triggered via calling `elabKenBurns` again when entering the fullscreen fanart. For iPhone the solution to use `UIScreen.mainScreen.bounds` still is correct.
Bugfix: Wrong dimension of Ken Burns animation on iPad
=> Bugfix: Wrong dimension of Ken Burns animation on iPad

XBMC Remote/AppInfoViewController.m, XBMC Remote/CustomNavigationController.m, XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.m, XBMC Remote/HostViewController.m, XBMC Remote/InitialSlidingViewController.m, XBMC Remote/Kodi Remote-Info.plist, XBMC Remote/MasterViewController.m, XBMC Remote/MoreItemsViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/ViewControllerIPad.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/745.
This PR redefines `supportedInterfaceOrientations` for iPad/iPhone via introducing `getSupportedOrientation` to return the desired supported orientation (portrait for iPhone and all for iPad).
Bugfix: Unwanted rotation after selecting item in iPad landscape fullscreen (iOS16 only)
=> Bugfix: Unwanted rotation after selecting item in iPad landscape fullscreen (iOS16 only)

XBMC Remote/DetailViewController.m
Use `id` type for the parameter and cast to `UITableViewCell*` when accessing the `backgroundColor`.
Maintenance: Remove compiler warning
=> Maintenance: Remove compiler warning

XBMC Remote/DetailViewController.m
Avoid a potential crash in `loadDetailedData` reported from AppStore. We are in GlobalSearch view which only supports `choosedTab = 0`.
Bugfix: Avoid potential crash when loading GlobalSearch
=> Bugfix: Avoid potential crash when loading GlobalSearch

XBMC Remote/DetailViewController.m
Fixes a regression reported [in this forum thread](https://forum.kodi.tv/showthread.php?tid=359717&pid=3116857#pid3116857).
Use correct `backgroundColor` for grid view when not in TVShow view. Ensure we only change background colors while in TVShow view.
Bugfix: Use correct background for grid view when not in TVShow view
=> Bugfix: Use correct background for grid view when not in TVShow view

XBMC Remote/DetailViewController.m
Do not reload grid view flag in `displayData`. This is not needed and fixes a problem with resynchronizing data (pull down) in fullscreen mode when the fullscreen mode was entered from a  list view.
Bugfix: Resync in iPad fullscreen only works one time when coming from list view
=> Bugfix: Resync in iPad fullscreen only works one time when coming from list view

XBMC Remote/AppDelegate.m, XBMC Remote/NowPlaying.m
With this PR "art" is supported (needs Kodi 18+). This will now prefer "poster" above "thumbnail" as already done for movies. This also enables "fanart" and "clearlogo" support for the `ShowInfoViewController`.
Screenshots:
https://abload.de/img/simulatorscreenshot-iyaen7.png
https://abload.de/img/simulatorscreenshot-imwd1m.png
https://abload.de/img/simulatorscreenshot-inhe18.png
https://abload.de/img/simulatorscreenshot-iyid4z.png
Note: Kodi's built-in scrapers do not provide most of this information. For the full experience metadata needs to be added following [this guide](https://kodi.wiki/view/NFO_files/Music_videos).
Improvement: Support "art" for Music Videos
=> Improvement: Support "art" for Music Videos

XBMC Remote/AppDelegate.m
Taking care of a comment in [this forum thread](https://forum.kodi.tv/showthread.php?tid=359717&pid=3117187#pid3117187).
Configure TVShow-fullscreen to directly open `ShowInfoViewController` (TV Show details) instead of only showing an action sheet with only one single option ("TVShow Details").
Improvement: Directly show details when selecting a TVShow in iPad fullscreen
=> Improvement: Directly show details when selecting a TVShow in iPad fullscreen

XBMC Remote/DetailViewController.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3117275#pid3117275).
This fixes an animation glitch where the toolbar was shortly showing with fullscreen width before animating back to standard width. Now the toolbar only shows after the animation to standard width finished.
Bugfix: Correct fade-in animation for toolbar when leaving fullscreen
=> Bugfix: Correct fade-in animation for toolbar when leaving fullscreen

XBMC Remote/ShowInfoViewController.h, XBMC Remote/ShowInfoViewController.m
Fixes and issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3116884#pid3116884).
Leave fullscreen fanart on iPad when entering remote gear. This avoids a UI state where gestures are not working until fullscreen is entered/left again.
Bugfix: Leave fullscreen fanart on iPad when entering remote settings
=> Bugfix: Leave fullscreen fanart on iPad when entering remote settings

XBMC Remote/DetailViewController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/ViewControllerIPad.h, XBMC Remote/ViewControllerIPad.m, XBMC Remote/iPad/StackScrollViewController.h, XBMC Remote/iPad/StackScrollViewController.m
Resolves https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/215.
This PR implements rotation for iPad fullscreen, e.g. fullscreen grid view including related popovers and fullscreen fanart.
_Note:_
Still one final issue to resolve, but personally I can live with this: When you have 2 or 3 stack views active (e.g. albums > album titles > album info) and then start the fullscreen from the first view (e.g. albums), I currently need to drop the views and 2 and 3. After ending the fullscreen you only will have the first screen (e.g. albums) visible.
Feature: Support rotation for iPad fullscreen
=> Feature: Support rotation for iPad fullscreen

XBMC Remote/DetailViewController.m
Improving a glitch reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3117275#pid3117275).
This PR changes the toolbar behaviour while searching. It will now only hide the toolbar when a search is active with a _non-empty string_ in the searchbar. This improves the behaviour when dismissing the keyboard (either via scrolling or hiding the keyboard) while the searchbar field is empty. In such case the full item list is shown, but without the toolbar. For a user it is not clear why the toolbar is not visible.
Improvement: Hiding toolbar only with non-empty searchbar field
=> Improvement: Hiding toolbar only with non-empty searchbar field

XBMC Remote/NowPlaying.m
This PR sets the visibility of the playlist edit button only after reading the playlist content. This avoids possible race conditions, e.g. with Kodi 17 the edit button was showing "Edit" after changing the playlist, even though still being in editing state.
Screenshot: https://abload.de/img/bildschirmfoto2022-10zoeoe.png
Bugfix: Playlist edit button might show wrong label
=> Bugfix: Playlist edit button might show wrong label

XBMC Remote/iPad/StackScrollViewController.m
Resolves an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3117483#pid3117483).
Introduce a special treatment for custom button view on iPad. This pushes the latest requested custom button view on top of the stack and removes all other already existing instances of the custom button view from the stack.
Improvement: Avoid multiple custom button views on iPad
=> Improvement: Avoid multiple custom button views on iPad

XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m
Fixes a problem reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3117483#pid3117483).
The former solution also dismissed the remote popover. With this PR the dismissal is only applied to the action sheet when shown.
Remind: The action sheet is dismissed because the origin is not matching anymore as `FlowLayout`  changes with a rotation (different amount of columns and rows).
Bugfix: Do not dismiss remote when rotating iPad in fullscreen
=> Bugfix: Do not dismiss remote when rotating iPad in fullscreen

XBMC Remote/DetailViewController.m
Aligns behaviour of grid and list view index.
Resolves an observation mentioned in [this forum thread](https://forum.kodi.tv/showthread.php?tid=359717&pid=3118150#pid3118150).
Only hide the grid view index when searching with non-empty string
Improvement: Align behaviour of grid and list view index during search
=> Improvement: Align behaviour of grid and list view index during search

XBMC Remote/DetailViewController.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/776.
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/778.
First, adds out-of-bounds-checks for resilience. Second, fixes the handling of ivar `choosedTab` in case global search view is shown. This might need a better solution, but it is good enough for now to avoid crashes and improve usability.
Bugfix: Fix crashes in GlobalSearch
=> Bugfix: Fix crashes in GlobalSearch

XBMC Remote/DetailViewController.m
Fixes a regression reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3118274#pid3118274).
The underlying issue was that with the latest change to align the index visibility behaviour of list view and grid view the grid view could be made visible in list view as well (first go to grid view, then to list view, then click into searchbar). Now the grid view's index is always hidden when in list view.
Bugfix: Avoid doubled index
=> Bugfix: Avoid doubled index

XBMC Remote/AppDelegate.m
Fixes a regression reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3118274#pid3118274).
The Kodi settings was not correctly configured to support grid view. Because of this the grid view when entering "Add-on" was not working properly since version 1.11.
Bugfix: Re-enable grid view for Kodi settings
=> Bugfix: Re-enable grid view for Kodi settings

XBMC Remote/iPad/StackScrollViewController.m
Entering the custom button view on iPad with an empty view stack caused a crash. Could easily be reproduced by starting the App on iPad, calling remote and then pressing gear.
Bugfix: Avoid crash when calling custom button view from empty stack on iPad
=> Bugfix: Avoid crash when calling custom button view from empty stack on iPad

XBMC Remote/DetailViewController.m
Fixes a regression reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3118274#pid3118274).
First, this PR corrects TV Show background color for grid view and fullscreen when falling back to default thumb. Root cause was a not handled condition.
Second, it fixes an animation glitch when toggling between grid and list view in the TV Show view. Root cause was a long existing race condition when setting the variable `enableCollectionView` during the animation process. This needs to be set after the current view was faded out, and before the new view is faded in. Otherwise the layout of the current view is changed before it is faded out, which caused the visual glitch.
Bugfix: TV Show background color when falling back to default thumb
Bugfix: TV Show animation …
=> Bugfix: TV Show layout and animation grid/list view

XBMC Remote/DetailViewController.m
Fixes a regression reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3118274#pid3118274).
This avoids to enter an undefined state of the search bar. It is important to do this with an empty as well as non-empty search string.
The keyboard is already dismissed when dragging while a search with an empty string is active. As the user cannot visually differentiate between an empty search and no search, but an active search will block the toolbar buttons, it is desired to also end the search in such case.
Bugfix: Undefined states when using toolbar buttons during search
Bugfix: Section layout glitches when toggling between grid and list view
=> Bugfix: Undefined states when using toolbar buttons during search

XBMC Remote/DetailViewController.m
This PR align the music video's thumb size of GlobalSearch view with the standard list view, as well as the thumb content with other views and NowPlaying.
Screenshots:
[https://abload.de/img/bildschirmfoto2022-11v0c64.png (thumb content)](https://abload.de/img/bildschirmfoto2022-11rydyx.png)
Improvement: Align GlobalSearch thumb size and content
=> Improvement: Align GlobalSearch thumb size and content

XBMC Remote/DetailViewController.m
Improves an observation reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3118274#pid3118274).
List view scroll bar uses `UIScrollViewIndicatorStyleDefault` to follow light/dark mode. Grid view scroll bar always is set to `UIScrollViewIndicatorStyleWhite` due the dark background.
Improvement: Make scrollbars readable in light/dark mode
=> Improvement: Make scrollbars readable in light/dark mode

XBMC Remote/DetailViewController.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3118289#pid3118289) and some more.
This PR applies fixes and improvements around the index in iPad fullscreen.
- Build `indexView` for grid view only during initialization
- Fix seeking via index in iPad fullscreen when sorted by year
- iPad fiullscreen section overlay `sectionNameOverlayView` needs to be re-initialized after rotation
- Enlarge iPad fullscreen section overlay `sectionNameOverlayView` for improved readability
- Coding style change (use conditional assignment)
Bugfix: Keep iPad fullscreen index when cancelling search
Bugfix: Correct layout of index seek layover after rotation in fullscreen
Bugfix: Correct index seek "by-year" in fullscreen
Improvement: Enlarge index seek layover …
=> Rework iPad fullscreen index

XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m, XBMC Remote/DetailViewController.xib
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3118274#pid3118274).
The toolbar's buttons were moving after entering a view for the first time. This was very prominent when pressing "...more" in the custom button view. Reason for this was that the building of the toolbar via `buildButtons`  was already called in `viewDidLoad`. Now the xib already loads the hidden button background default images to support the layout, and `buildButtons` -- which loads the background images and unhides the desired buttons -- is called in `viewDidAppear` or when the tab is changed. This resolves the animation glitch.
In addition, this PR does some refactoring for improved code readability and to avoid the tacky use of `UIButton` to transfer a tab index. …
=> Rework building the toolbar button list

XBMC Remote/DetailViewController.m
Since https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/774 list scrolling stuttered. Reason for this is that `[self.searchController setActive:NO]` triggers a layout of all cells again. So, this should only be called if the search is really active. Otherwise each scrolling gesture will trigger a layout of the cells again in high frequency.
This bug became quite visible due to another layout issue which is now also fixed. The y origin needs to be reset to 0 for the title when laying out the cell. Only for a few types this is changed alter.
Bugfix: Stuttering list scrolling
=> Bugfix: Stuttering list scrolling

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m
The former change applied was not fixing then underlying problem. Now the grid view is checked for initialization each time the view is enabled.
Bugfix: Final fix for settings grid view
=> Bugfix: Final fix for settings grid view

XBMC Remote/DetailViewController.m
Reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3118780#pid3118780).
Setting a search inactive via `[searchController setActive:NO]` triggers `updateSearchResultsForSearchController`. To avoid the hide/unhide of the toolbar inside `updateSearchResultsForSearchController` while a search is inactive, it is desired to check for an active search.
In addition, restore the animation of the toolbar when entering a child view (e.g. selecting an album or a genre). The desired animation is to first hide the toolbar (done in `viewWillAppear`), followed by showing the desired child view's toolbar Done in `viewDidAppear`).
Bugfix: Wrong inset in album/episode view after album/tvshow details
=> Bugfix: Wrong inset in album/episode view after album/tvshow details

XBMC Remote/HostManagementViewController.m
Avoids showing multiple active server connections, which was caused by the fact that `dequeueReusableCellWithIdentifier` can result in re-ordered cells.
Screenshot: https://abload.de/img/bildschirmfoto2022-11g0dnb.png
Bugfix: Avoid non-updated cell connection icon in server list
=> Bugfix: Avoid non-updated cell connection icon in server list

XBMC Remote/RemoteController.m, XBMC Remote/ViewControllerIPad.m, XBMC Remote/iPad/MenuViewController.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/797
Do not send  "StackScrollOnScreen" when bringing up the remote. This causes the progress bar to become unavailable when dismissing the remote. But send it when entering settings via remote to avoid a visible progress bar on top of the settings.
Bugfix: Make iPad's NowPlaying progress bar usable after dismissing remote
=> Bugfix: Make iPad's NowPlaying progress bar usable after dismissing remote

XBMC Remote/iPad/MenuViewController.m
Set iPad menu item alpha in `cellForRowAtIndexPath`. Ensure the main menu cells are initialized properly when becoming visible.
Bugfix: Start with grayed out iPad main menu
=> Bugfix: Start with grayed out iPad main menu

XBMC Remote/NowPlaying.xib
Use `lightGrayColor` instead of `grayColor` for the scrubbing rate info.
Improvement: Brighter color for scrubbing rate to improve readability
=> Improvement: Brighter color for scrubbing rate to improve readability

XBMC Remote/HostManagementViewController.m, XBMC Remote/HostManagementViewController.xib, XBMC Remote/InitialSlidingViewController.xib, XBMC Remote/MasterViewController.m, XBMC Remote/MasterViewController.xib, XBMC Remote/NowPlaying.m, XBMC Remote/NowPlaying.xib, XBMC Remote/RemoteController.xib, XBMC Remote/RightMenuViewController.m, XBMC Remote/RightMenuViewController.xib, XBMC Remote/ShowInfoViewController.xib, XBMC Remote/ViewControllerIPad.xib, XBMC Remote/VolumeSliderView.xib, XBMC Remote/cellView.xib, XBMC Remote/cellViewIPad.xib, XBMC Remote/iPad/MenuViewController.m, XBMC Remote/jsonDataCell.xib, XBMC Remote/playlistCellView.xib, XBMC Remote/rightCellView.xib, XBMC Remote/serverListCellView.xib
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/761.
- Unify use of `loadNibNamed`
- Unify use of cell identifiers (will update some xib to new toll version)
- Remove superfluous assignments and calls observed while working an this
Maintenance: Unify loading nib
=> Maintenance: Unify loading nib

XBMC Remote/AppDelegate.m
`enableSection` needs to be set to show the amount of items on iPad.
Screenshots: https://abload.de/img/bildschirmfoto2022-11n7f9z.png
Improvement : Show amount of Global Search items on iPad
=> Improvement : Show amount of Global Search items on iPad

XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m, XBMC Remote/NowPlaying.xib, XBMC Remote/ViewControllerIPad.m
Do not insert `songDetailsView` above `rootView` on iPad. This resolves a problem with `scrubbingView` shown underneath the `songDetailsView` on iPad. Instead, forward `touchesEnded` to `nowPlayingViewController`. This requires to add `closeButton` as well, it allows to close `songDetailsView` when touching the area outside and it removes duplicate code.
Bugfix: Draw scrubbing message on top of song details view on iPad
Improvement: Close song details view when touching outside area
=> Rework button processing of songDetailsView

XBMC Remote/DetailViewController.m
Use `BDKCollectionIndexView` for `UITableView` as well. This improves and unifies the overall index usability.
- Same position when switching between list/grid view
- Transparent overlay for TVShow banner view
In addition, fix the inset for grid view after jumping to top or to bottom via index and improve the readability on iPad via adding a small padding on the right side of the index.
Bugfix: Correct inset for grid when jumping to top/bottom via index
Bugfix: Avoids issue with iOS16 index when minimizing App in iPhone
Improvement: Transparent index overlay for TVShow banners
Maintenance: Use same same index implementation for grid/list view
=> Rework index

XBMC Remote/NowPlaying.m
Fixes an issue reported in [this forum thread](https://forum.kodi.tv/showthread.php?tid=359717&pid=3120534#pid3120534).
This PR will move the iPad prograss bar to the background when the user opened a stack view from an action sheet after long pressing a playlist item. It will send `StackScrollOnScreen` in such case.
Bugfix: Hide iPad progress bar after selecting longpress action on a playlist item
=> Bugfix: Hide iPad progress bar after selecting longpress action on a playlist item

XBMC Remote/DetailViewController.m
Fixes and issues reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3120534#pid3120534).
Remove shadow and separation line in episode view as this causes visual glitches when scrolling the collapsed seasons out of view. In the link above a video of the glitches is shared.
Bugfix: Fix visual glitches when scrolling collapsed seasons in episode view
=> Bugfix: Fix visual glitches when scrolling collapsed seasons in episode view

XBMC Remote/DetailViewController.m
Changes to method `toggleOpen:` which handles opening and closing season sections inside the episode view. Add dedicated refreshing of layout, setting the inset and scrolling to the desired section. This fixes multiple issues:
- Search not working after expanding one section
- Wrong inset after expanding section
- Wrong position of expanded sections when not fully visible during selection
Bugfix: Search not working after expanding one section inside episode view
Bugfix: Fix scrolling to opened section in episode view
Bugfix: Fix potentially wrong vertical inset after opening a section
=> Rework and fix open/close of sections in episode view

XBMC Remote/DetailViewController.m
It was possible to end up in a situation where either an active search with an empty string or even after cancelling such search an empty toolbar was shown. This was connected to the recently feature to keep showing the toolbar as long as the search string is empty.
This PR now adds some logic to hide the toolbar if either the search string is empty OR the toolbar is empty.
Bugfix: Avoid showing empty toolbars after using search
=> Bugfix: Avoid showing empty toolbars after using search

XBMC Remote/ShowInfoViewController.m
Use `UIColor.grayColor` for right arrow icon in `ShowInfoViewController`.
Screenshots: https://abload.de/img/bildschirmfoto2022-12cucw3.png
Improvement: Use gray color for right arrow in details view
=> Improvement: Use gray color for right arrow in details view

XBMC Remote/NowPlaying.xib
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3121191#pid3121191).
Avoid a visual glitch when switching from a library view (e.g. TV Shows) to NowPlaying. by initializing party mode button as transparent.
Bugfix: PartyMode button visible when animating from library view to NowPlaying
=> Bugfix: PartyMode button animation

XBMC Remote/DetailViewController.m, XBMC Remote/FloatingHeaderFlowLayout.m, XBMC Remote/HostViewController.m
This PR applies 3 confirmed fixes for crashes reported from AppStore (out of bounds access in `didSelectRowAtIndexPath`,  `showAlbumActions` and `layoutAttributesForElementsInRect`).
On top the PR also has two potential fixes which I found after research on www.stackoverflow.com. First is about setting some properties to `nil` in `dealloc` -- I am not sure, if this is relevant anymore. Second, is avoiding a potential recursive call in `textField:shouldChangeCharactersInRange:replacementString:` by using a copy of the object.
Bugfix: Fix potential crashes reported from AppStore
=> Bugfix: Fix potential crashes reported from AppStore

XBMC Remote/ConvenienceMacros.h, XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.m, XBMC Remote/InitialSlidingViewController.m, XBMC Remote/MasterViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/ShowInfoViewController.m
As brought up in [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3121198#pid3121198) the navigation bar items have a different gray tone. This PR aligns this to use` UIColor.lightGrayColor` for navigation bar items and toolbar buttons. In addition, the PR removes unused parameters from colorization helper methods inside the `NowPlaying` controller.
Screenshots: https://abload.de/img/bildschirmfoto2022-12gucrv.png
Improvement: Align color of navigation bar items
=> Improvement: Align color of navigation bar items

XBMC Remote/NowPlaying.m, XBMC Remote/NowPlaying.xib, XBMC Remote/ViewControllerIPad.m
Fixes a regression reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3121330#pid3121330).
This PR provides following changes:
- Keep `songDetailsView` on top of iiPad's `rootView` to support scrolling of details
- Do not allow to bring up `songDetailsView` while iPad stack is shown
- Move scrubbing message below song details view
Bugfix: Support scrolling song details on iPad
=> Bugfix: Support scrolling song details on iPad

XBMC Remote/NowPlaying.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3122361#pid3122361).
The playlist editing shall be ended after clearing the playlist (done via shaking when "Shake to clear playlist" is enabled).
Improvement: End editing playlist when clearing it
=> Improvement: End editing playlist when clearing it

XBMC Remote/DetailViewController.m
Fixes an issues reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3122541#pid3122541).
If a search keyboard was dismissed by scrolling, it should keep hidden after selecting an item and coming back to the origin view. This is ensured via setting `showkeyboard = NO;` when dismissing it on dragging the list.
Bugfix: Keep keyboard hidden after dismissing via scroll
=> Bugfix: Keep keyboard hidden after dismissing via scroll

XBMC Remote/NowPlaying.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3122896#pid3122896).
When nothing is playing the method `nothingIsPlaying` handles the screen updates. In this method the mini thumb was not updated to use the default thumb when stopping the playback. To ensure this update happens the condition check needs to be corrected. Luckily, we already have such condition inside `setButtonImageAndStartDemo`. So we just just use this to avoid code duplication.
Bugfix: Update the mini thumb when stopping playback in playlist view
=> Bugfix: Update the mini thumb when stopping playback in playlist view

XBMC Remote/NowPlaying.m
Resolves and issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3122896#pid3122896).
Reset the playlist after editing a row. Ensures the list view is properly initialized again after editing a single row. This resolves a problem where the current playback time was not properly updated after entering edit mode for a playlist item.
Bugfix: Current time frozen after editing a single playlist item
=> Bugfix: Current time frozen after editing a single playlist item

XBMC Remote/RemoteController.m
This PR corrects the origin for audio stream and sub title action sheets, which is only relevant for iPads. The origin needs top refer to `remoteControlView` and the button frames.
Screenshots: https://abload.de/img/bildschirmfoto2022-124mco7.png
Bugfix: Use correct origin for audio stream and sub title action sheets
=> Bugfix: Use correct origin for audio stream and sub title action sheets

XBMC Remote/Utilities.m, XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/818.
This PR reworks `DSJSONRPC` to support multiple `NSURLSessionDataTask` objects in a single instance. By this  `DSJSONRPC` object can be created only when required -- first time and when the configuration changes.
Bugfix: Resolves lock up after volume gesture
=> Rework: DSJSONRPC processing and usage

XBMC Remote/NowPlaying.m
Fixes an issue reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3122541#pid3122541).
The issue was generally caused by a race condition when using global variables. In future I would like to get rid of the global variables, but as a quick fix towards the next version is needed, this PR solves the underlying problem.
Background:
The global variable `storedItemID` holds the playlist index of the playing item. In `getActivePlayers` the screen updates are done, triggered by a timer. To reduce load several activities inside `getActivePlayers` are only taking place, if the current playing item `currentItemID` is not the same as `storedItemID`. The error happens, if the new instance of NowPlaying already initialized `storedItemID`, but the old instance still runs …
=> Bugfix: Fix empty cover in NowPlaying

XBMC Remote/NowPlaying.m
This PR fixes the Hi-Res logo not being shown (regression of app version 1.10). Simply process the codec name right after reading it. This ensures code names like "pcm_..." are recognized as lossless codecs.
Bugfix: Show Hi-Res logo again
=> Bugfix: Show Hi-Res logo again

XBMC Remote/NowPlaying.m
The behaviour for "nothing is playing" is inconsistent when the feature option "show jewel case" is enabled: 
1) no jewel case shown when entering the NowPlaying screen while nothing is played
2) jewel case of the last played item is shown when stopping playback or playlist ends. 
With this PR the jewel case is _always_ hidden when nothing is playing.
Improvement: Do not show jewel case when nothing is playing
=> Improvement: Do not show jewel case when nothing is playing

XBMC Remote/DetailViewController.m
Handles issues reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3123435#pid3123435).
With this PR only the first episode of an unfolded season is moved into the visible area. This feels smoother than scrolling the whole season into view.
Also change the interaction of search and unfolding a season. Explicitly dismiss keyboard and end search. Also only restore the `dataList.tableHeaderView` after updating `dataList`, instead of reinitializing the whole library view. This resolves some glitches (e.g. unfolding a season while active search does not end search properly).
Test cases:
- Enter TV Show > enter search > scroll > shall dismiss search and keyboard -> OK
- Enter TV Show > enter search > unfold season > shall dismiss search and keyboard -> OK
- Enter …
=> Fix and improve unfolding TV Show season

XBMC Remote/HostManagementViewController.m, XBMC Remote/MasterViewController.m, XBMC Remote/iPad/MenuViewController.m
This PR reworks the cell creation and layout for some controllers.
`MasterViewController`
The main menu controller for iPhone does now apply the desired layout outside of the cell creation condition (`if (cell == nil)`). This prepares for the future case of using dequeued cells. Currently this is not happening even after putting the App to sleep. Also the size of the server name label is corrected.
`MenuViewController`
The main menu controller for iPad does now use a simplified call to set the frame of `backgroundView`.
`HostManagementViewController`
Make arrow icon readable when editing server list in light mode.
Maintenance: Rework cell creation for some controllers
Improvement: Make arrow icon readable when editing server list in light mode
Improvement: Correct dimension for server …
=> Maintenance: Rework cell creation for some controllers

Kodi Remote.xcodeproj/project.pbxproj
Enables support for Croatian (hr-hr) as this is now fully translated. Should be merged after https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/833.
Feature: Add support for Croatian (hr-hr) language
=> Add support for Croatian (hr-hr) language

XBMC Remote/VolumeSliderView.h, XBMC Remote/VolumeSliderView.m, XBMC Remote/VolumeSliderView.xib
Rework volume button handling
- Replace magic numbers
- Handle slider via `UIControlEventValueChanged` instead of misusing button press methods
- Dedicated long press handling and timers for volume button press
- Propagate `sender tag` instead of using global variable `action`
- Use `switch-case` instead of `if-else`
Requires to have the volume lock fix (https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/819) merged first. Otherwise the smoother slider handling, which causes more JSON command per second, will cause lock ups as well.
Improvement: Faster volume change when holding volume buttons
Improvement: Smoother volume change via slider
=> Rework volume button handling

XBMC Remote/RightMenuViewController.h, XBMC Remote/RightMenuViewController.m, XBMC Remote/rightCellView.xib
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3120620#pid3120620).
The cell layout of `rightMenuCell` was inconsistent after App wakeup. To avoid this the code does not cache the few cells anymore, but re-creates them in `cellForRowAtIndexPath`. Alongside with this change, there were some cleanups added to remove magic numbers and not needed views.
Set `overrideUserInterfaceStyle` to `UIUserInterfaceStyleDark` for the custom remote button cells. These always have a dark background and ignore the system wide dark/light mode. This way the reorder icons are readable when in light mode.
Screenshots: https://abload.de/img/bildschirmfoto2022-12z5f82.png
Bugfix: Layout issues after App wakeup in power menu and custom button menu
Improvement: …
=> Rework cell layout inside rightMenuViewController

XBMC Remote/RightMenuViewController.m
As mentioned in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/836 there is still a problem with the layout after sleep / resume cell in `RightMenuViewController`. The former code also was not using dequeueing but loaded the cell fresh each time. To unblock the release 1.12 I propose a workaround which again loads the custom button rows each time when entering `cellForRowAtIndexPath`.
This needs another rework in future.
Bugfix: Improve readability of button rename icon in light mode
Bugfix: Fix custom button layout problems after sleep / resume
=> Fixes for custom buttons

XBMC Remote/RightMenuViewController.m
This PR ensures the layout of iPhone's embedded remote is correct after sleep/resume. If not done, the embedded remote's autoresizing moves the toolbar and the remote (when NowPlaying was entered with the remote being placed on bottom) out of the visible area. This potential issue was existing since long, as it happens when after dequeuing not exactly the same cell is being used as the embedded remote initialized with. It now became visible as we disabled dequeueing temporarily for this Controller.
Really needs an overhaul.
Bugfix: Fix layout of embedded remote after sleep/resume
=> Bugfix: Fix layout of embedded remote after sleep/resume

XBMC Remote/MasterViewController.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
After dequeuing iPhone  main menu cells, the server info (top most row) was reinitialized with "No connection". Instead, the current server name must be used.
In addition, only add the Kodi logo at cell creation, and control visibility afterwards. This fixes an issues with multiple instances of Kodi logo added on top of each other when the server status uses a dequeued cell.
Bugfix: Show correct server name / layout after moving iPhone server status out of visible area
=> Bugfixes for iPhone main menu's server status

XBMC Remote/MasterViewController.m, XBMC Remote/ViewControllerIPad.m
Only stop TCP on `UIApplicationDidEnterBackgroundNotification`. Avoids TCP being switched off on `UIApplicationWillResignActiveNotification` (e.g. when entering the list of active apps). In this case TCP is not enabled again as this is connected to `UIApplicationWillEnterForegroundNotification`.
Bugfix: Avoid undesired loss of TCP connect when entering iOS App Switcher or Notification Center
=> Changes around TCP connection and server status icon

XBMC Remote/DetailViewController.m, XBMC Remote/VersionCheck.h, XBMC Remote/VersionCheck.m, XBMC Remote/tcpJSONRPC.m
To improve code readability several version checks for major/minor/patch versions of the API are moved to dedicated helper methods of the class `VersionCheck`.
Maintenance: Introduce dedicated check methods instead of checking API major/minor/patch version
=> Maintenance: Improve code readability by introducing version check helper methods

XBMC Remote/DetailViewController.m
Avoid potential crash in `scrollToRowAtIndexPath` (reported via AppStore crash log). The variable `currentIndex` must not be equal to -1 or out of the section boundaries.
Bugfix: Avoid potential crash when using index
=> Bugfix: Avoid potential crash when using index

XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/865.
This PR implements support for `RunScript` favourites. This was tested using the "Autostop" add-on, more details can be looked up in the issue linked above.
Feature: Support RunScript favourites
=> Feature: Support RunScript favourites

XBMC Remote/ShowInfoViewController.m
Initialize fanart and Ken Burns view only in `viewDidAppear`. This ensures the correct view dimensions are used and avoids a blank safe area when enabling Ken Burns fullscreen for _music albums detail view_ (for other views this worked).
Screenshots: https://abload.de/img/bildschirmfoto2022-11ybdoj.png
Bugfix: Avoid empty safe area in Ken Burns fullscreen on iPhone
=> Bugfix: Avoid empty safe area in Ken Burns fullscreen on iPhone

XBMC Remote/AppDelegate.m, XBMC Remote/Settings.bundle/Root.plist, XBMC Remote/Settings.bundle/en.lproj/Root.strings
This PR adds a new setting option "Theme" which allows to set `UIUserInterfaceStyle` for the whole app. Possible settings are:
- Automatic (use the system mode, default)
- Dark (use Dark Mode)
- Light (use Light Mode)
As this only works on devices running iOS 13 or higher the setting itself is named "Theme (iOS13+)".
Screenshots: https://abload.de/img/bildschirmfoto2022-107afrd.png
Feature: Add option to select dark/light/automatic theme
=> Feature: Add option to select dark/light/automatic theme

XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/864.
Fixes a regression caused by https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/699/commits/59d83881b963e2a5fa646a8e44fbc69a1c2adc6b.
By fault active code was removed, causing the shortcut icons to enter Remote and NowPlaying not being displayed anymore in iPhone navigation bar.
Bugfix: Fix regression of not showing remote/NowPlaying shortcuts on iPhones
=> Bugfix: Fix regression when updating detailItem

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m
Fixes an issue reported in [this forum post](https://www.kodinerds.net/index.php/Thread/73696-Titel-Sortierung-Kodi-Remote-V1-8-1-App-auf-IPad/).
When in file browser mode the remote app requests Kodi to report the result sorted by label. This result list will start with directories, followed by files -- each block sorted by label. The remote app must not sort this again.
In addition, this PR will also configure sort-by-label when requesting the Movie and Video sources (was already done for TV Shows).
Screenshots: https://abload.de/img/bildschirmfoto2023-02lvijd.png
Bugfix: Keep directories on top while in file browsing mode
Bugfix: Sort Movie and Video sources by name
=> Fix filebrowser

fastlane/Fastfile
Xcode 14 no longer needs bitcode
=> disable bitcode in fastlane

XBMC Remote/DetailViewController.m
Fixes an issue where sync animation continued when attempting to sync recording while not having the PVR running.
Bugfix: Stop animating pull down sync on PVR error
=> Bugfix: Stop animating pull down sync on PVR error

XBMC Remote/NowPlaying.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3150902#pid3150902).
When migrating to new XCode and reworking the color effect in NowPlaying screen, there was a regression caused which does not hide a fanart background when entering the "nothing is playing" state (e.g. stopping playback or losing the connection). This PR fixes this regression.
Bugfix: Hide the iPad background image if nothing is playing
=> Bugfix: Hide the iPad background image if nothing is playing

XBMC Remote/NowPlaying.m
Fixes an issue reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3151109#pid3151109).
Caused failing seek if the player ID (e.g. movie) was not the same as current shown playlist (e.g. music).
Bugfix: Seek via slider fails when displayed playlist and active player do not match
=> Bugfix: Seek via slider fails when displayed playlist and active player do not match

XBMC Remote/NowPlaying.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3151058#pid3151058).
The current time showing in the playlist needs to be reset to "00:00" when a new playlist item starts to play or a cell is selected. Otherwise the last valid time for this cell or for the previous played item's time is shown for a second.
Bugfix: Show playlist time to 00:00 when playing new item
=> Bugfix: Show playlist time to 00:00 when playing new item

XBMC Remote/HostManagementViewController.m, XBMC Remote/tcpJSONRPC.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/553.
This PR reworks signaling TCP/JSON connection status to reduce code duplication. It also fixes possibly misaligned server status icons and ensures the loss of JSON connection (now falls back to red status) or TCP connection (now falls back to yellow connection) is properly recognized and signaled to user. 
#843 must be merged first.
Bugfix: Ensure correct server status icons (red/yellow/green)
Maintenance: Refactor signaling of TCP/JSON connection status
=> Bugfix: Ensure correct server status icons (red/yellow/green)

XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m, XBMC Remote/NowPlaying.xib
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/719.
**Layout:**
The layout is updated by moving the cover up and having all text elements below. The text font (bold/normal, size, color) is changed to highlight the most important information.
**Content:**
`"year"` and `"director"` is shown as well as enrichment to the already available information.
**Refactoring:**
The code is refactored to ease up updating cover with and without having jewel case enabled: `thubmnailView` now always represents the cover and `jewelView` always the jewel case image. This allows to reduce code duplication and complexity.
**Animation:**
The flip animation when toggling between playlist and NowPlaying views is reworked to a single staged animation which looks a lot smoother than the former …
=> Rework NowPlaying

XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
This PR refactors the player commands (e.g. play, pause, seek) to use `NSDictionary` directly, which allows to reduce overhead by converting from array to dictionary.
Maintenance: Refactor player commands
=> Maintenance: Refactor player commands

XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m
This PR reworks the use of `UIActivityIndicatorView`. The code will now simply hand over the pointer to the `UIActivityIndicatorView` object instead of reading it via `viewWithTag`.  In addition, the variable names and the position of the activity indicator are improved.
Maintenance: Rework use of activity indicator
=> Rework use of activity indicator

XBMC Remote/MessagesView.h, XBMC Remote/MessagesView.m, XBMC Remote/RemoteController.h, XBMC Remote/RemoteController.m, XBMC Remote/RemoteController.xib, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
This PR updates the remote's messages for subtitle and audio stream configuration changes. Now, the same message style as for the rest of the app is used. The messages are always placed in the vertical middle of the touch area / 4-button remote field, use the full remote width and have centralized text.
To be able to implement this, the app-wide used class`MessagesView` needs some updates:
- Messages are invisible right from the start and only become visible while animating them
- Messages can be placed at non-0 vertical positions
Screenshots (top = new, bottom = old):
https://abload.de/img/bildschirmfoto2023-010qeck.png 
Improvement: Improve readability of subtitle and audio stream messages
=> Rework remote messages

XBMC Remote/NowPlaying.m
Rename the method which sets the visibility of the playlist cell's progress bar to `setPlaylistCellProgressBar:hidden:` to match its functions. Move reading the `UIView` from the cell into the method.
Maintenance: Update method name and reduce code duplication
=> Maintenance: Update method name and reduce code duplication

XBMC Remote/ConvenienceMacros.h, XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.m, XBMC Remote/MasterViewController.m, XBMC Remote/MessagesView.m, XBMC Remote/NowPlaying.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/SettingsValuesViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/ViewControllerIPad.m, XBMC Remote/iPad/StackScrollViewController.m
This PR reworks some layout related topics:
- Use `safeAreaInsets.top` instead of future deprecated `statusBarFrame.size.height`
- Avoid future deprecated `UIApplication.sharedApplication.keyWindow`
- Fix position `messageView` frame and the height of iPad's `rootView`
- Fix height of iPad stack view after disabling fullscreen (fanart)
Screenshots: 
https://abload.de/img/bildschirmfoto2023-0425dm5.png
https://abload.de/img/bildschirmfoto2023-04grfpj.png
Bugfix: Fix partially visible message view in status bar above iPad stack view
Bugfix: Fix stack view overlapping the bottom toolbar after disabling or rotating fullscreen on iPads with safe bottom area
Bugfix: Fix iPad's toolbar transparency in fullscreen mode
Maintenance: Use safeAreaInsets.top instead of future deprecated …
=> Rework layout around status bars, especially iPads

XBMC Remote/NowPlaying.m
The iPad's playlist toolbar position was wrongly calculated and now became visible after the latest changes.
Bugfix: Use correct position for iPad's playlist toolbar
=> Bugfix: Use correct position for iPad's playlist toolbar

XBMC Remote/MoreItemsViewController.h, XBMC Remote/MoreItemsViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/ViewControllerIPad.h, XBMC Remote/ViewControllerIPad.m, XBMC Remote/iPad/MenuViewController.h, XBMC Remote/iPad/MenuViewController.m
This PR implements a user resizable left menu for iPad's. The user can now vertically move the playlist header via touch and by this tailor the split between main menu and playlist. The limits are from showing no main menu at all to at least show a single playlist item. The user selected layout persists.
Screenshot: https://abload.de/img/bildschirmfoto2023-04mddrm.png 
Feature: Support user resizable left menu on iPad
=> Feature: Support user resizable left menu on iPad

XBMC Remote/NowPlaying.xib
Fixes an issue reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3151478#pid3151478).
The clearlogo fanart is now properly centralized in the the NowPlaying overlay. Before, it was slightly off to the left.
Screenshots (bottom shows fixed position):
<a href="https://abload.de/image.php?img=bildschirmfoto2023-05kriwm.png"><img src="https://abload.de/img/bildschirmfoto2023-05kriwm.png" /></a>
Bugfix: Properly centralizing clearlogo fanart in NowPlaying overlay
=> Bugfix: Properly centralizing clearlogo fanart in NowPlaying overlay

XBMC Remote/HostManagementViewController.m, XBMC Remote/Utilities.m
On iPhone 14 Pro the status bar and top safe area have different sizes ([link](https://useyourloaf.com/blog/iphone-14-screen-sizes/#:~:text=The%20iPhone%2014%20Pro%20screen,area%20inset%20is%2059%20points.)). The App layout needs the status bar height.
In addition, some magic numbers in HostManagementViewController are replaced with the proper frame sizes.
Screenshots (iPhone 14 Pro):
<a href="https://abload.de/image.php?img=bildschirmfoto2023-05qjehy.png"><img src="https://abload.de/img/bildschirmfoto2023-05qjehy.png" /></a>
Bugfix: Fix layout issue for iPhone 14 Pro
=> Bugfix: Fix layout issue for iPhone 14 Pro

XBMC Remote/NowPlaying.m
Need to use `jewelView` as reference for the `BottomView` position. Fixes an issue where the bottom view was misaligned when activating jewel cases.
Screenshots: https://abload.de/img/bildschirmfoto2023-05i1dfd.png
Bugfix: Fix NowPlaying layout with jewel cases in iPad landscape
=> Bugfix: Fix NowPlaying layout with jewel cases in iPad landscape

XBMC Remote/DetailViewController.m
Fixes wrong background color for add-on grid view.
Bugfix: Use dark background for grid view in TV Shows menu
=> Bugfix: Use dark background for grid view in TV Shows menu

XBMC Remote/NowPlaying.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/895.
In general `thumbnailView` must use `clipsToBounds` to keep scaled images within the jewel case and the view boundaries. In addition channel logos (when playing TV / Radio or recordings) must use `UIViewContentModeScaleAspectFit` to stay fully visible within the jewel case frame. 
Also changed the channel / recording jewel case to the TV style as it was used for episodes.
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2023-05prcl5.png"><img src="https://abload.de/img/bildschirmfoto2023-05prcl5.png" /></a>
Bugfix: Fix NowPlaying channel thumb with jewel case
Improvement: NowPlaying channel info for recordings
=> Bugfix: Fix NowPlaying channel thumb with jewel case

XBMC Remote/ShowInfoViewController.m
This PR simplifies the logic for loading covers in ShowInfoVC with and without jewel case. Always use `coverView` for the cover and `jewelView` for the jewel case. This allows to reduce the complexity of several conditions and makes use of already created helper method `elaborateImage`.
Maintenance: Rework loading covers in ShowInfoVC
=> Maintenance: Rework loading covers in ShowInfoVC

XBMC Remote/DetailViewController.m
0% elapsed can occur when both `starttime` and `endtime` are empty strings or `nil`. In this case do not mark the program as active.
Bugfix: Do not mark program active if not started yet
=> Bugfix: Do not mark program active if not started yet

XBMC Remote/DetailViewController.m
Use same background for `contenView` and `cell` for TV Show banners.
Set `heightForHeaderInSection` to 0 when there is only 1 section.
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2023-05xlizs.png"><img src="https://abload.de/img/bildschirmfoto2023-05xlizs.png" /></a>
Bugfix: Remove white line on top of TV Show banners
Bugfix: Remove white frame around selected TV Show banner
=> Bugfixes for TV Show banner layout

XBMC Remote/PosterCell.m, XBMC Remote/RecentlyAddedCell.m
Use `systemBlue` instead of `systemGreen` when highlighting selected items in grid view and "recently added" views. This aligns better with the color scheme of the Apps's UI. `systemBlue` is commonly used to visualize active views and elements.
Screenshots: <a href="https://abload.de/image.php?img=bildschirmfoto2023-05i8fry.png"><img src="https://abload.de/img/bildschirmfoto2023-05i8fry.png" /></a>
Improvement: Blue color for selected item in grid / recently added
=> Improvement: Blue color for selected item in grid / recently added

XBMC Remote/AppDelegate.m
This PR adds the "listened" check mark for several music library items and view:
- Albums reached via Artists
- Albums in Top100 Albums view
- Songs in Top100 Songs view
- Albums in Recently Added Albums view
- Songs in Recently Added Songs view
- Albums reached via Music Roles
- Never display the marks in an album view itself as this visually overloads the view.
- Never display the marks in Recently Played Albums / Song. They were played anyway.
Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2023-05tmcl3.png"><img src="https://abload.de/img/bildschirmfoto2023-05tmcl3.png" /></a>
Improvement: Add "listened" mark for several music library views
=> Improvement: Add "listened" mark for several music library views

XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/Settings.bundle/Root.plist, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/jsonDataCell.xib, XBMC Remote/playlistCellView.xib
Improves display season/episode based on user feedback.
- Add setting "Episode identifier" (options: "1.01", "1x01", "E1S01", "E01S01") 
- Use this identifier consistently in "recently added episodes", playlist, playlist action sheet and NowPlaying
- Show season episodes in same format as album tracks (no "1x01", but simply the episode number "1").
- Adapt formatting to skip displaying season/episode information in case this is not provided.
- Check `season` and `episode` variables for support of `intValue` to improve robustness.
- Improve readability for library view (bigger font for 2nd/3rd row and no shadow for `year` and `rating`)
Screenshots: https://abload.de/img/bildschirmfoto2023-0507c2r.png
Improvement: Displaying Season/Episode
Feature: User selectable episode identifier …
=> Improvement: Displaying Season/Episode

XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.h, XBMC Remote/RemoteController.m, XBMC Remote/RemoteController.xib, XBMC Remote/SettingsValuesViewController.m, XBMC Remote/iPad/StackScrollViewController.h, XBMC Remote/iPad/StackScrollViewController.m
Resolves https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/546.
This PR reduces the use of `viewWithTag` where it can be replaced by ivars, outlets, xib or refactoring.
Maintenance: Reduce use of viewWithTag
=> Maintenance: Reduce use of viewWithTag in iPads StackScrollVC

XBMC Remote/DetailViewController.xib, XBMC Remote/HostManagementViewController.xib, XBMC Remote/HostViewController.xib, XBMC Remote/NowPlaying.xib, XBMC Remote/ShowInfoViewController.xib
Remove the top horizontal bar in NowPlaying. This resolves an unwanted animation glitch when animating from NowPlaying to playlist view.
In addition, remove superfluous horizontal bars in other screens and improve the alignment of the input fields in the Kodi server configuration.
Bugfix: Remove unwanted top horizontal bars
Improvement: Proper alignment of input fields for Kodi server configuration
=> Bugfix: Remove unwanted top horizontal bar in NowPlaying

XBMC Remote/Settings.bundle/Root.plist
The default must represent the _value_ not the _name_ of a setting. This fixes an issue where the episode identifier format was set to "1.01" instead of "%d.%02d". The issue shows up after a clean app-install.
Screenshots (left = buggy, right = fixed): https://abload.de/img/bildschirmfoto2023-06g5ejg.png
Bugfix: All episodes showing "1.01" after clean app install
=> Bugfix: All episodes showing "1.01" after clean app install

XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/ShowInfoViewController.m
The episode view does not show information on season/episode for each episode as this is given by the section header and the item number. When searching for episodes this information was missing and is now added. The same information is now also added to the episode details view to reflect information on the season and episode number.
Screenshots: https://abload.de/img/bildschirmfoto2023-06kpfa1.png
Improvement: Add season/episode info for episode search and episode details
=> Improvement: Add season/episode info for episode search and episode details

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m
Fixes a regression caused by https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/901.
The parameter `"title"` is not support for `"GetSeasons"` with API < 10. `"GetSeasons"` is used to request additional data for section header for the episode view. As the same mapping configuration (`mainFields`) is used, the easiest approach to resolve this is to change the mapping to use `"label"` in only this case. With this the problematic `"title"` parameter can be removed from the JSON request.
Bugfix: Entering TVShow episodes fails with Kodi 17 and older
=> Bugfix: TVShow episodes do not show with Kodi 17 and older

XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/ViewControllerIPad.m
NowPlaying does not load the background image anymore, but just sends the path. The image is then loaded in `ViewControllerIPad` which allows to remove an obsolete variable.
Use `kCAFilterTrilinear` for up- and down-scaling for a selected set of views. The views are not part of list or grid view to avoid performance problems while scrolling. This potentially improves the scaling quality.
Maintenance: Rework iPad background fanart loading
Improvement: Use higher quality scaling for several view
=> Rework iPad background fanart loading and improve scaling quality

XBMC Remote/DetailViewController.m
Expanded sections now always move their section header to top, which allows to show all available episodes. Collapsed sections will stay at their position -- except the first section which needs to have the inset set explicitly to deal with scrolled episodes.
Use `UITableViewRowAnimationMiddle` when showing/hiding episodes. This resolves a glitch where unfolding a season animated the newly shown episode from above the section header. Now the animation fades in each newly shown episode from its middle which gives a smoother user experience.
In addition, some refactoring is done to use literals and use local variables where is makes sense.
Improvement: Smoother section expand/collapse animation in episodes view
Improvement: Always move section header to top when expanding a season …
=> Improve section handling when expand/collapse seasons in episodes view

XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/369.
This PR will improve displaying content with BB or HTML code. It was reported by users that some plugins (e.g. youtube) and  most likely also the metadata of some service providers use BB or HTML code. As it is not reasonable to let the BB or HTML code control the layout (e.g. the text must keep readable in its context and for dark/light mode), the related code is stripped off and not used. For BB code most of the key words are stripped (`b, u, i, s, center, left, right, url, img, font, size, color`), for HTML simply all non-empty `<>`-brackets are stripped. The latter is _a lot_ faster than using the iOS internal solution via `NSHTMLTextDocumentType`.
Screenshots (youtube plugin main menu):
<a …
=> Improvement: Ignore BB and HTML code for menu entries and descriptions

XBMC Remote/AppDelegate.m, XBMC Remote/ConvenienceMacros.h, XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/SDWebImage/SDImageCache.m, XBMC Remote/SDWebImage/SDWebImageDownloader.h, XBMC Remote/SDWebImage/SDWebImageDownloader.m, XBMC Remote/SDWebImage/SDWebImageDownloaderOperation.h, XBMC Remote/SDWebImage/SDWebImageDownloaderOperation.m, XBMC Remote/SDWebImage/SDWebImageManager.h, XBMC Remote/SDWebImage/SDWebImageManager.m, XBMC Remote/SDWebImage/SDWebImagePrefetcher.m, XBMC Remote/SDWebImage/UIButton+WebCache.m, XBMC Remote/SDWebImage/UIImageView+HighlightedWebCache.m, XBMC Remote/SDWebImage/UIImageView+WebCache.m, XBMC Remote/ShowInfoViewController.m
Fixes an issue reported in the forum and which was caused by https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/884.
When the loaded images have a different size as the view they are loaded to re-scaling happens. Before migrating to sdwebimage 3.8.3 there already has been a special treatment for several lists where images were scaled before adding them to the cache. This PR is re-adding this mechanism in a slight different way. Now there is no call parameter but a new option `SDWebImageScaleToNativeSize` introduced. If this is set, the pre-scaling is executed and the targeted size is taken from the view itself. The option is used only for a subset of views, with a focus to views with many images. The improvement is quite visible for episode view and the actor list.
This PR also makes …
=> Bugfix: Resolves stutter when scrolling several lists

XBMC Remote/SDWebImage/SDWebImageDownloader.m
When attempting to load a non-loadable image, `dataOperation` will be `nil`, which results in the the completion handler not being called. To resolve this `completionHandler(nil)` is called in this case (= not caching response).
Bugfix: Fix runtime warning in SDWebImageDownloader
=> Bugfix: Fix runtime warning in SDWebImageDownloader

XBMC Remote/GlobalData.h, XBMC Remote/GlobalData.m, XBMC Remote/HostManagementViewController.m, XBMC Remote/HostViewController.h, XBMC Remote/HostViewController.m, XBMC Remote/MasterViewController.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/Settings.bundle/Root.plist, XBMC Remote/Settings.bundle/en.lproj/Root.strings, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/ViewControllerIPad.m, XBMC Remote/tcpJSONRPC.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/256.
This PR improves the Remote App's capability during service discovery (when pressing "Find Kodi"):
- Enable support for IPv6 and localhost
- Resolve TCP port automatically
- User setting for preferred address type (IPv4, IPv6 or localhost)
- Bring back "Find Kodi" button on service discovery error
Improvement: Support IPv6 and localhost during service discovery
Improvement: Resolve TCP port during service discovery
Improvement: User selectable address type preference
Bugfix: Re-enable "Find Kodi" on service discovery error
=> Improve service discovery and support IPv6

XBMC Remote/HostViewController.m, XBMC Remote/Kodi Remote-Info.plist
This PR fixes resolving the TCP IP on iOS devices (hardware). The new code also ignore invalid MAC addresses on iOS devices ("02:00:00:...").
Bugfix: Resolve TCP IP on iOS devices
Bugfix: Ignore invalid MAC address on iOS devices
=> Fix iOS device service discovery

XBMC Remote/HostManagementViewController.m
Fixes an error reported via an ASC review.
Stopping the repeated connection attempts is done via deselecting the selected server. This way the loop which attempts to reconnect will be stopped and the user can edit the credentials.
Bugfix: Stop connection attempt on authentication error
=> Bugfix: Stop connection attempt on authentication error

XBMC Remote/DetailViewController.m, XBMC Remote/ShowInfoViewController.m
Issue was reported in the forum and details were already shared [in this post](https://forum.kodi.tv/showthread.php?tid=373911&pid=3162311#pid3162311).
Explicitly set locale to `systemLocale` for `NSDateFormatter` using "UTC" timezone. This resolves an issue where `NSDateFormatter` returns `nil` on `dateFromString` when the user selects a 12h format on his iOS device and Kodi sends 24h format. This resulted in issues in the channel list, the channel guide view (EPG) and the recording details.
In addition, this PR improves performance in the channel list by using an ivar instead of a local instance of `NSDateFormatter`.
Bugfix: LiveTV issues using 12h time format on App device and 24h format by Kodi server
=> Bugfix: LiveTV issues using 12h time format on App device and 24h format by Kodi server

XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3160623#pid3160623).
JSON API responses can arrive after the NowPlaying view was already removed from the view hierarchy. Adding a check for this resolves a runtime warning when calling `cellForRowAtIndexPath` on a view which is not in the view hierarchy anymore. In addition, such check fixes a problem where `storedItemID` was set for an old instance of NowPlaying, causing the new instance to not load thumbs and metadata for the current running item anymore.
Use ivar instead of global variable in NowPlaying to avoid potential problems with race conditions where outdated instances of NowPlaying would set global variables like storedItemID` which influence the behaviour of the current instance. …
=> Improve handling of race condition in NowPlaying view

XBMC Remote/DetailViewController.m
This PR fixes an issue where the color of the grid/list and sort buttons is wrong, if no results are found (e.g. no TV stations).
Screenshot: https://abload.de/img/bildschirmfoto2023-10d1c10.png
Fix button color in case no results found
=> Fix button color in case no results found

XBMC Remote/MasterViewController.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3168838#pid3168838).
In case of cell re-use the cell background color and the highlighted image were not properly set. This resulted in situations where the brighter background color of the server menu item was used for another menu item after performing sleep. In the same situation the icon shown in the selected server menu item after was falling back to a highlighted image which was set for another menu item before, e.g. the white headphones for the music menu item.
This PR now explicitly sets the `highlightedImage` (`nil` for row 0) and the cell's background color.
Bugfix: Avoid wrong icon/color to be shown in iPhone main menu
=> Bugfix: Avoid wrong icon/color to be shown in iPhone main menu

XBMC Remote/HostViewController.h, XBMC Remote/HostViewController.m, XBMC Remote/HostViewController.xib, XBMC Remote/Settings.bundle/Root.plist, XBMC Remote/Settings.bundle/de.lproj/Root.strings, XBMC Remote/Settings.bundle/en.lproj/Root.strings, XBMC Remote/Settings.bundle/es-es.lproj/Root.strings, XBMC Remote/Settings.bundle/pl.lproj/Root.strings, XBMC Remote/en.lproj/Localizable.strings
With https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/923 the support to set a preference for the service discovery was added. As changing the preference was a bit awkward (users needed to enter the app settings and then go back to the service discovery screen), this PR adds a UISegmentControl which allows to set the preference for the next 'Find Kodi' button press. This should improve the usability.
Screenshots: https://abload.de/img/bildschirmfoto2023-087sim7.png
Improvement: Set the service discovery preference directly above 'Find Kodi'
=> Improve setting the service discovery preference

XBMC Remote/HostViewController.h, XBMC Remote/HostViewController.m, XBMC Remote/HostViewController.xib, XBMC Remote/Utilities.m
As users still raise problem reports and ratings/reviews about issues connecting to Kodi server, this PR adds links to Wiki and a pinned forum post which describe in more detail what needs to be configured.
Screenshot: https://abload.de/image.php?img=simulatorscreenshot-ikvehk.png
Improve help on the server connection screen
=> Improve help on the server connection screen

XBMC Remote/RemoteController.m
This PR addresses an issue raised in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3165521#pid3165521).
On iPhone the remote messages shall always cover the same area (full width and down to bottom of navigation bar). This avoids visual glitches when swiping the embedded remote and keeps the behaviour consistent for both embedded and fullscreen remote on iPhones. There is no change for iPad.
Improvement: Use same message layout for embedded and fullscreen remote
=> Improvement: Use same message layout for embedded and fullscreen remote

XBMC Remote/MasterViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/iPad/MenuViewController.m
This PR fixes an issue where not all menu cells were updated on connect/disconnect of Kodi server. This happened for menu cells which where scrolled out of the visible area, like on devices with smaller screens or on iPad with a small menu size configuration.
Bugfix: Not all menu cells updated on connect/disconnect
=> Bugfix: Not all menu cells updated on connect/disconnect

XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m, XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPCError.h, XBMC Remote/en.lproj/Localizable.strings
Improves robustness against mal-formatted JSON API responses.
Check for expected JSON object (`NSDictionary`) after deserialization. This avoids potential crashes reported via AppStore:
```
Last Exception Backtrace:
0   CoreFoundation                	0x1ce588cb4 __exceptionPreprocess + 164 (NSException.m:202)
1   libobjc.A.dylib               	0x1c76283d0 objc_exception_throw + 60 (objc-exception.mm:356)
2   CoreFoundation                	0x1ce6fdab8 -[NSObject(NSObject) doesNotRecognizeSelector:] + 136 (NSObject.m:140)
3   CoreFoundation                	0x1ce59f0e8 ___forwarding___ + 1592 (NSForwarding.m:3578)
4   CoreFoundation                	0x1ce605900 _CF_forwarding_prep_0 + 96 (:-1)
5   Kodi Remote                   	0x1043901b8 -[DSJSONRPC URLSession:task:didCompleteWithError:] + …
```
=> Improved robustness against mal-formatted JSON API responses

XBMC Remote/NowPlaying.m
Fixes and issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3169970#pid3169970).
NowPlaying's `viewDidDisAppear` does not need to end editing or make elements invisible. On iPhone the view is anyway deallocated after reaching `viewDidDisappear`. On iPad we want to keep the status as this only happens when calling Safari from the App (e.g. following the help link or entering Wikipedia). This fixes an issue where the playlist was empty, the editing got stopped and the NowPlaying overlay was closed on iPad after opening Safari from the App.
Bugfix: playlist empty after calling Safari from App on iPad
=> Bugfix: playlist empty after calling Safari from App on iPad

XBMC Remote/KenBurns/JBKenBurnsView.m
Simplify calculation of KenBurns resize ratio. Fixes that smaller images were not showing fullscreen or not all.
Screenshots: https://abload.de/img/bildschirmfoto2023-11zrdo6.png
Bugfix: KenBurns view did not show some art fullscreen
=> Bugfix: KenBurns view did not show some art fullscreen

XBMC Remote/NowPlaying.xib
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3171632#pid3171632).
Initialize HiRes logo as hidden to ensure the logo is not shown for a short time when showing the NowPlaying overlay for the first time.
Bugfix: Resolve unwanted short display of HiRes logo on first load of NowPlaying overlay
=> Bugfix: Resolve unwanted short display of HiRes logo on first load of NowPlaying overlay

XBMC Remote/Utilities.m
Do not attempt to process regular expression with string or expression `= nil`. Fixes following crash report:
```
Last Exception Backtrace:
0   CoreFoundation                	0x1bec40cb4 __exceptionPreprocess + 164 (NSException.m:202)
1   libobjc.A.dylib               	0x1b7ce03d0 objc_exception_throw + 60 (objc-exception.mm:356)
2   Foundation                    	0x1b8f48a88 -[NSRegularExpression(NSMatching) enumerateMatchesInString:options:range:usingBlock:] + 1724 (NSRegularExpression.m:0)
3   Foundation                    	0x1b8f47c74 -[NSRegularExpression(NSMatching) matchesInString:options:range:] + 180 (NSRegularExpression.m:534)
4   Foundation                    	0x1b8f19e5c -[NSRegularExpression(NSReplacement) stringByReplacingMatchesInString:options:range:withTemplate:] + 140 …
```
=> Bugfix: Fixes reported crash in stripRegEx:text

XBMC Remote/NowPlaying.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
Rounded edges are applied to `UIView` and not only to the subclass `UIImageView`. This allows to ease up the implementation and to unify calling it.
Maintenance: Refactor applying rounded edges to UIViews
=> Maintenance: Refactor applying rounded edges to UIViews

XBMC Remote/NowPlaying.m
Show "-" in case no EXIF data is reported for the given tag. This is easier to read than just leaving empty strings.
Improvement: Show "-" in case no EXIF data is reported for the given tag
=> Improvement: Show "-" in case no EXIF data is reported for the given tag

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/MasterViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/ViewControllerIPad.m
1. Limit in-memory cache size (1/4 of physical memory, but 256 MB max)
2. Only call `clearMemory` (= cleaning in-memory cache) in `applicationDidReceiveMemoryWarning`
3. Use `sd_setImageWithURL` instead of `queryDiskCacheForKey` which aligns this with all other places where images are loaded.
4. Set authorization for SWWebImage on connection success only.
Rework configuration of SDWebImage
=> Rework configuration of SDWebImage

XBMC Remote/AppDelegate.h, XBMC Remote/DetailViewController.m, XBMC Remote/PosterCell.m
This PR was triggered by a discussion in the forum. Following changes are done:
- iPad fullscreen adapts cover size to maintain equal spacing
- iPad fullscreen labels follows "hide label" setting
- Improve readability of labels in fullscreen
Screenshots:
Set 1: https://abload.de/img/bildschirmfoto2023-11qqd6u.png (albums)
Set 2: https://abload.de/img/bildschirmfoto2023-11gcfpt.png (movies)
Set 3: https://abload.de/img/bildschirmfoto2023-11z2dow.png (recently added)
Improvement: iPad fullscreen adapts cover size to maintain equal spacing
Improvement: iPad fullscreen labels follows "hide label" setting
Improvement: Better readability of labels in fullscreen
=> Improve iPad fullscreen layout

XBMC Remote/SDWebImage/SDImageCache.m
With the migration to SDWebImage 3.8.3 the maximum cache age was reduced from 1 month to 1 week. This PR brings this back to 1 month again.
Improvement: Extend the max image cache age to 1 month
=> Improvement: Extend the max image cache age to 1 month

XBMC Remote/NowPlaying.m, XBMC Remote/ShowInfoViewController.m
As suggested in https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/949#discussion_r1440715340 this PR changes the declaration of a weak self to the standard notation:
`__weak __typeof(self) weakSelf = self;`
Maintenance: Use standard notation when declaring weak self
=> Maintenance: Use standard notation when declaring weak self

XBMC Remote/ShowInfoViewController.h, XBMC Remote/ShowInfoViewController.m
The implemented solution will identify multiple variants of youtube.com and youtu.be links (http, https, www or not), extract the video id and create a fresh FullHD embedded youtube link from this. This allows to show all such links with in-app preview.
Improvement: Reformat non-embedded to embedded youtube video link
=> Improvement: Reformat non-embedded to embedded youtube video link

XBMC Remote/DetailViewController.m, XBMC Remote/ViewControllerIPad.m
This PR reworks the layout of the section header for albums and episodes. Now both use the same layout and method instead of separate implementations.
Overview of changes:
- Move duplicate code into helper method
- Unify layout for albums and seasons (adds fanart for season headers)
- Correct and ease up the layout calculation
- Simple runtime calculation and display
- Replace magic numbers
- Improve readability of bottom labels
Improvement: Rework section header layout for albums and episodes
=> Rework section header layout for albums and episodes

XBMC Remote/ShowInfoViewController.m
Early return if `URLWithString` returns `nil`. This avoids a crash reported via AppStore for TF build 4196 (1.14).
Bugfix: Avoid potential crash in trailer preview
=> Bugfix: Avoid potential crash in trailer preview

XBMC Remote/DetailViewController.m, XBMC Remote/SettingsValuesViewController.m, XBMC Remote/ShowInfoViewController.h, XBMC Remote/ShowInfoViewController.m
- Add boundary checks in EPG channel ID and (movie / episode / TV Show) cast processing.
- Use ternary operator in few places
- Improve naming of ivar (list of cast members)
- Remove `stringWithFormat` where not needed
Improvement: Avoid potential crashes and coding style
=> Improvement: Avoid potential crashes and coding style

XBMC Remote/SettingsValuesViewController.m
partially solves https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/981.
Sort the array of values before displaying it in the settings UI.
Improvement: Sort settings array before displaying
=> Improvement: Sort settings array before displaying

XBMC Remote/ConvenienceMacros.h, XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m, XBMC Remote/DetailViewController.xib, XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
During the review of another PR it was suggest to introduce a new convenience macro `LOCALIZED_STR_ARGS` to handle localized strings with arguments/parameters. I felt this improves the code readability and did this.
While working on this I also reworked the copy-clipboard warning popup to use a common method for the creation of the message text.
Maintenance: Add LOCALIZED_STR_ARGS convenience macro
=> Maintenance: Add LOCALIZED_STR_ARGS convenience macro

XBMC Remote/DetailViewController.m
This PR removes further magic numbers, slightly changes the layout itself and reduces code duplication by introducing a helper method as suggested in earlier reviews. It needs to be updated once #974 is merged.
Maintenance: Rework layout of progress pie and recording dot
=> Maintenance: Rework layout of progress pie and recording dot

XBMC Remote/AppDelegate.m
Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/987.
Do not request Kodi to sort response by "label" when requesting response from addons / plugins.
Bugfix: Do not sort plugin menus
=> Bugfix: Do not sort plugin menus

XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/ViewControllerIPad.m, XBMC Remote/XBMCVirtualKeyboard.h, XBMC Remote/XBMCVirtualKeyboard.m, XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPCError.h
Resolves https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/986.
Virtual keyboard might have been closed on App, but not on Kodi, which resulted in unexpected debug errors on the App. This is now resolved by canceling the Kodi keyboard by sending "Input.Back" in case of an active keyboard being canceled in the App. In addition, the App does now not show a debug message, when `""` was sent to the Addon search. Instead, only the "no items found" message is seen.
On top, this PR does some refactoring and hygiene changes like indentation and white spaces corrections, removes unneeded parameters and refactors the code which send the text.
Bugfix: Do not end up in debug message when searching in add ons
=> Bugfix: Do not end up in debug messages when searching in add ons

XBMC Remote/Utilities.m
The formerly used "Kodi blue" was too dark. Now updated this with the color taken from official logo from Kodi Wiki.
Bugfix: Use "Kodi blue" from official logo
=> Bugfix: Use "Kodi blue" from official logo

XBMC Remote/DetailViewController.m
Only attempt to create and layout the collection view when supported, which avoids a runtime warning when creating a flow layout with sizes of 0. Fixes a regression caused by https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/984/commits/9d0f34a84e0189376ceda3a0409ef81cf2c814e7, for some cases already introduced with 1.14-b1.
Bugfix: Only attempt to create the collection view when supported
=> Bugfix: Only attempt to create the collection view when supported

Kodi Remote.xcodeproj/project.pbxproj, PrivacyInfo.xcprivacy
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/1005.
- `NSPrivacyAccessedAPICategoryFileTimestamp` with `C617.1` because the image cache deletes aged files from image cache.
- `NSPrivacyAccessedAPICategoryUserDefaults` and `CA92.1` as we access the app's settings.
[not app] Declare privacy API usage
=> Maintenance: Declare NSPrivacyAccessedAPITypes

XBMC Remote/RightMenuViewController.m
The bottom bar of the custom button view on iPad uses a wrong height.
Bugfix: Fix bottom bar height for custom button view on iPad
=> Bugfix: Fix bottom bar height for custom button view on iPad

XBMC Remote/jsonDataCell.xib
Fixes an interesting finding which came in with new iOS versions. Some labels in `jsonDataCell` had too less height to allow rendering with the desired font size. Older iOS versions still rendered the text as can be seen from screenshots I made for app release 1.13 and which were shared by a user in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3188023#pid3188023). With newer iOS the font size is scaled down.
This PR now gives the labels the appropriate dimensions which allows to render in the desired font size.
Screenshot: https://ibb.co/7K4cWLh (the difference can easily be recognized by the font size for rating)
Bugfix: Increase font sizes for database view cells
=> Bugfix: Increase font sizes for database view cells

XBMC Remote/DetailViewController.m
Kodi <= 11 (not only < 11) does not support "art".
Bugfix: Avoid error response when requesting "art" with Kodi 11 or earlier
=> Bugfix: Avoid error response when requesting "art" with Kodi 11 or earlier

XBMC Remote/DetailViewController.m, XBMC Remote/MoreItemsViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/SettingsValuesViewController.m, XBMC Remote/iPad/MenuViewController.m
In several ViewControllers an empty or 1-line strong`UIView` was added as `tableFooterView`. This is not required and therefor removed.
Maintenance: Do not set empty or dummy tableFooterViews
=> Maintenance: Do not set empty or dummy tableFooterViews

XBMC Remote/HostManagementViewController.m, XBMC Remote/MessagesView.h, XBMC Remote/MessagesView.m, XBMC Remote/NowPlaying.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/SettingsValuesViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
Fixes a regression caused by https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/889.
Generally it is correct to use `UIApplication.sharedApplication.keyWindow.safeAreaInsets.top` in `getTopPadding`. This resolves issues with moving and wrongly positioned tables in iPhone main menu and custom button view. For the HostManagementViewController we use `UIApplication.sharedApplication.statusBarFrame.size.height ` to read the size of the status bar.
Bugfix: Fix vertical origin of main menu and custom button view
=> Bugfix: Fix top padding

XBMC Remote/NowPlaying.m, XBMC Remote/NowPlaying.xib
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/1023.
Fixes a review comment about improving the code which generates iPad's play control toolbar.
Maintenance: Refactor building iPad's play control toolbar
=> Maintainance: Refactor building iPad's play control toolbar

XBMC Remote/NowPlaying.m
This PR fixes an issue found with new "blurred cover background" feature. The background was not updated when switching playback from an item with a valid cover to an item which falls back to default cover. Now the blurred background is switched using the fading animation.
Bugfix: Remove blurred cover when falling back to default cover
=> Bugfix: Remove blurred cover when falling back to default cover

XBMC Remote/HostManagementViewController.h, XBMC Remote/HostManagementViewController.m
This fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3190952#pid3190952).
This was caused by incomplete configuration of the `ECSlidingViewController` in `HostManagementViewController`.
Bugfix: Fix potentially empty right pane for server view
=> Bugfix: Fix potentially empty right pane for server view

XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m
This fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3190952#pid3190952).
The layout function `setNowPlayingDimensionIPhone:height` can be called multiple times, resulting in changing the view and font sizes again. It is needed to use _absolute_ and not _relative_ size changes. In addition use `CGFloat` as input type and for the reference sizes `BOTTOMVIEW_WIDTH` and `BOTTOMVIEW_HEIGHT` when calculating the factors for resizing.
Bugfix: Avoid resizing of NowPlaying view and font on iPhone
=> Bugfix: Avoid resizing of NowPlaying view and font on iPhone

XBMC Remote/DetailViewController.m
Fixes a long standing issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3191003#pid3191003).
This PR resolves an issue where a list was animated both vertically _and_ horizontally instead of _only_ horizontally, if the former list had been scrolled before. This was caused by the content offset not being properly set before kicking off the animation.
Bugfix: Only animate new library lists horizontally
=> Bugfix: Only animate new library lists horizontally

XBMC Remote/RightMenuViewController.m
Improve readability of scroll indicator in `RightMenuViewController`. This always uses dark background and cells with dark background. So the scroll indicator should be set to `UIScrollViewIndicatorStyleWhite`.
Bugfix: Use white scroll indicator for RightMenuVC
=> Bugfix: Use white scroll indicator for RightMenuVC

XBMC Remote/DetailViewController.m
The method `setViewInset` shall process the _input_ parameter and not `dataList`. Fixes an issue with the collection view using wrong bottom inset for the scroll indicator.
Bugfix: Use correct bottom scroll inset for collection view
=> Bugfix: Use correct bottom scroll inset for collection view

XBMC Remote/NowPlaying.m, XBMC Remote/ViewControllerIPad.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/976.
Adds the amount of items for a playlist to the playlist header, e.g. "Playlist (16)".
Screenshots: https://ibb.co/2PT6G4Q
Improvement: Show playlist item count in header
=> Improvement: Show playlist item count in header

XBMC Remote/NowPlaying.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/1020.
This PR reworks the implementation for changing and displaying the repeat and shuffle modes. It reduces code duplication by adding helper methods to update the repeat and shuffle buttons.
Maintenance: Rework shuffle and repeat status change and button update
=> Maintenance: Rework shuffle and repeat status change and button update

XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m, XBMC Remote/ViewControllerIPad.h, XBMC Remote/ViewControllerIPad.m, XBMC Remote/ViewControllerIPad.xib
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/1021.
This PR removes all code related to UI colorization in NowPlaying (navigation bar items, labels and progress bar) and ViewControllerIpad.
Maintenance: Remove UI colorization code from NowPlaying and ViewControllerIpad
=> Maintenance: Remove UI colorization code from NowPlaying and ViewControllerIpad

XBMC Remote/AppDelegate.m, XBMC Remote/MasterViewController.h, XBMC Remote/MasterViewController.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/ViewControllerIPad.m
This PR introduces a globally visible connection status icon for iPhone. On iPad this was already visible in the right corner of the toolbar, on iPhone an upper left position on top of the navigation bar is chosen. With this change it is possible to recognize connection state without moving through the menus to a remote screen or the server list.
The status icon is not visible when entering the Kodi settings. I will not fix this as the code in this area will anyway change when the settings are moved to main menu.
Screenshots: https://ibb.co/g3CdX7c
Improvement: Global connection status for iPhone
=> Improvement: Global connection status for iPhone

XBMC Remote/MasterViewController.m
Also need to set `highlightedImage` to ensure the correct icon is shown when `cell` has been reused.
Bugfix: Ensure correct MasterVC connection icon on cell reuse
=> Bugfix: Ensure correct MasterVC connection icon on cell reuse

XBMC Remote/iPad/MenuViewController.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3193994#pid3193994).
When using the "NowPlaying" button from the iPad toolbar, all stack views are closed. At the same time the current active menu item (e.g. "Music" or "TV Shows") should be deselected.
Bugfix: Deselect menu when closing all stack views on iPad
=> Bugfix: Deselect menu when closing all stack views on iPad

XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m, XBMC Remote/DetailViewController.xib
This PR removes `detailView` ivar from DetailViewController and its related xib as it is not needed anymore. In addition it brings the dimensions back to the normally used 320x416. The view's dimension was off in the xib since 4 years.
Maintenance: Remove detailView ivar from DetailViewController
Maintenance: Bring back DetailVC xib dimensions to normal
=> Maintenance: Remove detailView ivar from DetailViewController

XBMC Remote/ConvenienceMacros.h, XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m, XBMC Remote/NowPlaying.xib, XBMC Remote/cellViewIPad.xib, XBMC Remote/iPad/MenuViewController.m
This PR does small but visible layout improvements:
1. Use `darkGrayColor` for progress slider's `maximumTrackTintColor`. Improves contrast to current position, especially on non-seekable items.
2. Menu and playlist now share same vertical gray separator of width 0.5. In consequence `playlistLeftShadow` has been removed. A define has been introduced to set the separator width.
Screenshots: https://ibb.co/ggjb81X
Improvement: Small layout improvements to progressbar and iPad left menu
=> Improvement: Small layout improvements to progressbar and iPad left menu

XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m, XBMC Remote/ViewControllerIPad.h, XBMC Remote/ViewControllerIPad.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/1039.
This PR implements the "blurred cover" feature for iPad. If this feature is enabled (this is the app's default) and no cover is present, or if this feature is disabled, the background shows the fanart. In fullscreen mode the toolbar is made semi-transparent for an improved look.
Screenshots: https://ibb.co/7r9hYC1
Feature: Blurred cover for iPad
=> Feature: Blurred cover for iPad

XBMC Remote/AppDelegate.h, XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/VersionCheck.h, XBMC Remote/VersionCheck.m, XBMC Remote/tcpJSONRPC.m
This PR implements the feature to follow Kodi's setting "Show empty TV shows" as suggested [in this forum thread](https://forum.kodi.tv/showthread.php?tid=359717&pid=3195435#pid3195435). The setting is read when the app is connecting to Kodi server and applied when reloading the library in the app via pull-to-sync.
Feature: Follow Kodi's "Show empty TV shows" setting
=> Feature: Follow Kodi's "Show empty TV shows" setting

XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m
This PR reworks the playback states of NowPlaying when receiving the response to `@"Player.GetProperties"`. Variable names are improved (e.g. `canSeek` instead `canseek`), logic is simplified, comments are added, code sections are separated by new lines and existing helper methods are used.
Maintenance: Rework NowPlaying playback states
=> Maintenance: Rework NowPlaying playback states

XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m
relates to https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/1042
The current implementation is not optimal and shows some unpredictable behaviour. Some of the current seen issues are caused by iOS17 (missing scroll indicator when adding a searchbar as `UITableView's` `tableHeaderView`, or too wide searchbars).
But there are general flaws in the implementation like re-creating the searchbar with each switch between list view and collection view, removing and adding searchbar from views multiple times. I prepared a change which reworks this but has a few workarounds which I would like to have 2nd opinion on.
- Keep searchbar on top of lists, so pulldown-to-search
- Keep active searchbar detached from list to be able to scroll the filtered result list
- Keep searchbar inside the …
=> Maintenance: Internal rework related to searchbar

XBMC Remote/HostManagementViewController.m
The server list scroll indicator shall be always white as the list uses a dark background always.
Bugfix: Use white scroll indicator in server list
=> Bugfix: Use white scroll indicator in server list

XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/1007.
As discussed in https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/1044 a workaround was found to make the scroll indicator visible again for several views. This PR introduces this workaround for the main library view only. Other view do not seem to be impacted by this problem.
Bugfix: Make scroll indicators visible in iOS17
=> Bugfix: Make scroll indicators visible in iOS17

XBMC Remote/NowPlaying.m
This PR fixes the order of the play control buttons for iPad. 
Wrong order as STOP, SEEK BACK, _PREV_, PLAY, _NEXT_, SEEK FWD, ...
Correct order is STOP, _PREV_, SEEK BACK, PLAY, SEEK FWD, _NEXT_, ...
Bugfix: Fix order of play control buttons for iPad
=> Bugfix: Fix order of play control buttons for iPad

XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m, XBMC Remote/DetailViewController.xib
Fixes a regression of https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/1043 which was reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3197156#pid3197156).
The PR re-introduces the `UIView` `maskView` to DetailViewController which is required to be able to set `clipsToBounds` to hide the inactive elements (e.g. more items menu or grid view) out of sight on iPad. Directly setting a mask for `self.view` is not possible as this would not allow to add visible shadows (see `addShadowsToView`) around the masked area.
Bugfix: iPad stack view did not mask bounds
=> Bugfix: iPad stack view did not mask bounds

XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/1037.
With the rework of the searchbar it now became obvious that the dimension of the _inactive_ searchbar was not correctly set. The searchbar needs to use the the view's `bounds` width.
Bugfix: Use correct width for inactive searchbar
=> Bugfix: Use correct width for inactive searchbar

XBMC Remote/NowPlaying.xib
Use contentMode "Center" for overlay labels. Avoids moving text labels when toggling fullscreen on/off on iPad.
Bugfix: Moving text labels in NowPlaying overlay when toggling iPad fullscreen mode
=> Bugfix: Moving text labels in NowPlaying overlay when toggling iPad fullscreen mode

XBMC Remote/ViewControllerIPad.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3200266#pid3200266).
While in NowPlaying fullscreen the iPad main menu should not be resizable. This is ensured with an early return in `touchesMoved:withEvent`.
Bugfix: Do not resize the iPad menu if in NowPlaying fullscreen
=> Bugfix: Do not resize the iPad menu if in NowPlaying fullscreen

XBMC Remote/DetailViewController.m, XBMC Remote/PosterCell.m, XBMC Remote/RecentlyAddedCell.m
The grid / collection view was using a darker background as the list views. This PR applies changes to let the grid/collection views have the standard application background by using transparent backgrounds where needed. For rounded corners this also required a change to the `PosterCell` class to let a label view follow the borders of the underlying cover. For recently added posters the blue "selected" highlighting is reduced to 1 pixel and the non-selected state simply uses clear background. This enlarges the covers/fanart visibly.
Screenshots (left = old, right = new):
<a href="https://ibb.co/9N8z5tk"><img src="https://i.ibb.co/1LvhW6t/Bildschirmfoto-2024-05-20-um-17-14-42.png" alt="Bildschirmfoto-2024-05-20-um-17-14-42" border="0"></a>
<a href="https://ibb.co/rZCqKQy"><img …
=> Improvement: Use transparent background for grid / collection view

XBMC Remote/NowPlaying.m
Configure SDWebImage to delay loading placeholder for NowPlaying cover. This avoids a shortly visible default cover before the final cover art is shown.
Improvement: NowPlaying does not show default cover before cover art is loaded
=> Improvement: NowPlaying does not show default cover before cover art is loaded

XBMC Remote/DetailViewController.m
This PR adds the possibility to show the watched flag for seasons in the so-called episodesView.
Screenshot: https://ibb.co/QHPYSnb
Feature: show watched flag for seasons
=> Feature: show watched flag for seasons

XBMC Remote/HostViewController.h, XBMC Remote/HostViewController.m, XBMC Remote/HostViewController.xib
Suggested by @kambala-decapitator.
"Find Kodi" now only needs to be called once. This is will execute the service discovery for _all_ supported address types. Afterwards the user can select the address type without running "Find Kodi" again.
Important: MAC address can only be resolved using iPv4. The code has been changed to use only IPv4 for this, even if the user selects IPv6 or host name as address type. If IPv4 address cannot be found, the MAC address cannot be resolved.
Improvement: IPv4, IPv6 and host name can be selected after calling Find Kodi once
=> Improvement: IPv4, IPv6 and host name can be changed after calling Find Kodi once

XBMC Remote/NowPlaying.m
This PR fixes the dimension of the separator for the playlist cells. It is now aligned with `mainLabel`.
Screenshots (left = fixed, right = before): 
<a href="https://ibb.co/fq7wsZh"><img src="https://i.ibb.co/wB1mf89/Bildschirmfoto-2024-06-16-um-12-36-02.png" alt="Bildschirmfoto-2024-06-16-um-12-36-02" border="0"></a>
Bugfix: Align playlist separator inset with main label
=> Bugfix: Align playlist separator inset with main label

XBMC Remote/NowPlaying.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3201148#pid3201148).
A bold font is used to display EXIF data, using an attributed text inside the label `itemDescription`. Therefore it is causing trouble when resetting the font and font size of `itemDescription` when the NowPlaying dimensions were change, e.g. when switching to fullscreen or back. Instead we only keep the desired font size and set the font inside the conditions for VIDEO and MUSIC playback.
Bugfix: EXIF details font toggling between bold and normal
=> Bugfix: EXIF details font toggling between bold and normal

XBMC Remote/NowPlaying.xib
Resolves and issues reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3201144#pid3201144).
Keep HiRes Audio logo within overlay boundaries. Place other bottom labels and images views centric around horizontal middle of overlay.
Improvement: keep HiRes logo within overlay boundaries
=> Improvement: keep HiRes logo within overlay boundaries

XBMC Remote/NowPlaying.m, XBMC Remote/NowPlaying.xib
Implements a suggestion from [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3201148#pid3201148).
The Edit button is now initialized hidden. Its visibility is controlled by the active playlist type which makes it hidden for pictures playlist and visible for music and video playlists.
Improvement: Edit button visibility controlled by active playlist type
=> Improvement: Edit button visibility controlled by active playlist type

XBMC Remote/DetailViewController.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3201107#pid3201107).
The `topOverlay` view which needs to cover the whole fake searchbar did not autoresize. As a consequence the user might be able to interact with the fake searchbar, which does not work at all. 
This PR makes `tapOverlay` autoresizing and also lets the fake searchbar not show "Cancel" anymore. This make it more visible when the search is active (by showing "Cancel") and also avoid potentially irritating UI behaviour (textfield becomes active after pressing "Cancel" on the fake searchbar). 
Bugfix: Searchbar not working after pressing cancel
=> Bugfix: Searchbar not working after pressing cancel

XBMC Remote/RightMenuViewController.m
Fixes and issue reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3205628#pid3205628).
This PR just ensures there same dimension of `MessagesView` instances are used for both remote screen and custom button view.
Bugfix: Use same message dimension for remote and custom button screen
=> Bugfix: Use same message dimension for remote and custom button screen

XBMC Remote/RightMenuViewController.m
Elements of embedded remote need a transparent background. Others keep default custom button background color. This lets the embedded remote use the gradient background which darkens on top at bottom.
Screenshots (left = new, right = before):
<a href="https://ibb.co/pbFGpvV"><img src="https://i.ibb.co/LY7bfzj/Bildschirmfoto-2024-06-28-um-15-01-37.png" alt="Bildschirmfoto-2024-06-28-um-15-01-37" border="0"></a>
Bugfix: Embedded remote needs transparent background
=> Bugfix: Embedded remote needs transparent background

XBMC Remote/NowPlaying.m
Register to `UIApplicationDidEnterBackgroundNotification` and end `timer`.
Bugfix: Let NowPlaying handle entering background
=> Let NowPlaying handle entering background

XBMC Remote/DetailViewController.m
Fixes an error reported via a recent AppStore review. 
Even in case the JSON API responds with error for the current request it is required to send the next set of Global Search JSON requests and walk through the whole list of Global Search JSON commands. This ensures we are not stuck with a never ending animation.
Bugfix: Resolve never ending Global Search animation
=> Bugfix: Resolve never ending Global Search animation

XBMC Remote/DetailViewController.m
This PR resolves two long-standing issues I was just recognizing.
1. Since the main menu supports separated Live TV and Radio menus the same instance of DetailVC is used for channel lists and recordings. For recording views a different height and font size for the genre label is used as well as hiding `runtime`. Due to cell reuse the `genre` label height, font size and `runtime` label's visibility must be explicitly set for channel list.
2. Since recordings must be synced it is required to set `recordingListView` separately. This enables some layout code formerly skipped. Also improve readability of recording plot by non-bold font.
Bugfix: Restore channel list layout after viewing recording list
Improvement: Better readability of recording plot
=> Improvement and fixes for channel and recording lists

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m
Ensure `collectionView` is _always_ initialized in `viewDidLoad`, also if the first tab does not support grid view. Otherwise collection view is not initialized for other tabs of the same controller instance. Also ensure the change of the list view's start frame is only altered after the collection view was initialized. Both are relevant for the settings controller view.
In addition this PR simplifies the configuration for settings view's bottom-up start animation. Two variables, one key and one condition could be removed.
Last change is to ensure the start animation when changing tabs is always same, regardless of the gird/list mode of the former and new tab chosen.
Bugfix: Grid view not working for settings menu
Improvement: Consistent animation when changing tab
=> Rework settings grid view and animation when changing tabs

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m
Add support for longpress on source directories via adding `sheetActions`. To be able to Play/Queue a source directory the key `"filetype"` must be set programmatically to `"directory"` as the API does not return this.
Improvement: Handle longpress for sources and support play/queue
=> Improvement: Handle longpress for sources and support play/queue

XBMC Remote/VolumeSliderView.m
Fixes a warning shown by XCode analyzer that the value assigned to `muteBackgroundImage` was never used.
Maintenance: assigned value was never used (Xcode analyzer warning)
=> Maintenance: assigned value was never used (Xcode analyzer warning)

XBMC Remote/XBMCVirtualKeyboard.h, XBMC Remote/XBMCVirtualKeyboard.m
Remove several ivars and replace by macros. Adapt view and label sizes to match given title. The title label supports maximum 4 lines.
Screenshots:
<a href="https://ibb.co/kcSj4w0"><img src="https://i.ibb.co/6sWzHTb/Bildschirmfoto-2024-06-29-um-10-51-15.png" alt="Bildschirmfoto-2024-06-29-um-10-51-15" border="0"></a>
Improvement: Virtual keyboard title adapts size to given title instead of scaling down font
=> Rework virtual keyboard

XBMC Remote/RemoteController.h, XBMC Remote/RemoteController.m, XBMC Remote/VersionCheck.h, XBMC Remote/VersionCheck.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/427.
This PR does some internal rework of how `RemoteController` handles key presses and touch pad events.
Refactoring the processing of keys into two main methods `processButtonPress` and `processButtonLongPress`. Only in these methods key presses and interpreted and commands are sent to Kodi. This allowed to reduce some distributed preparation and calling of JSON API commands.
Introducing `"Input.ButtonEvent"` (supported since Kodi 19) for the up/down/left/right buttons to match the behaviour of pressing the same on a physical keyboard. This resolves an issue where seek was behaving different while playing videos with and without the progress slider being visible.
_Remark:_ This now results in different behaviour between …
=> Rework RemoteController key handling

XBMC Remote/RightMenuViewController.m
Restores using `getTopPadding`, which avoids vertical moving custom button view after coming back from settings. Applies same message height as for remote only for the messages.
Bugfix: Restore fix for vertical pos of custom button view
=> Bugfix: Restore fix for vertical pos of custom button view

XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.m, XBMC Remote/Utilities.m
This PR fixes an issue reported and discussed in the support forum (see [this post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3206508#pid3206508)). The underlying root cause looks like an iOS issue which came with iOS 16 and lets `boundingRectWithSize` return a wrong label size for some occasions. This PR drops `boundingRectWithSize` and uses `sizeThatFits` instead, which return the correct label dimension (correct = same as auto-layout uses).
Bugfix: calculate correct height of labels when using auto-layout
=> Bugfix: calculate correct height of labels when using auto-layout

XBMC Remote/iPad/StackScrollViewController.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3207569#pid3207569).
This PR resolves an issue where an iPad stack could show wrong bounce-behaviour after entering fullscreen from main stack while having active stacks right of the main stack. Solution is to clear `viewAtRight` and `viewAtRight2` after removing the related stacks from view.
Bugfix: correct iPad stack bounce behaviour after fullscreen
=> Bugfix: correct iPad stack bounce behaviour after fullscreen

XBMC Remote/DetailViewController.m
Fixes a regression of https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/1081, reported via ASC/TestFlight.
Rework changes made earlier to allow longpress actions on sources. Instead of generally changing "filetype" and file mode detection, which caused regressions, now only change the behaviour for items of type "sources".
Bugfix: entering addons via Music/Movies/Videos/TVShows menus
=> Bugfix: entering addons via Music/Movies/Videos/TVShows menus

XBMC Remote/DetailViewController.m
Fixes an issue brought up in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3208330#pid3208330).
1. Use correct name: As `rootLabel` is not set for Settings menu in `AppDelegate` (Settings is not a main menu entry), we need to avoid Settings menu titles fall back to `mainLabel`, but use the dedicated tab's name. 
2. Avoid flickering title: The tab's title does not need to be set inside `handleTabChange`,it is set later again -- called from `displayData:`.
Bugfix: show correct title in Settings menu
=> Bugfix: show correct title in Settings menu

XBMC Remote/NowPlaying.xib
The feature was broken since version 1.15 (regression of the NowPlaying rework merged with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/1004). Since then it was only possible to change the playback speed via the remote screen's buttons. 
This PR just connects back the seek backward/forward buttons of the NowPlaying screen to the existing gestureRecognizer.
Bugfix: set speed via longpress NowPlaying's seek buttons
=> Bugfix: set speed via longpress NowPlaying's seek buttons

XBMC Remote/DetailViewController.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3208424#pid3208424).
To really catch all relevant use cases simply apply the iOS17 workaround in `scrollViewDidScroll`, which is called every time scrolling is performed.
Bugfix: another workaround to make list view scrollbars visible for iOS17
=> Bugfix: another workaround to make list view scrollbars visible for iOS17

XBMC Remote/AppDelegate.h, XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m
Based on reviews, this PR applies several updates to the main menu config inside `AppDelegate`. 
- Remove non-working queue and play options for movie sets
- Remove non-working movie details for video playlist items
- Remove long-press options while browsing in addons
- Remove obsolete `showInfo` assignments to `YES`
- Rename methods to better match their function
- Avoid code duplication by using `action_album` also for album view actions
Maintenance: Review and rework menu config
=> Review and rework menu config

XBMC Remote/ShowInfoViewController.m
Other trailers can anyway not be played and the embedded trailer view is wasting space on the screen in such case.
Improvement: Only show embedded trailer for youtube links
=> Only show embedded trailer for youtube links

XBMC Remote/NowPlaying.m
Addresses feedback given in [this forum thread](https://forum.kodi.tv/showthread.php?tid=378679).
On the NowPlaying screen the remote button was opening the embedded remote (which has limited buttons). With this commit also NowPlaying's remote button will enter the full screen remote as from any other menu. Swiping left the NowPlaying screen is still entering the embedded remote.
Improvement: consistently enter full screen remote when tapping remote button (iPhone)
=> Improvement: consistently enter full screen remote when tapping remote button (iPhone)

XBMC Remote/DetailViewController.m
Addresses an issue raised in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3207569#pid3207569).
Since search bar was reworked in the past months, it is now possible to end an active search via `[self.searchController setActive:NO]` and then continue to execute the toolbar buttons presses. This improves the user experience compared to just ignoring button presses, which was done in an earlier change (https://github.com/xbmc/Official-Kodi-Remote-iOS/commit/c618ffff93904db041ee4dcc9fd30157748f561a) to avoid undesired / improper behaviour.
Improvement: allow toolbar buttons while active search
=> Improvement: allow toolbar buttons while active search

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m, XBMC Remote/NowPlaying.xib, XBMC Remote/VersionCheck.h, XBMC Remote/VersionCheck.m, XBMC Remote/en.lproj/Localizable.strings
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/51.
This PR introduces support for "Play using..." which allows to play content to an external UPnP device. When selecting "Play using..." from the context menu a new action sheet is shown which lists the supported players for the selected item. Once selecting a player, `Player.Open` is triggered for the selected item and player.
There are a few constraints:
- It is not possible to send a playlist item to a UPnP device. When attempting to do so, Kodi stops playback via UPnP and falls back to the default internal player. Therefore playlist items cannot be selected during UPnP playback.
- It is possible to skip to previous as long as this just restarts the title. When attempting to play a previous title, Kodi stops playback via …
=> Support "Play using..." to allow playback to an UPnP device

XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m
Resolves https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/645.
This PR is triggered by user feedback (forums and AppStore review) on playlists jumping while scrolling/editing. Main reason for this complaint is the playlist always automatically scrolls the current playing item into the middle of the view. While this works well (you can see previous and next items) while just letting playback do its job, it becomes a hassle when user drags the playlist to view different section of it, or when user is editing. This PR reworks this in two areas editing and dragging. 
When entering editing mode all items are generally editable, instead of keeping the current playing item not editable. This has the benefit that highlighting the current playing item can be fully removed, which simplifies …
=> Improve playlist user experience

XBMC Remote/NowPlaying.m, XBMC Remote/VolumeSliderView.m
Resolves a review finding from https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/1104.
Calling `invalidate` on `NSTimer` instances in `dealloc` is not required.
Maintenance: No need to invalidate timers in dealloc
=> No need to invalidate timers in dealloc

XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/399.
This PR implements a longpress menu for seasons which allows to queue after current, queue and play a whole season.
Feature: Queue and Play a season via longpress menu
=> Feature: Queue and Play a season via longpress menu

XBMC Remote/DetailViewController.m
- Rework `initSectionNameOverlayView`
- Label now supports 2 rows with the given font
- Background view fits the label instead of just deriving its size from the screen size
- Make transparent (alpha = 0.8)
- Rework section header layout 
- Use `getHeightOfFont`
- Use `"table_arrow_right"` icon (similar to disclosure) and colorize with text color
- Move button to vertical middle on the right side
- Labels width adapted to not overlap with button
Screenshots (left = before, right = new):
https://ibb.co/Hg3bSr5
https://ibb.co/GCZwHy8
Improvement: Use common disclosure button for season/album section headers
Improvement: Section overlay (iPad fullscreen) adapts to font size and supports 2 rows
Improvement: Correct calculation of label heights for given font
=> Rework overlay and season

XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.h, XBMC Remote/HostManagementViewController.m, XBMC Remote/MasterViewController.h, XBMC Remote/MasterViewController.m, XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.h, XBMC Remote/RemoteController.m, XBMC Remote/RightMenuViewController.h, XBMC Remote/RightMenuViewController.m, XBMC Remote/SettingsValuesViewController.h, XBMC Remote/SettingsValuesViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/ViewControllerIPad.m
This PR reworks the approach on how messages are shown. Before, each `UIViewController` had an own instance of `MessagesView` and the messages were presented by it. Now, there is only a single instance of `MessagesView` in either the iPad's or iPhone's main controller. All other `UIVewController`s send notifications which are consumed by this central instance and shown from there. This allows to reduce code to layout and create several instances and it easily aligns the layout of the messages. 
In addition, this PR brings back the messages after executing action from the "Power Menu" (e.g. Audio Library Scan). Those were lost as part of refactoring and unifying the power menu.
Maintenance: Use centralized approach to show messages
Bugfix: Show power menu related messages again
=> Rework messages to centralized approach

XBMC Remote/MasterViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
Ignore `UIAlertController` as top most controller. This avoids showing messages aligned with action sheets on iPhone.
<a href="https://ibb.co/mSK0xyQ"><img src="https://i.ibb.co/8XwbhxF/Bildschirmfoto-2024-09-14-um-22-54-55.png" alt="Bildschirmfoto-2024-09-14-um-22-54-55" border="0"></a>
Bugfix: avoid showing messages aligned with action sheets on iPhone
=> Bugfix: avoid showing messages aligned with action sheets on iPhone

XBMC Remote/playlistCellView.xib
Improves an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3210107#pid3210107), which came in with font scaling rework.
This PR tweaks font scaling and label size for playlist cells to properly show duration of 3-digit minutes ("123 min" instead of "123...").
Screenshots:
<a href="https://ibb.co/SvsMDNr"><img src="https://i.ibb.co/s3mNpjH/Bildschirmfoto-2024-09-22-um-11-34-43.png" alt="Bildschirmfoto-2024-09-22-um-11-34-43" border="0"></a>
Bugfix: Show movie duration of 3-digit minutes properly in playlist
=> Bugfix: Show movie duration of 3-digit minutes properly in playlist

XBMC Remote/iPad/StackScrollViewController.m
This reverts commit c1a0a06958bea76521c9b62505ddc7d26177aca7, reversing changes made to 44f11f82c51beb2b86d54970d79a500e33d03dc9.
Caused more trouble than it fixed. The change broke full screen fanart for e.g. movies on iPad. Not rotating anymore and not leaving fullscreen into a working stack view.
Bugfix: Rotating and leaving iPad fanart fullscreen
=> Bugfix: Roating and leaving iPad fanart fullscreen

XBMC Remote/DetailViewController.m
Present UPnP player list from same origin, controller and view as the action sheet which listed "Play using...". This fixes an issue where the list was potentially shown outside of the visible area.
Screenshots: https://ibb.co/Kq4RpZ3
Bugfix: Present action sheet with UPnP players from correct origin (iPad)
=> Bugfix: Present action sheet with UPnP players from correct origin (iPad)

XBMC Remote/ShowInfoViewController.m, XBMC Remote/ShowInfoViewController.xib
The scroll top/down arrows need to be initialized invisible (alpha = 0). Otherwise setting `scrollView.contentInset` for iPad calls  `scrollViewDidScroll` which would result in fading out the arrow visibly with a 0.3 seconds animation. This does not happen on iPhone, but starting with invisible arrows is desired in any case.
Bugfix: Avoid scroll up arrow to be shortly visible on iPad's detail info screen
=> Bugfix: Avoid scroll up arrow to be shortly visible on iPad's detail info screen

XBMC Remote/DetailViewController.m
This allows the user to always end the fullscreen mode, even while search is active or after selecting an item from a filtered list.
Screenshots: https://ibb.co/fvjFDxY
Bugfix: Keep exit fullscreen button always reachable in iPad fullscreen
=> Bugfix: Keep exit fullscreen button always reachable in iPad fullscreen

XBMC Remote/DetailViewController.m, XBMC Remote/mainMenu.h, XBMC Remote/mainMenu.m
Reset `filterModeType` in `viewDidLoad` and do not carry over to subview. This is not required and avoids showing errors or empty results when selecting an item from a filtered list (e.g. played/unplayed albums, album/song/default artists). This was broken since version 1.11.
Bugfix: Error or no results when selecting an item from filtered list
=> Bugfix: Error or no results when selecting an item from filtered list

XBMC Remote/DetailViewController.m
Resolves an issue (4th issue) reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3210210#pid3210210).
On iPad the so-called corner info (bottom right info text shown in the pane's bottom toolbar) changes its width, depending on whether the "fullscreen" button is shown or not. When changing a tab it is important to make the old text invisible (alpha = 0) before the width is adapted and the new text is displayed (alpha = 1). This avoids visual glitches, especially caused by changing from 1-lined to 2-lined texts.
In addition, this PR 
- reworks the corner info animation to properly serialize fade out, text update and fade in,
- strips bb/html code for iPad corner info as well (already was done for iPhone).
Improvement: Avoid visual glitch in iPad corner info …
=> Rework animations and content of iPad corner info

XBMC Remote/NowPlaying.m, XBMC Remote/Utilities.m
Check if input variable responds to "intValue" inside the helper method `convertTimeFromSeconds` instead of only checking for `NSNumber` type outside.
Maintenance: Handle type check inside the time conversion helper
=> Maintenance: Handle type check inside the time conversion helper

XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/1134.
The ivar `activeLayoutView` shall use `UTableView` type.
Maintenance: activeLayoutView shall use UTableView type
=> Maintenance: activeLayoutView shall use UTableView type

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/1102.
This PR addresses  a long-standing issue around `AppDelegate` in which the menu structure uses `NSArray` instead of `NSDictionary` in manifold places. Now this is reworked to use the desired type from the beginning, which requires some work in other controllers to adapt the processing of `mainMethod` and `mainParameters` to the new type.
Maintenance: Rework AppDelegate to use appropriate types
=> Maintenance: Rework AppDelegate to use appropriate types

XBMC Remote/rightCellView.xib
Resolves an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3210589#pid3210589).
Restore stronger font scaling for custom buttons. This will break too long button description into two line in case required.
Screenshots:
<a href="https://ibb.co/zmLJ1Yb"><img src="https://i.ibb.co/vcrYbGm/Bildschirmfoto-2024-09-26-um-06-46-25.png" alt="Bildschirmfoto-2024-09-26-um-06-46-25" border="0"></a>
Bugfix: Restore stronger font scaling for custom buttons
=> Bugfix: Restore stronger font scaling for custom buttons

XBMC Remote/AppDelegate.m
Resolves an issue reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3210742#pid3210742).
This PR fixes a regression brought in by https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/1097. The configuration for music menu which enables the detail info screen for album/artists has been removed due to lack of testing the fullscreen mode for this use case.
Bugfix: Bring back fullscreen info screen for album/artist
=> Bugfix: Bring back fullscreen info screen for album/artist

XBMC Remote/DetailViewController.m
This fixes rating not being visible for movies and TV Shows in Global Search after once showing cells without this field. Reason is that cell reuse requires the rating label to be explicitly made visible.
Screenshots (left = before, right = after): https://ibb.co/M18hykN
Bugfix: Global Search might not show ratings for movies and TV shows
=> Bugfix: Global Search might not show ratings for movies and TV shows

XBMC Remote/DetailViewController.m
Method heightForRowAtIndexPath shall use same logic as inside cellForRowAtIndexPath.
Fixes an issue reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3211465#pid3211465).
The cell re-use in Global Search is more sensitive as it shows different types of content with different cell layouts. This PR fixes an issue where the cell's height was mismatching between `heightForRowAtIndexPath` and the content used in `cellForRowAtIndexPath`. Now, both use the same logic to retrieve the cell's height.
Bugfix: Ensure correct cell height in heightForRowAtIndexPath
=> Bugfix: Ensure correct cell height in heightForRowAtIndexPath

XBMC Remote/Utilities.m
This PR fixes a memory leak in `averageColor:inverse:autoColorCheck:` where `rawImageRef` was created but never released. This caused a _massive_ memory leak in the use case of TV or Radio channel lists in grid view.
Bugfix: Fix memory leak when calculating average color
=> Bugfix: Fix memory leak when calculating average color

XBMC Remote/DetailViewController.m
The error handling inside `sd_setImageWithURL` ensures the caller receives the `placeholderImage` in case of an error, e.g. when the image cannot be downloaded from the given URL. Therefore always use caller.image as input for the background color calculation inside `setViewColor`. Otherwise, in case `image == nil`, a transparent background could be selected.
Screenshots (left = before, mid = after, right = no error):
<a href="https://ibb.co/TbVST6L"><img src="https://i.ibb.co/vQ7GBpY/Bildschirmfoto-2024-10-05-um-20-18-15.png" alt="Bildschirmfoto-2024-10-05-um-20-18-15" border="0"></a>
Bugfix: Ensure proper background color for section header in case of download  error
=> Bugfix: Ensure proper background color for section header in case of download error

XBMC Remote/NowPlaying.m
As suggested in the support forum this PR adds a small improvement to the NowPlaying screen. Prioritize the release year in the 2nd row when truncating. So, instead of always truncating the tail, we now truncate at middle, if a release year is given.
Screenshots: 
https://i.ibb.co/488Z1Yj/Bildschirmfoto-2024-09-25-um-21-32-03.png
Improvement: NowPlaying info prioritizes release year when truncating
=> Improvement: NowPlaying info prioritizes release year when truncating

XBMC Remote/MasterViewController.m
This PR blocks showing warning/error messages (aka "toaster messages") while the main menu is shown on iPhone. The iPhone main menu is shown in case the central`self.slidingViewController` shows its `underLeftController`, which can be checked by `self.slidingViewController.underLeftShowing`. This avoids that the user cannot enter the server connection view from main menu while the server cannot be connected and throws error warnings.
Screenshots:
<a href="https://ibb.co/LgHVJCy"><img src="https://i.ibb.co/FYCR0B1/Bildschirmfoto-2024-10-04-um-13-28-52.png" alt="Bildschirmfoto-2024-10-04-um-13-28-52" border="0"></a>
Improvement: Messages shall not be shown on iPhone main menu
=> Improvement: Messages shall not be shown on iPhone main menu

XBMC Remote/DetailViewController.xib, XBMC Remote/NowPlaying.xib
This PR changes the layout of the the "No items found" label to ensure the text is not truncated in other languages. 
Following changes are applied:
- Increase width and scale horizontally
- Use minimumScaleFactor = 0.8
- Use numberOfLines = 2 (in case not fitting into a single row, the text will expand to two rows)
- Remove icon and center align text
Screenshots (left = Version 1.15, middle = before this PR, right = this PR):
<a href="https://ibb.co/28MjGbr"><img src="https://i.ibb.co/M81RFXH/Bildschirmfoto-2024-09-29-um-21-54-00.png" alt="Bildschirmfoto-2024-09-29-um-21-54-00" border="0"></a>
Bugfix: Ensure "No items found" is not truncated
=> Bugfix: Ensure "No items found" is not truncated

XBMC Remote/HostManagementViewController.h, XBMC Remote/HostManagementViewController.m, XBMC Remote/InitialSlidingViewController.h, XBMC Remote/InitialSlidingViewController.m, XBMC Remote/MasterViewController.h, XBMC Remote/MasterViewController.m, XBMC Remote/RightMenuViewController.h
Use better matching method name `handleMenuButton` and declare it properly as method of `InitialSlidingViewController`. In addition, remove a not needed includes, not needed method `revealUnderRight:` and its related notification `"revealUnderRight"`.
Maintenance: Rework iPhone menu button implementation
=> Maintenance: Rework iPhone menu button implementation

XBMC Remote/AppDelegate.m, XBMC Remote/InitialSlidingViewController.m, XBMC Remote/MasterViewController.m, XBMC Remote/Utilities.h, XBMC Remote/ViewControllerIPad.h, XBMC Remote/ViewControllerIPad.m, XBMC Remote/en.lproj/Localizable.strings, XBMC Remote/tcpJSONRPC.m
This PR improves the time from App start or from manual server selection until the server is connected. Basically, this is done by two core changes:
1. Loading the last server in `AppDelegates's` `didFinishLaunchingWithOptions` before initializing the main controllers for iPad and iPhone.
2. Calling the heartbeat check method `checkServer` immediately before starting the repeating timer which calls `checkServer`.
3. Trigger restart of timer by notification once a new server was selected.
To be able to show the `HostManagement` popover on iPad (e.g. no last server is defined or last server cannot be connected) the `tcpJSONRPC` is started in `viewDidAppear`.
As we are now connecting faster, the heartbeat timer can use a lower frequency. The timer was increased 5 seconds, and the connection …
=> Improvement: Faster connect to Kodi server

XBMC Remote/NowPlaying.m
The cover thumb used for iPhone's playlist toggle button was not using the maximum (native) pixel resolution of the display and a wrong aspect ratio.
Screenshots (white background for debugging):
<a href="https://ibb.co/QnCHwZG"><img src="https://i.ibb.co/K7LsvYH/Bildschirmfoto-2024-10-12-um-21-49-01.png" alt="Bildschirmfoto-2024-10-12-um-21-49-01" border="0"></a>
Improvement: Use max resolution and correct aspect ratio for iPhone's playlist toggle button
=> Improvement: Use max resolution and correct aspect ratio for iPhone's playlist toggle button

XBMC Remote/DetailViewController.m
This PR improves the animation behaviour of searchbar after leaving iPad fullscreen, and alongside makes some coding style changes.
1. Resolves an issue where list view's searchbar became shortly visible when animating from iPad fullscreen back to grid view by hiding the searchbar (`dataList.tableHeaderView`) once the list view is moved to invisible area. 
2. Avoids a distracting animation of the list view's searchbar when animating back from iPad fullscreen to list view by setting the inset to list view's top.
3. Coding style changes (`toggleFullscreen` re-indentation and removal of unneeded parameter)
Improvement: Avoid glitches of searchbar animation when leaving iPad fullscreen
=> Improvement: Avoid glitches of searchbar animation when leaving iPad fullscreen

XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/733.
This PR reworks the presentation of search results and delivers two main improvements and a small one.
1. The search result list in Global Search does now show the section headers with the item type, e.g. movie or artists. This way it easy to recognize what type of item is shown in the list. 
2. All search results are now sorted by ascending label (for Global Search by "Type" within a section). This improves the user experience where Kodi does not provide sorted lists or the lists are sorted by something else, e.g. playcount for the "Top 100 Songs".
3. Support searching the "year" key in the data, which allows to search for release years of movies, TV Shows, music videos, albums, and songs.
Screenshots (in each pair: left …
=> Rework presentation of search results

XBMC Remote/HostManagementViewController.m, XBMC Remote/NowPlaying.m
Fixes regression of https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/1150.
Do not overwrite `leftBarButtonItem` in `NowPlaying` and `HostManagementViewController`. The `leftBarButtonItem` is already defined in `MasterViewController`. This ensures the correct method `handleMenuButton` is called on pressing the menu button.
Bugfix: Make menu button in server list work again on iPhone
=> Bugfix: Make menu button in server list work again on iPhone

XBMC Remote/AppInfoViewController.xib
Reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3212720#pid3212720).
Enlarge width of `appVersion` label to avoid truncation on iPad.
Screenshots:
<a href="https://ibb.co/fdZR8wg"><img src="https://i.ibb.co/B2vD4Mp/Bildschirmfoto-2024-10-15-um-06-19-55.png" alt="Bildschirmfoto-2024-10-15-um-06-19-55" border="0"></a>
Bugfix: Do not truncate version info on iPad
=> Bugfix: Do not truncate version info on iPad

XBMC Remote/MoreItemsViewController.m
This improves user experience on small screen devices like iPod Touch.
In `MoreItemsViewController`, which is loaded when pressing "..." in menus, there was no font scaling used at all. This PR enables this to improve the user experience on small screen devices.
Screenshots (taken from iPod Touch simulator):
<a href="https://ibb.co/PGGc5F3"><img src="https://i.ibb.co/233vjWm/Bildschirmfoto-2024-10-19-um-17-05-48.png" alt="Bildschirmfoto-2024-10-19-um-17-05-48" border="0"></a>
Improvement: Allow font scaling for MoreItemsVC
=> Improvement: Allow font scaling for MoreItemsVC

XBMC Remote/HostManagementViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/ViewControllerIPad.m, XBMC Remote/en.lproj/Localizable.strings
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/1116.
This PR removes the need confirm power menu actions which include updating/cleaning libraries, leaving Kodi application,  shutting down or hibernating the Kodi system. It also lets Wake-on-LAN only show success (when the command could be issued) or failure (when in need of MAC address).
Improvement: Remove confirmation of power menu actions
=> Improvement: Remove confirmation of power menu actions

XBMC Remote/InitialSlidingViewController.m, XBMC Remote/tcpJSONRPC.m
Fixes two issues reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3212625#pid3212625).
iOS does obviously cause errors when issuing JSON commands right after `applicationWillEnterForeground`, see also https://stackoverflow.com/questions/63621039/. Solution is to add a minor delay of 0.1 seconds before starting the heartbeat timer which will issue the JSON commands to re-connect to the Kodi server.
Root cause was a logic error, which caused `topViewController.view.hidden` to _follow_ the connection state. The desired behaviour is to unhide the view only on an error, and to leave it unchanged else. This error caused the `topViewController`, which is the active controller on an iPhone (e.g. Music or Remote), to be hidden on each successful connection attempt. …
=> Fixes for connection issues after wakeup

XBMC Remote/PosterCell.m
Apply rounded edges to grid view's `labelImageView`. Resolves layout glitch at bottom of grid view thumbs, which caused missing rounded edges.
Screenshots:
<a href="https://ibb.co/fSZ5v9H"><img src="https://i.ibb.co/1nB56MT/Bildschirmfoto-2024-10-27-um-12-09-31.png" alt="Bildschirmfoto-2024-10-27-um-12-09-31" border="0"></a>
Bugfix: Apply rounded edges to grid view thumb's bottom
=> Bugfix: Apply rounded edges to grid view thumb's bottom

XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/XBMCVirtualKeyboard.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/570.
Migrated places where database IDs are processed to use `long` precision. Major area was `NowPlaying`, but also one more situation in `DetailViewController` was identified. In addition, some minor refactoring was done to improve code readability.
Maintenance: Use long type for database IDs
=> Maintenance: Use long type for database IDs

XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m, XBMC Remote/DetailViewController.xib, XBMC Remote/ShowInfoViewController.h, XBMC Remote/ShowInfoViewController.m
This PR does some refactoring to simplify the state machine and logic.
- Remove the need to use ivar `isViewDidLoad` in DetailViewController. Now iPad corner info only requires layout for iPad by adding a fixed space programmatically instead of adding it to xib and removing it for iPhone.
- Remove the need to use ivar `isViewDidLoad` in ShowInfoViewController. Now a check is done _inside_ `createInfo` to only run the layout once.
Maintenance: Remove isViewDidLoad, rework iPad corner info and detail view
=> Maintenance: Remove isViewDidLoad, rework iPad corner info and detail view

XBMC Remote/HostManagementViewController.m
Explicitly add the menu icon for HostManagementVC. This is needed as the server list is shown on iPhone as default and without selecting a menu item, which usually adds the menu icon to the next upcoming controller.
Bugfix: Show menu icon on iPhone server list after launch
=> Bugfix: Show menu icon on iPhone server list after launch

XBMC Remote/DetailViewController.m
Fixes and issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3214668#pid3214668).
The issue was caused by https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/1145, which resulted in GlobalSearch having `method` equal to `nil` instead of `@[@{}]`. This in consequence resulted in sort method and sort order not being restored anymore. This PR fixes this by removing the check for nil when restoring, as it is not required for robustness or function.
Bugfix: restore GlobalSearch sort method and sort order
=> Bugfix: restore GlobalSearch sort method and sort order

XBMC Remote/HostManagementViewController.m, XBMC Remote/MessagesView.m, XBMC Remote/NowPlaying.m, XBMC Remote/tcpJSONRPC.m
Several timers should independent of ongoing dragging / touching events, especially the toast animation, the heartbeat and the NowPlaying updates. This change avoids that toast messages are not disappearing while touching / dragging., that the heartbeat checks and NowPlaying updates continue while dragging.
Improvement: Add timers to RunLoopCommonModes to avoid blockage by dragging a view
Improvement: Continue toast message, NowPlaying and heartbeat while dragging a view
=> Improvement: Add timers to RunLoopCommonModes to avoid blockage by dragging a view

XBMC Remote/NowPlaying.m
This PR improves the titles of actionsheets for playlist items (reachable via longpress on a playlist item).
- Prefer title over label, if present
- Show artist for musicvideos
- Show channel for recordings
- Avoid empty rows by adding newline strings
Screenshots: https://ibb.co/GHgT0f6
Improvement: Simplified actionsheet title for playlist items
=> Improvement: Simplified actionsheet title for playlist items

XBMC Remote/ConvenienceMacros.h, XBMC Remote/NowPlaying.m, XBMC Remote/SDWebImage/SDImageCache.m, XBMC Remote/SDWebImage/SDWebImageDecoder.m, XBMC Remote/SDWebImage/SDWebImageDownloader.m, XBMC Remote/SDWebImage/SDWebImageDownloaderOperation.m, XBMC Remote/SDWebImage/UIImageView+WebCache.m, XBMC Remote/UIImage+Resize/UIImage+Resize.h, XBMC Remote/UIImage+Resize/UIImage+Resize.m, XBMC Remote/Utilities.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/1176.
This PR does another major improvement to the `SDWebImage` cache implementation.
When enabling the `SDWebImage`-setting `shouldDecompressImages`, any `UIImage` loaded from flash to in-memory retained the CG context of the decompressed image. This PR applies a change to the decompression which results in not retaining this copy anymore. The memory consumption for the image cache is reduced to 50%.
When disabling the `SDWebImage`-setting `shouldDecompressImages`, any `UIImage` loaded from flash to in-memory retains the (PNG) data loaded from flash. In this case the memory consumption is reduced to about 60%.
After reviewing the implementation in-depth, it became clear that thumb images are not really fully scaled to the …
=> Rework image cache

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.m, XBMC Remote/MasterViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/ViewControllerIPad.m, XBMC Remote/VolumeSliderView.m, XBMC Remote/tcpJSONRPC.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/1175.
Move `init` of `tcpJSONRPC` to `init` of main iPad/iPhone controllers and do not start the heartbeat in the `init` anymore. Generally hook up starting the heartbeat timer with `applicationDidBecomeActive` instead of `applicationWillEnterForeground` as the socket will be available at this time and no additional timeout is needed.
Improvement: Rework wakeup of tcpJSONRPC
Improvement: Avoid loss of connection during wakeup
=> Rework wakeup of tcpJSONRPC

XBMC Remote/AppDelegate.m, XBMC Remote/ConvenienceMacros.h, XBMC Remote/HostManagementViewController.m, XBMC Remote/HostViewController.m, XBMC Remote/HostViewController.xib, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m, XBMC Remote/tcpJSONRPC.m
Resolves an issue reported via TestFlight. The App shows default values for server port (8080) and tcp port (9090) in the placeholders of the text fields. If the values are not set explicitly, these defaults should be used automatically. This was not done for the server port, which resulted in connection errors in this case.
This PR now changes few things to improve the behaviour and maintainability:
- Set the default for server / tcp port via newly introduced helper methods
- Use app-wide macros for the default values and show these value as placeholders in the UI
Improvement: Use port defaults if not explicitly set
Maintenance: Centralized definition of port defaults
=> Rework handling default server port and tcp port

XBMC Remote/iPad/StackScrollViewController.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3216270#pid3216270).
Stop all animations before moving stack views off screen. This avoids visual glitches when starting an new animation while another one (bounce) is still active.
Bugfix: avoid visual glitch on iPad when closing stack while bounce animation is active
=> Bugfix: avoid visual glitch on iPad when closing stack while bounce animation is active

XBMC Remote/iPad/StackScrollViewController.m
Fullscreen mode ends when moving all stack views off screen. This fixes an issue where stack views were immovable after leaving fullscreen via the NowPlaying button in the toolbar.
Bugfix: iPad stack not movable after leaving fullscreen with toolbar's nowplaying button
=> Bugfix: iPad stack not movable after leaving fullscreen with toolbar's nowplaying button

XBMC Remote/DetailViewController.m
Update the `defaultThumb` before attaching `"_wall"`. This ensures the default thumb with correct dimension is chosen for recordings and timers.
Screenshots:
<a href="https://ibb.co/5LqbBY7"><img src="https://i.ibb.co/jD7ngVp/Bildschirmfoto-2024-11-23-um-10-50-22.png" alt="Bildschirmfoto-2024-11-23-um-10-50-22" border="0"></a>
Bugfix: use correct default thumbs for recordings and timers in grid view
=> Bugfix: use correct default thumbs for recordings and timers in grid view

XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.m, XBMC Remote/HostViewController.m, XBMC Remote/MasterViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/RemoteController.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/ViewControllerIPad.m, XBMC Remote/VolumeSliderView.m, XBMC Remote/XBMCVirtualKeyboard.m, XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m, XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPCError.m, XBMC Remote/iPad/StackScrollViewController.m, XBMC Remote/tcpJSONRPC.m
This PR cleans up several actions in `dealloc` when deallocating objects.
- `delegates` which are _not_ `weak` must be `nil`'ed (`NSStream`, `NSNetService` and `NSNetServiceBrowser`)
- `delegates` which _are_ `weak` do not need to be `nil`'ed
- No need to `invalidate` timers
- No need to `removeObserver`
- No need to clean up properties (`removeAllObjects` or `nil`'ing)
- No need for `removeFromSuperview`
- Removing empty `dealloc`
Maintenance: clean up dealloc
=> Maintenance: clean up dealloc

XBMC Remote/ConvenienceMacros.h, XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/PosterCell.h, XBMC Remote/PosterCell.m, XBMC Remote/RecentlyAddedCell.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
This PR simplifies the layout of `posterLabel` and `labelImageView` by adding both as subviews to `posterThumbnail` instead of `self.contentView`. This way calling `applyRoundedEdgesView` can be removed for both as the new parent view has this applied already.
Correctly place the activity indicators for collection view. As the cell layout might change after rotation, the center must be updated before starting the animation.
Use pixel exact dimension for the item sizes (based on `UIScreen.mainScreen.scale`). Use fixed height for `posterLabelFullscreen`(keeping flexible width) and place it relative to the bottom of the cell.
The blue frame for selected items in collection view now works again when having "rounded edges" disabled. To make this happen, the cell's `posterThumbnail` is scaled …
=> Rework PosterCell and RecentlyAddedCell

XBMC Remote/DetailViewController.m, XBMC Remote/Utilities.h
Call `applyRoundedEdgesView` to process the "rounded corner" setting before applying it to "recently added" view. Do not make `roundedCornerImage` and `roundedCornerView` public to avoid calling these methods outside of `Utilities`. This forces using the methods which check for the "rounded corner" setting.
Bugfix: do not have "rounded corners" always on for "recently added" grid view
=> Bugfix: do not have "rounded corners" always on for "recently added" grid view

XBMC Remote/DetailViewController.m
Reads the configured sort order and uses it when building the section array in case of GlobalSearch sort-by-type. Keeps sorting ascending inside each section.
Bugfix: GlobalSearch by type respects user sort order for section during search
=> Bugfix: GlobalSearch by type respects user sort order for section during search

XBMC Remote/DetailViewController.m, XBMC Remote/PosterCell.m, XBMC Remote/RecentlyAddedCell.h, XBMC Remote/RecentlyAddedCell.m
Introduce method `setRecentlyAddedCellLayout` to manually set object dimensions to avoid erratic change of cell dimensions by auto-layout. Introduce helper method which calculates the frame sizes for all objects to avoid code duplication. The helper is called from init and the manual layout method.
Let the background gradient shadow overlap more with labels. This increases the contrast for the the top row's text.
Screenshots: https://ibb.co/9nZ1k4B (left = new, right = before)
Introduce helper method `setPosterCellLayout` which calculates the frame sizes for all objects to avoid code duplication. The helper is called from init and the manual layout method.
Bugfix: avoid erratic layout change of labels or thumbnails in "recently added" grid view
Improvement: better readability of labels in …
=> Rework RecentlyAddedCell and PosterCell

XBMC Remote/PosterHeaderView.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3217836#pid3217836).
`PosterHeaderView's` background needs to autoresize.
Bugfix: Use full width for section header in fullscreen
=> Bugfix: Use full width for section header in fullscreen

XBMC Remote/DetailViewController.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3218142#pid3218142), as well as a problem found during testing.
1. Present sort-by action from `buttonsView`. This lets the origin stay at the right place when rotating iPad.
2. Present other action sheets from `self.view`. Fixes origins not moving correctly when rotating, e.g. when long pressing albums in Music > Artists > Albums.
Bugfix: keep action sheet's origin after rotation on iPad
=> Bugfix: keep action sheet's origin after rotation on iPad

XBMC Remote/Utilities.m
Fixes a crash reported via AppStore.
`UIGraphicsBeginImageContextWithOptions` cannot handle image sizes of width = 0 or height = 0.
Bugfix: Avoid crash in colorizeImage:withColor:
=> Bugfix: Avoid crash in colorizeImage:withColor:

XBMC Remote/DetailViewController.m
Call `showNoResultsFound` in case no movie sets are found. This avoids never-ending activity indicator when no movie sets are found, as movie sets use an early return.
Bugfix: Fix avoids never-ending activity indicator in movie sets
=> Bugfix: Fix avoids never-ending activity indicator in movie sets

XBMC Remote/MasterViewController.m
Do not show toast messages while in `AppInfoView` on iPhone. The toast message is not placed correctly in this case.
Improvement: do not show toast message while in AppInfoView on iPhone
=> Improvement: do not show toast message while in AppInfoView on iPhone

XBMC Remote/AppDelegate.m
In iPad fullscreen the variable `showInfo` defines, if the detail info view is loaded on item selection. This avoids an additional step, as otherwise an action list with only a single entry ("TV Show Details") was shown, and the single action needed to be selected.
Screenshot showing the now removed single-action menu: https://ibb.co/DVC7FrL
Improvement: directly enter the TV Show details from iPad fullscreen
=> Improvement: directly enter the TV Show details from iPad fullscreen

XBMC Remote/ShowInfoViewController.m
Improve readability of close button in fullscreen fanart by adding text shadow.
Screenshots:
<a href="https://ibb.co/FVSnVc1"><img src="https://i.ibb.co/gV56VQ8/Bildschirmfoto-2024-11-27-um-20-35-42.png" alt="Bildschirmfoto-2024-11-27-um-20-35-42" border="0"></a>
Improvement: better readability of fullscreen fanart close button
=> Improvement: better readability of fullscreen fanart close button

XBMC Remote/ShowInfoViewController.h, XBMC Remote/ShowInfoViewController.m
This change takes care of issue reports regarding non-reliable resume functionality and at the same time addresses review comments in the nearly 4 years old https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/139.
The remote app's playback is centered around playlists. When playing an item, the app first clears the playlist, then adds the item to the playlist and finally plays the playlist item. But when starting playback of a playlist index, `Player.Open` does not support the option to resume playback. Instead, the app added a seek to the desired position. Before seeking, the player needed to start playback, so a sleep of 1 second was added. This worked reasonably ok, but there were reports of unreliable resume or a glitchy user experience as users could see the playback start, …
=> Improvement: use Player.Open to resume

XBMC Remote/RightMenuViewController.m
Fixes a sporadic issue reported via AppStore by early return to avoid out-of-bounds-access.
Bugfix: Fix potential crash when renaming custom buttons
=> Bugfix: Fix potential crash when renaming custom buttons

XBMC Remote/NowPlaying.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3217268#pid3217268).
Current logic ignored playlist updates in Party Mode to avoid flickering. Playlist reloads are handled by `updatePartyModePlaylist` which are only called for each new song in Party Mode. This causes also _user_ triggered playlist changes, e.g. by adding an item, to be ignored as well. With this PR _any_ playlist update again triggers a playlist reload by also calling `updatePartyModePlaylist` while in Party Mode.
Improvement: change logic for playlist updates in Party Mode
=> Improvement: change logic for playlist updates in Party Mode

XBMC Remote/AppDelegate.m
The "resume" point was already requested from Kodi, but the response was not further processed. Now assign and process it as expected. This will bring up the "Resume from ..." option for recordings when playing via the ShowInfoVC.
Feature: support resume for PVR recordings
=> Feature: support resume for PVR recordings

XBMC Remote/ShowInfoViewController.m, XBMC Remote/VersionCheck.h, XBMC Remote/VersionCheck.m
`Player.Open` requires at least Kodi 12 to support `resume` in `options`.
Bugfix: Hide resume option for Kodi 11 or earlier
=> Bugfix: Hide resume option for Kodi 11 or earlier

XBMC Remote/ShowInfoViewController.m
The Broadcast Details where not showing the title correctly while recording is active. This was caused by using a wrong `CGRect` when manipulating the frame dimensions.
Screenshots:
<a href="https://ibb.co/4Tssdg4"><img src="https://i.ibb.co/hWXXf12/Bildschirmfoto-2024-12-27-um-19-03-09.png" alt="Bildschirmfoto-2024-12-27-um-19-03-09" border="0"></a>
Bugfix: Fix Broadcast Details while recording is active
=> Bugfix: Fix Broadcast Details while recording is active

XBMC Remote/Utilities.m
By fault the RGB values were taken from P3 color space, but applied to sRGB. The updated values are using the correct sRGB color space and are taken from official Kodi logos provided on kodi.tv.
Link to logos:
https://kodi.wiki/view/Official:Media_center_logos
Bugfix: Use exact Kodi blue color in sRGB color space
=> Bugfix: Use exact Kodi blue color in sRGB color space

XBMC Remote/NowPlaying.m
Fixes a crash report from AppStore by introducing a check for out-of-bounds before calling `selectRowAtIndexPath`. Also apply a minor coding style change to correctly assign `nil` to a variable of type `NSIndexPath`.
```
Last Exception Backtrace:
0   CoreFoundation                	0x19ab795ec __exceptionPreprocess + 164 (NSException.m:249)
1   libobjc.A.dylib               	0x1980f5244 objc_exception_throw + 88 (objc-exception.mm:356)
2   CoreFoundation                	0x19acc66e0 +[NSException raise:format:] + 128 (NSException.m:0)
3   UIKitCore                     	0x19e69d738 -[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:usingPresentationValues:] + 364 (UITableView.m:0)
4   UIKitCore                     	0x19e69e1c8 -[UITableView …
```
=> Bugfix: Fix crash after scrolling playlist

XBMC Remote/MasterViewController.m
When assigning a recolored icon to `UIImageView's` `image` and `highlightedImage` the new icon might not be updated. This was observed with XCode 15.4 and 16.2.
Screenshot: https://ibb.co/WGBm26z
`.highlightedImage = .image = icon`
1. Changed order: `.image = .highlightedImage = icon`
2. `nil`'ing `highlightedImage` and `image` before assigning icon
3. Assigning icon separately to `highlightedImage` and `image`
Option 3 chosen to avoid any future problems by impact of order of assignment.
1. Successfully connect to a server
2. Enter the server list 
3. Disconnect from the server again
4. Go to main menu -> Still shows blue icon, but with "No connection" description
5. Scrolling the first menu entry (server list) out of the top of the menu also fixes this
Bugfix: Kodi icon might not …
=> Bugfix: Kodi icon might not reflect disconnected state on iPhone

XBMC Remote/DetailViewController.m
Fixes an issue reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3221239#pid3221239).
Need to deselect the item and stop `forceMusicAlbumMode` (which will be enabled again on the next attempt to process an album).
Bugfix: Properly end "Play using..." action sheet
=> Bugfix: Properly end "Play using..." action sheet

XBMC Remote/DetailViewController.m
Fixes a crash reported via AppStore by applying early return in case of `nil` for `value` or `key` when building `item` while processing "Play using...".
```
Last Exception Backtrace:
0   CoreFoundation                	0x19fc4d5ec __exceptionPreprocess + 164 (NSException.m:249)
1   libobjc.A.dylib               	0x19d1c9244 objc_exception_throw + 88 (objc-exception.mm:356)
2   CoreFoundation                	0x19fc61398 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 728 (:-1)
3   CoreFoundation                	0x19fc60734 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 52 (NSDictionary.m:614)
4   Kodi Remote                   	0x102674468 -[DetailViewController addPlayback:indexPath:using:position:shuffle:] + 1336 (DetailViewController.m:4325)
5   UIKitCore …
```
=> Bugfix: Avoid potential crash in "Play using..."

XBMC Remote/MasterViewController.h, XBMC Remote/MasterViewController.m, XBMC Remote/RemoteController.h
`UIViewController` instances are generated fresh each time, there is no need to keep them as ivar or property. `RemoteController` does not need to expose `resetRemote` anymore.
Maintenance: Remove non needed ivars and properties in iPhone MasterVC
=> Maintenance: Remove non needed ivars and properties in iPhone MasterVC

XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m
This PR does some small refactoring around method parameters.
- Replace origin's `x`/`y` parameters with `CGPoint`.
- Remove parameter `fromcontroller:` which anyway was always set to `[Utilities topMostController]`
- Improve checking `sender` in `prepareShowAlbumInfo` to not depend on `DETAIL_VIEW_INFO_ALBUM = 0`
- Ensure to use copies of `AppDelegate.instance.playlist`, when tailoring them, to avoid changing the origin by fault.
Maintenance: Small refactoring in DetailVC
=> Maintenance: Small refactoring in DetailVC

Kodi Remote.xcodeproj/project.pbxproj
The translation for Afrikaans (South Africa) reached >70% and is enabled now.
Feature: Support language af-za
=> Feature: Support language af-za

XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.h, XBMC Remote/NowPlaying.m, XBMC Remote/ShowInfoViewController.h, XBMC Remote/ShowInfoViewController.m
This PR resolves a long-standing concept problem, which also is expected to cause some sporadically reported crashes in via AppStore while using Global Search. 
`choosedTab` represents the selected view in a menu, e.g. Albums, Artists or Genre. The variable is used to read key data, like JSON methods/parameters or sort options, from the menu structure array. The implementation for now did change this ivar while processing actions for Global Search items (like entering next menu level or processing action sheets). This could result in the current Global Search view (always `choosedTab = 0`) temporarily using wrong values of `choosedTab` just to process an item related action. In worst case this could end up in an out-of-bounds access crash.
Instead of changing the ivar `choosedTab`, when …
=> Rework handling of active tab

XBMC Remote/NowPlaying.m
Fixes an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3222438#pid3222438).
When entering the full screen remote from NowPlaying view, the ivar `fromItself` must be set. This will trigger reloading the playlist once NowPlaying is again entering `viewDidAppear`.
Bugfix: Update playlist after coming back from full screen remote on iPhone
=> Bugfix: Update playlist after coming back from full screen remote on iPhone

XBMC Remote/AppDelegate.m
As clarified with Kodi development team ([link to thread](https://forum.kodi.tv/showthread.php?tid=380235)), the recording ids are recreated each time the recording list build inside Kodi. Mapping of ids to recordings is therefor volatile and caching not possible. This PR removes local cache for PVR recordings.
Bugfix: Remove local cache for PVR recordings
Bugfix: Avoid mismatching recording IDs between Remote App and Kodi
=> Bugfix: Remove local cache for PVR recordings

XBMC Remote/Utilities.m
`UIGraphicsBeginImageContextWithOptions` crashes when called with an image size of zero width or height. Perform an early return in this case.
Bugfix: Avoid crash in for roundedCornerImage
=> Bugfix: Avoid crash in roundedCornerImage

XBMC Remote/AppDelegate.m
Correct type from `NSArray` to `NSDictionary`. This data is (currently) not touched, but should use the correct variable types in future.
Maintenance: Correct type from NSArray to NSDictionary
=> Maintenance: Correct type from NSArray to NSDictionary

XBMC Remote/NowPlaying.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/en.lproj/Localizable.strings
Resolves https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/1231.
One string was used in `AppInfoViewController` and replaced in https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/1214. The content only changed in a very minor way, so it was kept for a while to allow translators have it as a reference in Kodi Weblate. Other obsolete strings were formerly used in former releases instead of icons or when user were asked to confirm power or library related actions. Also, there were two strings maintained around the scrubbing speed change, which I reduced the only valid one.
In one interesting case I found even a logical error around the resume function which made this _always_ fail when running the UI in Turkish. This is also fixed by a code change which now generates a `resumeKey` …
=> Maintenance: Remove unused string from localization

XBMC Remote/DetailViewController.m, XBMC Remote/iPad/StackScrollViewController.m
PR is motivated by a discussion [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3222637#pid3222637).
This PR unifies the selection/deselection behaviour for iPad and iPhone by not setting
```
panRecognizer.delaysTouchesBegan = YES;
panRecognizer.delaysTouchesEnded = YES;
```
in iPad's StackViewController. This is not required as sliding the views is not impacted, but an unwanted side effect of non-visible selections is gone.
Generally this PR reworks the strategy to show the selection of items. The selection is removed when showing an action sheet. The details for the selected item are anyway shown on top of the action sheet, on iPad there is a pointer to the touched origin and on iPhone the selection is most cases hidden behind the action sheet. Now, a selection …
=> Rework strategy to select/deselect items

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m
This PR adds an improvement suggested via AppStore: Directly play TV/Radio channels on selection, instead of always bringing up the action sheet with all options. The action sheet can still be brought up by long press. This updated behaviour is aligned with Kodi UI.
Improvement: Play TV/Radio channels on selection
Maintenance: Rework menu parameters forcePlayback and forceActionsheet
=> Play TV/Radio channels on selection

XBMC Remote/NowPlaying.m
Picks up a suggestion from [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3227084#pid3227084).
Let the 2nd row show "artist" only, not "album - artist" which often made the artist non-readable as the album name took all the available space.
Screenshots:
https://ibb.co/5gH1nnt1
Improvement: Music playlist items shall only show song title and artist
=> Music playlist items shall only show song title and artist

XBMC Remote/Utilities.m
Fixes a crash reported via AppStore. Perform early return in `isValidIP6Address` in case `utf8 == NULL` as otherwise `inet_pton` will crash.
Bugfix: Early return to avoid crash in inet_pton
=> Bugfix: Early return to avoid crash in inet_pton

XBMC Remote/DetailViewController.m
Implements an improvement suggested in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3229234#pid3229234).
This PR improves the search results by adding both the album name and artist to the search string. For albums with common names like Tailor Swift's "1989" this drastically improves the search result.
Improvement: Use both album and artist for Wikipedia search
=> Improvement: Use both album and artist for Wikipedia search

XBMC Remote/VolumeSliderView.m
This PR does some small rework related to volume changes. 
First, volume changes are blocked when the server is not connected. Before this change users could change the volume, and by that also the displayed volume (on iPad), while the server was disconnected. This makes no sense.
Second, set volume to 0 (displayed value on iPad and volume slider) when no server is connected. Before this change the volume of the formerly connected server was still valid.
Third, the step size is now more fine granular and allows 1% steps.
Improvement: Volume changes blocked when not connected
Improvement: Volume set to 0 when not connected
Improvement: 1% step size for volume changes
=> Rework volume change

XBMC Remote/AppDelegate.m, XBMC Remote/DetailViewController.m, XBMC Remote/ShowInfoViewController.m
First, this can be derived from being in TV Show banner mode (when in `tvshowsView` and not preferring posters). Second, the separators are anyway not visible as covered by banners.
Maintenance: Remove blackTableSeparator special handling
=> Remove blackTableSeparator special handling

Kodi Remote.xcodeproj/project.pbxproj, XBMC Remote/DetailViewController.m, XBMC Remote/SharingActivityItemSource/SharingActivityItemSource.h, XBMC Remote/SharingActivityItemSource/SharingActivityItemSource.m, XBMC Remote/en.lproj/Localizable.strings
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/702.
This PR adds the option to share an item's URL with other applications or copying it to clipboard. This URL can be used as download link to play/download the selected item through another application on your iOS device, e.g. by pasting the URL to VLC. The item must be a downloadable file, the Remote App will not offer the option in other cases. The Share menu will show the item's label and a thumbnail (in case no item thumbnail is available the Remote App's logo is shown).
Screenshots: https://ibb.co/zhLMyWHx
Important: The iOS Remote App will not implement local playback itself as the iOS `AVPlayer` has *very* limited support for audio and video formats.
Feature: Share URL of item
=> Feature: Share URL of item

XBMC Remote/MasterViewController.m, XBMC Remote/ViewControllerIPad.m
This PR improves usability as the "clearing cache" popover is for sure readable by the user and does not just look like an unwanted glitch because clearing the cache is usually finished really quick.
Improvement: Show "clearing cache" popover at least for two seconds
=> Show "clearing cache" popover at least for two seconds

XBMC Remote/DetailViewController.m
This PR reworks building action sheets. 
- Better naming by using `showActionSheetWithTitle`
- Centralized trim regarding "Play Using...", "Share", "Play Trailer" and "Mark as watch/unwatched"
- Fixes missing "Share" option in few use cases
- Show alert message instead of misusing action sheet
- Unifies the action sheet title for items.
- Will not show "file" or "directory" in 2nd row anymore while in file browsing mode.
Maintenance: Rework building action sheets
Bugfix: Fixes missing "Share" option in few use cases
Bugfix: Do not show "file" or "directory" in action sheet header for items in file browser
=> Maintenance: Rework building action sheets

XBMC Remote/AppDelegate.m
Fixes a regression caused by https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/1281. Bring back `applicationWillEnterForeground` after removing by fault.
Bugfix: Add applicationWillEnterForeground after removing by fault
=> Bugfix: Add applicationWillEnterForeground after removing by fault

XBMC Remote/HostManagementViewController.m, XBMC Remote/InitialSlidingViewController.h, XBMC Remote/InitialSlidingViewController.m, XBMC Remote/MasterViewController.h, XBMC Remote/MasterViewController.m
`InitialSlidingVC` is the main controller for iPhone. It has the top, the underleft and underright controller. When starting, the top controller is either the default `HostManagementVC` or any other menu controller defined by the user settings. The underleft controller is always the main menu (= `MasterVC`). These two controllers (top and underleft) should be created and assigned when `InitialSlidingVC` is initialized.
In addition apply a small refactoring to make `navController` a local variable instead of using ivar.
Maintenance: Rework iPhone main controller initialization
=> Maintenance: Rework iPhone main controller initialization

XBMC Remote/ActorCell.m, XBMC Remote/AppDelegate.m, XBMC Remote/ClearCacheView.m, XBMC Remote/ConvenienceMacros.h, XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.m, XBMC Remote/MasterViewController.m, XBMC Remote/NowPlaying.m, XBMC Remote/PlaylistProgressView.m, XBMC Remote/PosterCell.m, XBMC Remote/PosterHeaderView.m, XBMC Remote/RecentlyAddedCell.m, XBMC Remote/RemoteController.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/SettingsValuesViewController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/Utilities.m, XBMC Remote/ViewControllerIPad.m, XBMC Remote/iPad/MenuViewController.m
This PR does some color cleanup. It removes some unused color definitions and background views. It introduced the new macros for color at a central place and it partially unifies colors between certain UI elements.
I keep this non-squashed for easier review. Once approved I plan to squash the introduction of the new defines into a single commit.
Maintenance: Cleanup colors
=> Maintenance: Cleanup colors

XBMC Remote/DetailViewController.m, XBMC Remote/NowPlaying.m
Fixes an issue where the NowPlaying screen was not having correct dimensions when entering it from library view.
Screenshots (simulator iPod Touch 7G, iOS 15.5):
<a href="https://ibb.co/BmMcvLG"><img src="https://i.ibb.co/kpC5zKJ/Bildschirmfoto-2025-06-24-um-09-34-15.png" alt="Bildschirmfoto-2025-06-24-um-09-34-15" border="0"></a>
Bugfix: NowPlaying dimensions potentially wrong after entering from library view
=> Bugfix: NowPlaying dimensions potentially wrong after entering from library view

XBMC Remote/DetailViewController.m
This PR bring some small improvements to the iPad corner info layout:
- More space for iPad corner info (extends a little to the right)
- Same position for iPad fullscreen toggle button when toggling in portrait mode
- Avoid magic numbers in iPad corner info layout
What's the iPad corner info:
<a href="https://imgbb.com/"><img src="https://i.ibb.co/5X2fMjvW/Bildschirmfoto-2025-06-22-um-14-07-20.png" alt="Bildschirmfoto-2025-06-22-um-14-07-20" border="0"></a>
Improvement: More space for iPad corner info
Improvement: Same position for iPad fullscreen toggle button when toggling in portrait mode
Maintenance: Avoid magic numbers in iPad corner info layout
=> Improvement: Small rework related to iPad corner info

XBMC Remote/ActorCell.m, XBMC Remote/AppInfoViewController.m, XBMC Remote/CustomNavigationController.m, XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.m, XBMC Remote/InitialSlidingViewController.m, XBMC Remote/MasterViewController.m, XBMC Remote/MoreItemsViewController.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/SettingsValuesViewController.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/iPad/MenuViewController.m, XBMC Remote/iPad/StackScrollViewController.m, XBMC Remote/jsonDataCell.m
Initially I only wanted to remove the anyway invisible footer on iPhone's main menu. In addition, this PR now removes the implementation of several framework methods which only return the default (`...HeaderInSection`, `...FooterInSection`) or where only `[super method]` is called.
Maintenance: Cleanup obsolete framework methods
=> Maintenance: Cleanup obsolete framework methods

XBMC Remote/ActorCell.h, XBMC Remote/ActorCell.m, XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m, XBMC Remote/DetailViewController.m, XBMC Remote/HostManagementViewController.m, XBMC Remote/PosterCell.m, XBMC Remote/PosterHeaderView.m, XBMC Remote/RecentlyAddedCell.m, XBMC Remote/ShowInfoViewController.m, XBMC Remote/ViewControllerIPad.m, XBMC Remote/iPad/StackScrollViewController.m
- Minor rework of `ActorCell` and `longTimeout` animation
- Remove unneeded condition to handle `sectionTitle == nil` when creating section headers
- Remove magic numbers
Maintenance: Internal refactoring to avoid magic numbers
Improvement: Avoid potential overlap of labels and accessories in actor table view
=> Code clean up and some rework

Kodi Remote.xcodeproj/project.pbxproj, XBMC Remote/BaseMasterViewController.h, XBMC Remote/BaseMasterViewController.m, XBMC Remote/MasterViewController.h, XBMC Remote/MasterViewController.m, XBMC Remote/ViewControllerIPad.h, XBMC Remote/ViewControllerIPad.m
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/1124.
This PR introduces the base class `BaseMasterViewController` to hold common code which is shared between both iPad's main controller `ViewControllerIPad` and iPhone's `MasterViewController`. This reduces code duplication by moving the following methods and related notification registrations to the new base class:
- `handleDidEnterBackground`
- `handleEnterForeground`
- `handleTcpJSONRPCChangeServerStatus` with its helper `changeServerStatus`
- `handleXBMCServerHasChanged`
- `handleLibraryNotification`
- `handleLocalNetworkAccessError`
- `startClearAppDiskCache` and `clearAppDiskCacheFinished`
- `connectionStatus`
Also moves calling `addClearCacheMessage` into `viewWillAppear`, which fixes a layout issue on iPhone where …
=> Maintenance: Introduce a base class for the iPhone and iPad main controller

XBMC Remote/DetailViewController.h, XBMC Remote/DetailViewController.m, XBMC Remote/DetailViewController.xib, XBMC Remote/HostManagementViewController.h, XBMC Remote/HostManagementViewController.m, XBMC Remote/HostManagementViewController.xib, XBMC Remote/RightMenuViewController.m, XBMC Remote/ShowInfoViewController.m
Inspired by #1290 but avoiding the complications caused when also using frosted glass for the navigation bar. The implementation is done for the relevant toolbars DetailVC (library view), RightMenuVC (custom button view), HostManagementVC (server list view) and ShowInfoVC (item's detail view).
In future I might replace the remaining two instances of `UIToolbar` by views with buttons. This will avoid the -- for now undesired -- visual change when iOS26 introduces "liquid glass".
Screenshots of library view:
<a href="https://ibb.co/8nd649c8"><img src="https://i.ibb.co/JWy5FHQk/Bildschirmfoto-2025-07-26-um-17-23-45.png" alt="Bildschirmfoto-2025-07-26-um-17-23-45" border="0"></a>
Improvement: Use frosted glass effect for toolbars
=> Improvement: Use frosted glass effect for toolbars

XBMC Remote/HostViewController.m, XBMC Remote/HostViewController.xib, XBMC Remote/InitialSlidingViewController.m, XBMC Remote/InitialSlidingViewController.xib
On iPhone with wide screen, e.g. iPhone 16 Pro Max, both the server list view (`HostManagementVC`) and the server search view (`HostVC`) have an incorrect layout. In the server list the `InitialSldingVC`'s must be auto-scaling and the vertical shadow must be applied with `navController's` frame dimensions. In the server search view `discoveredInstancesView` must be kept right outside the visible area until results are shown. This needs the view to be programmatically placed there, instead of just hardcoding a position in the xib which worked for most display widths until now.
Screenshot from iPhone 16 Pro Max: https://postimg.cc/yWVRZ0YL (each pair shows left = before, right = after)
Bugfix: Fix server list / search views for iPhones with wide screen
=> Bugfix: Fix server list / search views for iPhones with wide screen

XBMC Remote/HostManagementViewController.m, XBMC Remote/Utilities.h, XBMC Remote/Utilities.m
Closes #633.
Stop re-connection attempts after user selected Quit Application, Shutdown System, Hibernate System or Suspend System from the power menu and Kodi reported success. To stay consistent with the status reflected in the UI, the current selected server is unselected. After Remote App relaunch there is no server connection attempted to be connected again. The user needs to select the desired server again.
Improvement: Do not continue re-connect after quit/shutdown/hibernate/suspend
=> Improvement: Do not continue re-connect after quit/shutdown/hibernate/suspend

XBMC Remote/HostManagementViewController.m, XBMC Remote/serverListCellView.xib
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/1309.
The current implementation uses 1 line for the server name (left aligned) and the IP / host name (right aligned). This way, especially on devices with smaller display width, one or both labels are quite short and cut the text. Even on wider screens this might happen, depending on the text to show.
This PR changes the layout to use 2 lines, top = server name, bottom = IP / host name. The font size, color and label positions were chosen to highlight the server name and keep both lines visually closely coupled.
Screenshots:
<a href="https://ibb.co/0ynHw9Rx"><img src="https://i.ibb.co/yFNH3kcr/Bildschirmfoto-2025-08-23-um-09-23-24.png" alt="Bildschirmfoto-2025-08-23-um-09-23-24" border="0"></a>
Improvement: Use full width …
=> Improvement: Use full width for server name and IP / host name

XBMC Remote/DetailViewController.m, XBMC Remote/RightMenuViewController.m, XBMC Remote/SettingsValuesViewController.m
Do not save custom button's icon name, except for downloadable images (used only for add-ons). Instead, derive the custom button icon from the button's executed command. This avoids the remote app not being able to load icons from its image library in case of renaming. This also introduces custom button icons for actions and windows.
Screenshots: https://ibb.co/S7xS8p2B
Improvement: Ensure that custom buttons show icons
=> Improvement: Ensure that custom buttons show icons

XBMC Remote/SettingsValuesViewController.m
The settings cell tint should use `systemBlue` for better readability of accessory check marks. This is well recognizable from the screenshots in dark and light mode.
For iOS 17.2 (and others?) `heightForRowAtIndexPath` is called before `willDisplayCell`, which results in wrong cell sizes. This is avoided when finishing the cell layout in `cellForRowAtIndexPath`.
Screenshots (top = new, bottom = before): https://ibb.co/BVh7bj9t
Improvement: Better readability of accessory check marks for settings on iPad
Bugfix: Fix layout for settings cells for some iOS versions
=> Rework settings layout for iPad and some iOS versions

XBMC Remote/SettingsValuesViewController.m
Custom buttons for multi-select settings (e.g. "Skip steps") were always sending a malformatted command, not sending the array of values, but an empty string. Custom buttons for editable settings (e.g. "Track naming template") were always sending an empty string instead of the desired value.
Bugfix: Make custom buttons work for multi-select and editable settings
=> Bugfix: Make custom buttons work for multi-select and editable settings

XBMC Remote/DetailViewController.m
Fixes a regression caused by https://github.com/xbmc/Official-Kodi-Remote-iOS/commit/7d9936f7923c818528f8dd74ccd76a86958b6df5 and reported in https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/1328. The regression caused showing multiple results without translations: "x results" was shown (x > 1).
Keep cast to `(int)` to avoid warning when using the `"%d"` argument. The `"%d"` argument is part of already translated strings for many languages and shall be kept.
Bugfix: Fix showing amount of results in different languages
=> Bugfix: Fix showing amount of results in different languages

XBMC Remote/HostManagementViewController.m, XBMC Remote/InitialSlidingViewController.m
Fixes a regression caused by reworking iPhone main controller initialization (0adb368b). The issue fixed is that `underRightVC` became visible for the `HostManagmentVC` (server list view) once the NowPlaying screen was entered before.
Bugfix: Disable underRightVC for server list view
=> Bugfix: Disable underRightVC for server list view

XBMC Remote/DetailViewController.m
This PR fixes a minor visual glitch reported [in this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3242227#pid3242227).
Do not update `topNavigationLabel` in iPad fullscreen mode. Avoids that `topNavigationLabel` becomes visible (alpha = 1) again in fullscreen after pull-to-sync.
Bugfix: Do not make iPad corner visible after pull-to-sync in fullscreen
=> Bugfix: Do not make iPad corner visible after pull-to-sync in fullscreen

XBMC Remote/RightMenuViewController.m, XBMC Remote/rightCellView.xib
Minor cleanup: Remove unused `UIImageView` from `rightCellView`.
Maintenance: Remove unused UIImageView from rightCellView
=> Maintenance: Remove unused UIImageView from rightCellView
